objects/AAV_Asset_Availability__c.object
<CustomObject>
    <description>Object to track Asset/Product availability on product configuration.</description>
    <label>Asset Availability</label>
    <nameField>
        <displayFormat>AAV-{00000000}</displayFormat>
        <label>Asset Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Availabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Equipment_Size__c</fullName>
        <formula>TEXT(Product2.Container_Size__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Equipment Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this asset.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Formula field utilizing VF page/ merge fields to log effort task on Case.  SDT-4271</description>
        <formula>if( $Profile.Name = &quot;Customer Service&quot;,HYPERLINK(&quot;/apex/GenTaskPage?id=&quot;&amp; Id ,CaseNumber,&quot;_self&quot;),HYPERLINK(&quot;/lightning/r/&quot;&amp; CASESAFEID(Id) &amp; &quot;/view&quot;,CaseNumber, &quot;_self&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Override_Comment__c</fullName>
        <inlineHelpText>Provide the SLA Override Comments if Bypass SLA Override Reason is selected as &apos;Other&apos;.</inlineHelpText>
        <label>SLA Override Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SLA_Override_Reason__c</fullName>
        <description>The field provide SLA Override reason in the case when the Service Date is not equal to the SLA Date.</description>
        <label>SLA Override Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Repairs</fullName>
                </value>
                <value>
                    <fullName>Corporate Visit/Walkthrough</fullName>
                </value>
                <value>
                    <fullName>Power Outage</fullName>
                </value>
                <value>
                    <fullName>Potential Violation</fullName>
                </value>
                <value>
                    <fullName>Weather/Natural Disaster</fullName>
                </value>
                <value>
                    <fullName>Internal Error</fullName>
                </value>
                <value>
                    <fullName>Vendor Error</fullName>
                </value>
                <value>
                    <fullName>Vendor not able to meet SLA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>NAM/PM</fullName>
                    <isActive>false</isActive>
                    <label>NAM/PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Acorn Issue Tracking Number, AKA T-Number</description>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Comment__c.object
<CustomObject>
    <description>This object stores the value of the Case/Task Comments</description>
    <fields>
        <fullName>Acorn_Tracking_Number__c</fullName>
        <description>this field is updated from case tracking number</description>
        <label>Acorn Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Holds the value of the case Number</description>
        <label>Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Communication_Log_Type_Name__c</fullName>
        <label>Communication Log Type Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Captures the object the comment is related to.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workflow_TeamUser__c</fullName>
        <description>Source System Acorn</description>
        <label>Team/User</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Log</label>
        <type>Checkbox</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <recordTypes>
        <fullName>Acorn_Ticket_Comment</fullName>
        <active>true</active>
        <description>Holds Acorn Ticket Comment records</description>
        <label>Acorn Ticket Comment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Comment_Log_Detail__mdt.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Comment Log Detail</label>
    <pluralLabel>Comment Log Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>TEXT(VALUE(SBQQ__Opportunity2__r.Case__r.CaseNumber))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/AAV_Delivery_Override_Comment__c.field-meta.xml
<CustomField>
    <fullName>AAV_Delivery_Override_Comment__c</fullName>
    <description>This field will be used to capture the comment by end user for selecting non-available delivery day</description>
    <label>Delivery Override Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/AAV_Delivery_Override_Reason__c.field-meta.xml
<CustomField>
    <fullName>AAV_Delivery_Override_Reason__c</fullName>
    <description>This field will be capture in case of un-available days selected for Delivery</description>
    <label>Delivery Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Desired Date</fullName>
            </value>
            <value>
                <fullName>WM Confirmed Availability</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.
If you want to change the Start Date, please update the Vendor Commit Date on the Bundle.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SLA_Override_Comment__c.field-meta.xml
<CustomField>
    <fullName>SLA_Override_Comment__c</fullName>
    <label>SLA Override Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SLA_Override_Reason__c.field-meta.xml
<CustomField>
    <fullName>SLA_Override_Reason__c</fullName>
    <label>SLA Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repairs</fullName>
            </value>
            <value>
                <fullName>Corporate Visit/Walkthrough</fullName>
            </value>
            <value>
                <fullName>Power Outage</fullName>
            </value>
            <value>
                <fullName>Potential Violation</fullName>
            </value>
            <value>
                <fullName>Weather/Natural Disaster</fullName>
            </value>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>Vendor Error</fullName>
            </value>
            <value>
                <fullName>Vendor not able to meet SLA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/QuoteProcurementIntegrationService.cls
/**
 * @description QuoteProcurementIntegrationService - External integration layer
 *
 * This service handles integrations with external systems including SLA calculations,
 * Asset Availability API, and special handling flags.
 *
 * Key Responsibilities:
 * - SLA override comment management
 * - Asset Availability API integration
 * - Alternate product updates
 * - Special handling flags
 *
 * @author Waste Management
 * @date 2025
 * @group Service Layer - Integration
 */
public with sharing class QuoteProcurementIntegrationService {

    // ========================================================================
    // PUBLIC API - SLA OPERATIONS
    // ========================================================================

    /**
     * @description Add comment for SLA override from Intake
     * Refactored from: addCommentForSLAOverrideFromIntake() in QuoteProcurementController
     * @param caseId The Case ID
     */
    @AuraEnabled
    public static void addCommentForSLAOverrideFromIntake(String caseId) {
        addCommentForSLAOverride(caseId, null, null);
    }

    /**
     * @description Add comment for SLA override from MIF Flow
     * Refactored from: addCommentForSLAOverrideFromMIF() in QuoteProcurementController
     * @param input List of input wrappers
     */
    @InvocableMethod(label='Add Comment for SLA Override'
                    description='This action is for creating sla override comment')
    public static void addCommentForSLAOverrideFromMIF(List<InputWrapperForMIFFlow> input) {
        if (input != null && !input.isEmpty()) {
            addCommentForSLAOverride(input[0].caseId, input[0].slaComment, input[0].slaReason);
        }
    }

    /**
     * @description Add comment for SLA override
     * Refactored from: addCommentForSLAOverride() in QuoteProcurementController
     * @param caseId The Case ID
     * @param slaComment SLA override comment
     * @param slaReason SLA override reason
     */
    @AuraEnabled
    public static void addCommentForSLAOverride(String caseId, String slaComment, String slaReason) {
        try {
            String commentBody;
            String trackingNumber;
            String caseNumber;

            // Get comment template
            Map<String, Comment_Log_Detail__mdt> commentLogTemplateData =
                new Map<String, Comment_Log_Detail__mdt>();

            for (Comment_Log_Detail__mdt c : Comment_Log_Detail__mdt.getAll().values()) {
                commentLogTemplateData.put(c.DeveloperName, c);
            }

            Comment_Log_Detail__mdt slaOverrideCommentTemplate =
                commentLogTemplateData.get('SLA_Override');

            Id recordTypeId = Schema.getGlobalDescribe()
                .get('Comment__c')
                .getDescribe()
                .getRecordTypeInfosByDeveloperName()
                .get('Acorn_Ticket_Comment')
                .getRecordTypeId();

            // When called from MIF flow
            if (String.isNotEmpty(slaComment) && String.isNotEmpty(slaReason)) {
                commentBody = slaOverrideCommentTemplate.Comment__c.replaceAll('<Reason__x>', slaReason);
                commentBody = commentBody.replaceAll('<Comment__c>', slaComment);

                List<Case> csList = [
                    SELECT Id, CaseNumber, Tracking_Number__c
                    FROM Case
                    WHERE Id = :caseId
                    LIMIT 1
                ];

                if (!csList.isEmpty()) {
                    caseNumber = csList[0].CaseNumber;
                    trackingNumber = csList[0].Tracking_Number__c;
                }
            } else {
                // Query quoteline for comment details
                List<SBQQ__QuoteLine__c> qlList = [
                    SELECT Id, SLA_Override_Reason__c, SLA_Override_Comment__c,
                           SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__c,
                           SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.CaseNumber,
                           SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.Tracking_Number__c
                    FROM SBQQ__QuoteLine__c
                    WHERE SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__c = :caseId
                          AND SBQQ__Requiredby__c = null
                          AND SLA_Override_Reason__c != null
                    LIMIT 1
                ];

                if (!qlList.isEmpty()) {
                    String overrideReason = qlList[0].SLA_Override_Reason__c;
                    String overrideComment = qlList[0].SLA_Override_Comment__c;
                    commentBody = slaOverrideCommentTemplate.Comment__c.replaceAll(
                        '<Reason__x>',
                        overrideReason
                    );
                    commentBody = commentBody.replaceAll('<Comment__c>', overrideComment);

                    caseNumber = qlList[0].SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.CaseNumber;
                    if (String.isNotEmpty(qlList[0].SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.Tracking_Number__c)) {
                        trackingNumber = qlList[0].SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.Tracking_Number__c;
                    }
                }
            }

            // Create comment record
            if (String.isNotBlank(commentBody)) {
                Comment__c comment = new Comment__c();
                comment.RecordTypeId = recordTypeId;
                comment.Comment__c = commentBody;
                comment.is_Log__c = true;
                comment.Workflow_TeamUser__c = System.UserInfo.getName();
                comment.Communication_Log_Type_Name__c = 'Internal';
                comment.Case__c = caseId;
                comment.Type__c = Constant_Util.OBJECT_CASE;
                comment.Case_Number__c = caseNumber;
                comment.Acorn_Tracking_Number__c = trackingNumber;

                insert comment;
            }

        } catch (Exception ex) {
            UTIL_LoggingService.logHandledExceptionWithClass(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.CONFIRM_CONFIGURATION_ACTION,
                System.LoggingLevel.Error,
                UTIL_ErrorConstants.QUOTEPROCUREMNTCONTROLLER_CLASSNAME,
                'addCommentForSLAOverride',
                null
            );
        }
    }

    // ========================================================================
    // PUBLIC API - ASSET AVAILABILITY
    // ========================================================================

    /**
     * @description Get Asset Availability response for a QuoteLine
     * Refactored from: getAvailabilityResponse() in QuoteProcurementController
     * @param quoteLineId The QuoteLine ID
     * @return AAV_Asset_Availability__c Availability response
     */
    @AuraEnabled
    public static AAV_Asset_Availability__c getAvailabilityResponse(String quoteLineId) {
        return AAV_APIIntegration.getAvailabilityResponse(quoteLineId);
    }

    // ========================================================================
    // PUBLIC API - ALTERNATE PRODUCT
    // ========================================================================

    /**
     * @description Update alternate product for QuoteLine
     * Refactored from: updateAlternateProduct() in QuoteProcurementController
     * @param productWrapper Product wrapper with new equipment size
     * @return Boolean True if successful
     */
    @AuraEnabled
    public static Boolean updateAlternateProduct(Object productWrapper) {
        try {
            // Convert productWrapper to map to access parentId
            Map<String, Object> wrapperMap = (Map<String, Object>)JSON.deserializeUntyped(
                JSON.serialize(productWrapper)
            );

            Id parentId = (Id)wrapperMap.get('parentId');
            String equipmentSize = (String)wrapperMap.get('equipmentSize');

            if (parentId != null) {
                List<SBQQ__QuoteLine__c> qlList =
                    QuoteProcurementContextGetter.getQuoteLinesByParentId(parentId);

                for (SBQQ__QuoteLine__c ql : qlList) {
                    ql.Equipment_Size__c = equipmentSize;
                    ql.SLA_Override_Reason__c = '';
                    ql.SLA_Override_Comment__c = '';
                    ql.SBQQ__StartDate__c = null;
                    ql.AAV_Delivery_Override_Reason__c = '';
                    ql.AAV_Delivery_Override_Comment__c = '';
                }

                QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();
                QuoteProcurementDMLService.DMLResult result = dmlService.updateQuoteLines(qlList);

                return result.isSuccess;
            }
        } catch (Exception e) {
            System.debug('updateAlternateProduct Error->' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }

        return false;
    }

    // ========================================================================
    // INNER CLASSES
    // ========================================================================

    /**
     * @description Input wrapper for MIF Flow invocable method
     */
    public class InputWrapperForMIFFlow {
        @InvocableVariable(label='Case Id')
        public String caseId;

        @InvocableVariable(label='Sla Comment')
        public String slaComment;

        @InvocableVariable(label='Sla Reason')
        public String slaReason;
    }
}