objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Record Type (to replace the Supplier record type)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Position__c.object
<CustomObject>
    <description>Service Container Positions for Location</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Positions</relationshipLabel>
        <relationshipName>Account_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Container_Position__c</fullName>
        <description>Position at location where container is located</description>
        <label>Container Position</label>
        <type>TextArea</type>
    </fields>
    <label>Account Position</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Lookup to client Accounts</description>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Code</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/QuoteProcurementSearchServiceTest.cls
/**
 * @description Test class for QuoteProcurementSearchService
 * @author Waste Management
 * @date 2025
 */
@isTest
private class QuoteProcurementSearchServiceTest {

    @testSetup
    static void setupTestData() {
        Account clientAccount = TestDataFactoryRefactored.createAccount('Client', 'Client');
        insert clientAccount;

        Account locationAccount = TestDataFactoryRefactored.createAccount('Location', 'Location');
        locationAccount.ParentId = clientAccount.Id;
        insert locationAccount;

        Account vendorAccount = TestDataFactoryRefactored.createAccount('Vendor', 'Vendor');
        vendorAccount.Name = 'Test Vendor Search';
        vendorAccount.AccountNumber = 'VEN123';
        insert vendorAccount;

        Account_Position__c position = new Account_Position__c(
            AccountId__c = locationAccount.Id,
            Container_Position__c = 'Test Position'
        );
        insert position;

        Opportunity opp = TestDataFactoryRefactored.createOpportunity(clientAccount.Id);
        insert opp;

        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__Account__c = locationAccount.Id
        );
        insert quote;

        Project_Code__c project = new Project_Code__c(
            Name = 'Test Project',
            Client_Account__c = clientAccount.Id,
            Active__c = true
        );
        insert project;
    }

    @isTest
    static void testSearchVendors() {
        Test.setFixedSearchResults(new List<Id>{
            [SELECT Id FROM Account WHERE RecordType.Name = 'Vendor' LIMIT 1].Id
        });

        Test.startTest();
        List<Account> result = QuoteProcurementSearchService.searchVendors('Test Vendor');
        Test.stopTest();

        System.assert(result != null, 'Should return search results');
    }

    @isTest
    static void testGetAllPositions() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Test.startTest();
        List<Account_Position__c> result =
            QuoteProcurementSearchService.getAllPositions(locationAccount.Id);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Should return all positions');
    }

    @isTest
    static void testSearchPositions_WithSearchString() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Test.setFixedSearchResults(new List<Id>{
            [SELECT Id FROM Account_Position__c LIMIT 1].Id
        });

        Test.startTest();
        List<Account_Position__c> result =
            QuoteProcurementSearchService.searchPositions(locationAccount.Id, 'Test');
        Test.stopTest();

        System.assertNotEquals(null, result, 'Should return search results');
    }

    @isTest
    static void testSearchPositions_EmptySearch() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Test.startTest();
        List<Account_Position__c> result =
            QuoteProcurementSearchService.searchPositions(locationAccount.Id, '');
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Should return all positions for empty search');
    }

    @isTest
    static void testSearchActiveProjects() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Test.setFixedSearchResults(new List<Id>{
            [SELECT Id FROM Project_Code__c LIMIT 1].Id
        });

        Test.startTest();
        List<Project_Code__c> result =
            QuoteProcurementSearchService.searchActiveProjects(quote.Id, 'Test');
        Test.stopTest();

        System.assertNotEquals(null, result, 'Should return project search results');
    }
}