objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Manually_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to change the case sub-status &quot;Pending Manual Dispatch&quot; for Manual Dispatch process.</description>
        <label>Contact Manually Vendor</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Record Type (to replace the Supplier record type)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Availability_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Sub_Status__c</fullName>
        <description>Captures the sub-status for a Case State</description>
        <label>Case Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Inbound Interaction</fullName>
                </value>
                <value>
                    <fullName>Pending Customer Information</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Procurement</fullName>
                </value>
                <value>
                    <fullName>Pending Cost Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Request Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Price Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Quote Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Information</fullName>
                </value>
                <value>
                    <fullName>Pending Service Integration</fullName>
                </value>
                <value>
                    <fullName>Pending Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Manual Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pending Service Confirmation</fullName>
                </value>
                <value>
                    <fullName>Service Not Performed</fullName>
                </value>
                <value>
                    <fullName>Service Confirmed</fullName>
                </value>
                <value>
                    <fullName>Service Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Request Not Approved</fullName>
                </value>
                <value>
                    <fullName>Request Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Follow Up</fullName>
                </value>
                <value>
                    <fullName>Pending Service Issue Resolution</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Recovery</fullName>
                </value>
                <value>
                    <fullName>Pending Recovery Confirmation</fullName>
                </value>
                <value>
                    <fullName>Status Provided</fullName>
                </value>
                <value>
                    <fullName>Status Not Provided</fullName>
                </value>
                <value>
                    <fullName>Recovery Scheduled</fullName>
                </value>
                <value>
                    <fullName>Recovery Not Performed</fullName>
                </value>
                <value>
                    <fullName>Recovery Confirmed</fullName>
                </value>
                <value>
                    <fullName>Integration Error</fullName>
                </value>
                <value>
                    <fullName>Request Closed</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_Service_Date__c</fullName>
        <description>This field will be updated with the value of Proposed Service Date of Task</description>
        <label>Proposed Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>field to identify the source system/origination point of a Case</description>
        <label>Source System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acorn</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order_Instructions__c</fullName>
        <description>Work Order instructions for the case captured from the flow</description>
        <label>System Work Order Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Cases (Work Order)</relationshipLabel>
        <relationshipName>Case_WorkOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Acorn_WorkOrder_Number__c</fullName>
        <label>Acorn WorkOrder Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. - Customer Location</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders (Customer Location)</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rescheduled_Date__c</fullName>
        <label>Rescheduled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Status__c</fullName>
        <label>Send Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Failed (Send Manually)</fullName>
                </value>
                <value>
                    <fullName>Failed (System will Retry)</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>OnHold</fullName>
                </value>
                <value>
                    <fullName>Accepted by MAS</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Confirmation Wait</fullName>
                    <isActive>false</isActive>
                    <label>Confirmation Wait</label>
                </value>
                <value>
                    <fullName>Failed Send</fullName>
                    <isActive>false</isActive>
                    <label>Failed Send</label>
                </value>
                <value>
                    <fullName>Failed Workorder</fullName>
                    <isActive>false</isActive>
                    <label>Failed Workorder</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor_Account_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. - Vendor Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Service_Status__c</fullName>
        <label>Vendor Service Status</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkOrderTriggerHelperTest.cls
/*************************************************************
@Name: WorkOrderTriggerHelperTest
@Author: Claude AI
@CreateDate: 12/01/2025
@Description: Comprehensive test class for WorkOrderTriggerHelper
@Coverage: WorkOrderTriggerHelper
**************************************************************/
@isTest
private class WorkOrderTriggerHelperTest {

    @testSetup
    static void setupTestData() {
        // Create account hierarchy
        Account clientAccount = new Account(Name = 'Test Client');
        insert clientAccount;

        Account locationAccount = new Account(
            Name = 'Test Location',
            ParentId = clientAccount.Id,
            ShippingCountry = 'USA'
        );
        insert locationAccount;

        Account vendorAccount = new Account(
            Name = 'Test Vendor',
            Contact_Manually_Vendor__c = false
        );
        insert vendorAccount;

        // Create contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test@example.com',
            AccountId = locationAccount.Id
        );
        insert testContact;

        // Create asset
        Asset testAsset = new Asset(
            Name = 'Test Asset',
            AccountId = locationAccount.Id
        );
        insert testAsset;

        // Create case
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'Open',
            Case_Sub_Status__c = 'Pending Service Integration',
            AccountId = locationAccount.Id,
            ContactId = testContact.Id,
            AssetId = testAsset.Id,
            Service_Date__c = System.today().addDays(7),
            Work_Order_Instructions__c = 'Test instructions',
            Availability_Confirmed__c = true
        );
        insert testCase;

        // Create work order
        WorkOrder testWO = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'New',
            Subject = 'Test Work Order',
            Service_Date__c = System.today().addDays(7)
        );
        insert testWO;
    }

    @isTest
    static void testUpdateCaseDetailBasic() {
        WorkOrder wo = [SELECT Id, CaseId, Service_Date__c FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Work_Order__c, Proposed_Service_Date__c FROM Case WHERE Id = :wo.CaseId];

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        WorkOrderTriggerHelper.updateCaseDetail(woMap, null, caseMap);

        Test.stopTest();

        // Verify case was updated
        Case updatedCase = [SELECT Id, Work_Order__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals(wo.Id, updatedCase.Work_Order__c, 'Work Order should be linked to Case');
    }

    @isTest
    static void testUpdateCaseDetailServiceDateChange() {
        WorkOrder wo = [SELECT Id, CaseId, Service_Date__c FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Status, Proposed_Service_Date__c FROM Case WHERE Id = :wo.CaseId];

        Date newServiceDate = System.today().addDays(14);
        wo.Service_Date__c = newServiceDate;
        WorkOrder oldWO = wo.clone(true);
        oldWO.Service_Date__c = System.today().addDays(7);

        update wo;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, WorkOrder> oldWoMap = new Map<Id, WorkOrder>{oldWO.Id => oldWO};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        RecurrsiveTriggerHandler.bypassValidation = false;
        WorkOrderTriggerHelper.updateCaseDetail(woMap, oldWoMap, caseMap);

        Test.stopTest();

        // Verify proposed service date was updated
        Case updatedCase = [SELECT Id, Proposed_Service_Date__c FROM Case WHERE Id = :testCase.Id];
        System.assertNotEquals(null, updatedCase.Proposed_Service_Date__c);
    }

    @isTest
    static void testUpdateCaseDetailConfirmedNegative() {
        WorkOrder wo = [SELECT Id, CaseId, Vendor_Service_Status__c FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Status, Case_Sub_Status__c FROM Case WHERE Id = :wo.CaseId];

        wo.Vendor_Service_Status__c = 'Confirmed - Negative';
        update wo;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        WorkOrderTriggerHelper.updateCaseDetail(woMap, null, caseMap);

        Test.stopTest();

        // Verify case was closed
        Case updatedCase = [SELECT Id, Status, Case_Sub_Status__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Closed', updatedCase.Status, 'Case should be closed');
        System.assertEquals('Service Not Performed', updatedCase.Case_Sub_Status__c);
    }

    @isTest
    static void testUpdateCaseDetailConfirmedPositive() {
        WorkOrder wo = [SELECT Id, CaseId, Vendor_Service_Status__c FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Status, Case_Sub_Status__c FROM Case WHERE Id = :wo.CaseId];

        WorkOrder oldWO = wo.clone(true);
        oldWO.Vendor_Service_Status__c = null;

        wo.Vendor_Service_Status__c = 'Confirmed - Positive';
        wo.Status = 'Work Complete';
        update wo;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, WorkOrder> oldWoMap = new Map<Id, WorkOrder>{oldWO.Id => oldWO};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        WorkOrderTriggerHelper.updateCaseDetail(woMap, oldWoMap, caseMap);

        Test.stopTest();

        // Verify case was marked as service confirmed
        Case updatedCase = [SELECT Id, Status, Case_Sub_Status__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Closed', updatedCase.Status, 'Case should be closed');
        System.assertEquals('Service Confirmed', updatedCase.Case_Sub_Status__c);
    }

    @isTest
    static void testUpdateCaseDetailPendingDispatch() {
        WorkOrder wo = [SELECT Id, CaseId, Status FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Status, Case_Sub_Status__c, Source_System__c FROM Case WHERE Id = :wo.CaseId];
        testCase.Source_System__c = 'Acorn';
        update testCase;

        wo.Status = 'Issued';
        update wo;

        Account vendor = [SELECT Id, Contact_Manually_Vendor__c FROM Account WHERE Name = 'Test Vendor' LIMIT 1];
        wo.Vendor_Account_Id__c = vendor.Id;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        WorkOrderTriggerHelper.updateCaseDetail(woMap, null, caseMap);

        Test.stopTest();

        // Verify case sub status was updated
        Case updatedCase = [SELECT Id, Case_Sub_Status__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Pending Dispatch', updatedCase.Case_Sub_Status__c);
    }

    @isTest
    static void testServiceDateChanges() {
        List<WorkOrder> woList = [SELECT Id, CaseId, Service_Date__c FROM WorkOrder];

        Map<Id, WorkOrder> oldWoMap = new Map<Id, WorkOrder>();
        for (WorkOrder wo : woList) {
            WorkOrder oldWO = wo.clone(true);
            oldWO.Service_Date__c = System.today().addDays(5);
            oldWoMap.put(oldWO.Id, oldWO);
            wo.Service_Date__c = System.today().addDays(10);
        }

        Test.startTest();

        WorkOrderTriggerHelper.ServiceDateChanges(woList, oldWoMap);

        Test.stopTest();

        // Verify method executed without errors
        System.assertNotEquals(null, woList, 'Work order list should not be null');
    }

    @isTest
    static void testCreateCaseComment() {
        WorkOrder wo = [SELECT Id, CaseId, Acorn_WorkOrder_Number__c FROM WorkOrder LIMIT 1];
        wo.Acorn_WorkOrder_Number__c = 'ACORN-123';
        update wo;

        Map<String, List<WorkOrder>> commentWOMap = new Map<String, List<WorkOrder>>();
        commentWOMap.put('Work Order Creation', new List<WorkOrder>{wo});

        Test.startTest();

        WorkOrderTriggerHelper.createCaseComment(commentWOMap);

        Test.stopTest();

        // Verify method executed without errors
        System.assertNotEquals(null, commentWOMap, 'Comment map should not be null');
    }

    @isTest
    static void testBulkOperations() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location' LIMIT 1];

        // Create bulk work orders
        List<WorkOrder> bulkWOs = new List<WorkOrder>();
        for (Integer i = 0; i < 100; i++) {
            bulkWOs.add(new WorkOrder(
                CaseId = testCase.Id,
                Customer_Location__c = locationAccount.Id,
                Status = 'New',
                Subject = 'Bulk WO ' + i,
                Service_Date__c = System.today().addDays(7)
            ));
        }
        insert bulkWOs;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>(bulkWOs);
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        WorkOrderTriggerHelper.updateCaseDetail(woMap, null, caseMap);

        Test.stopTest();

        // Verify bulk operations completed
        System.assertEquals(100, bulkWOs.size(), 'Should process 100 work orders');
    }

    @isTest
    static void testUpdateCaseDetailWithRescheduledDate() {
        WorkOrder wo = [SELECT Id, CaseId, Rescheduled_Date__c FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Status FROM Case WHERE Id = :wo.CaseId];

        DateTime rescheduledDate = System.now().addDays(10);
        wo.Rescheduled_Date__c = rescheduledDate;

        WorkOrder oldWO = wo.clone(true);
        oldWO.Rescheduled_Date__c = null;

        update wo;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, WorkOrder> oldWoMap = new Map<Id, WorkOrder>{oldWO.Id => oldWO};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        RecurrsiveTriggerHandler.bypassValidation = false;
        WorkOrderTriggerHelper.updateCaseDetail(woMap, oldWoMap, caseMap);

        Test.stopTest();

        // Verify proposed service date was updated from rescheduled date
        Case updatedCase = [SELECT Id, Proposed_Service_Date__c FROM Case WHERE Id = :testCase.Id];
        System.assertNotEquals(null, updatedCase.Proposed_Service_Date__c);
    }

    @isTest
    static void testUpdateCaseDetailPendingServiceConfirmation() {
        WorkOrder wo = [SELECT Id, CaseId, Send_Status__c, Status FROM WorkOrder LIMIT 1];
        Case testCase = [SELECT Id, Status, Case_Sub_Status__c, Availability_Confirmed__c FROM Case WHERE Id = :wo.CaseId];

        wo.Send_Status__c = 'Sent';
        wo.Status = 'Sent';
        update wo;

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>{wo.Id => wo};
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();

        WorkOrderTriggerHelper.updateCaseDetail(woMap, null, caseMap);

        Test.stopTest();

        // Verify case sub status
        Case updatedCase = [SELECT Id, Case_Sub_Status__c FROM Case WHERE Id = :testCase.Id];
        System.assertNotEquals(null, updatedCase.Case_Sub_Status__c);
    }
}