objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_ByPassWO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To by pass the workorder</description>
        <label>Is ByPassWO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact_Phone__c</fullName>
        <label>Onsite Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Site_Contact__c</fullName>
        <description>Site contact captured on the case</description>
        <label>Onsite Contact Name</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Input_Work_Order_Instructions__c</fullName>
        <description>User inputs WO instructions.  These instructions are then placed into work order instructions field via trigger on update.</description>
        <label>Work Order Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <customValue>
        <fullName>Location</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/WorkOrderPreviewControllerTest.cls
/**
 * @description Test class for WorkOrderPreviewController
 * 
 * Tests work order preview data retrieval, updates, and validation
 * for the unified case management system.
 * 
 * @author Claude (AI Assistant)
 * @date 2025-11-18
 * @group Test Classes
 */
@isTest
private class WorkOrderPreviewControllerTest {
    
    /**
     * Test data setup
     */
    @testSetup
    static void setupTestData() {
        // Create test account (location)
        Account testLocation = new Account(
            Name = 'Test Location',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId()
        );
        insert testLocation;
        
        // Create test contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testLocation.Id,
            Email = 'test@example.com'
        );
        insert testContact;
        
        // Create test case
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'New',
            Origin = 'Web',
            Location__c = testLocation.Id,
            ContactId = testContact.Id,
            Case_Type__c = 'Service',
            Case_Sub_Type__c = 'Delivery',
            Site_Contact__c = 'John Doe',
            Site_Contact_Phone__c = '555-1234',
            User_Input_Work_Order_Instructions__c = 'Test instructions'
        );
        insert testCase;
    }
    
    /**
     * Test getWorkOrderPreviewData method
     */
    @isTest
    static void testGetWorkOrderPreviewData() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        WorkOrderPreviewController.WorkOrderPreviewData result = 
            WorkOrderPreviewController.getWorkOrderPreviewData(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals('John Doe', result.siteContact, 'Site contact should match');
        System.assertEquals('555-1234', result.siteContactPhone, 'Site phone should match');
        System.assertEquals('Test instructions', result.workOrderInstructions, 'Instructions should match');
    }
    
    /**
     * Test getWorkOrderPreviewInfo method
     */
    @isTest
    static void testGetWorkOrderPreviewInfo() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        WorkOrderPreviewController.WorkOrderPreviewInfo result = 
            WorkOrderPreviewController.getWorkOrderPreviewInfo(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertNotEquals(null, result.previewText, 'Preview text should not be null');
        System.assertEquals('John Doe', result.siteContact, 'Site contact should match');
    }
    
    /**
     * Test updateWorkOrderPreviewFields method
     */
    @isTest
    static void testUpdateWorkOrderPreviewFields() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        WorkOrderPreviewController.WorkOrderUpdateData updateData = 
            new WorkOrderPreviewController.WorkOrderUpdateData();
        updateData.siteContact = 'Jane Smith';
        updateData.siteContactPhone = '555-9999';
        updateData.workOrderInstructions = 'Updated instructions';
        updateData.byPassWorkOrder = true;
        
        String updateDataJson = JSON.serialize(updateData);
        
        Test.startTest();
        WorkOrderPreviewController.updateWorkOrderPreviewFields(testCase.Id, updateDataJson);
        Test.stopTest();
        
        Case updatedCase = [SELECT Site_Contact__c, Site_Contact_Phone__c, 
                                  User_Input_Work_Order_Instructions__c, Is_ByPassWO__c
                           FROM Case WHERE Id = :testCase.Id];
        
        System.assertEquals('Jane Smith', updatedCase.Site_Contact__c, 'Site contact should be updated');
        System.assertEquals('555-9999', updatedCase.Site_Contact_Phone__c, 'Site phone should be updated');
        System.assertEquals('Updated instructions', updatedCase.User_Input_Work_Order_Instructions__c, 
                          'Instructions should be updated');
        System.assertEquals(true, updatedCase.Is_ByPassWO__c, 'Bypass flag should be updated');
    }
    
    /**
     * Test validateWorkOrderCreation method
     */
    @isTest
    static void testValidateWorkOrderCreation() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        WorkOrderPreviewController.ValidationResultWrapper result = 
            WorkOrderPreviewController.validateWorkOrderCreation(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertNotEquals(null, result.messages, 'Messages should be initialized');
    }
    
    /**
     * Test null/blank input handling
     */
    @isTest
    static void testNullInputHandling() {
        Test.startTest();
        
        // Test null case ID
        WorkOrderPreviewController.WorkOrderPreviewData result1 = 
            WorkOrderPreviewController.getWorkOrderPreviewData(null);
        System.assertNotEquals(null, result1, 'Should handle null input gracefully');
        
        // Test blank case ID for validation
        WorkOrderPreviewController.ValidationResultWrapper result2 = 
            WorkOrderPreviewController.validateWorkOrderCreation('');
        System.assertEquals(false, result2.isValid, 'Should be invalid for blank input');
        System.assert(result2.messages.size() > 0, 'Should have validation message');
        
        Test.stopTest();
    }
    
    /**
     * Test error handling
     */
    @isTest
    static void testErrorHandling() {
        Test.startTest();
        
        try {
            // Try to update with null data
            WorkOrderPreviewController.updateWorkOrderPreviewFields(null, null);
            System.assert(false, 'Should have thrown exception');
        } catch (Exception e) {
            System.assert(e.getMessage().contains('required'), 'Error message should mention required');
        }
        
        Test.stopTest();
    }
}