objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>This field contains the parent case number</description>
        <label>Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <customValue>
        <fullName>Location</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ActionMessagesPanelControllerTest.cls
/**
 * @description Test class for ActionMessagesPanelController
 * 
 * Tests action panel data retrieval, button visibility, and message generation
 * for the unified case management system.
 * 
 * @author George Martin
 * @date 2025-11-18
 * @group Test Classes
 */
@isTest
private class ActionMessagesPanelControllerTest {
    
    /**
     * Test data setup
     */
    @testSetup
    static void setupTestData() {
        // Create test account (location)
        Account testLocation = new Account(
            Name = 'Test Location',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId()
        );
        insert testLocation;
        
        // Create test contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testLocation.Id,
            Email = 'test@example.com'
        );
        insert testContact;
        
        // Create test product and asset
        Product2 testProduct = new Product2(Name = 'Test Product');
        insert testProduct;
        
        Asset testAsset = new Asset(
            Name = 'Test Asset',
            AccountId = testLocation.Id,
            Product2Id = testProduct.Id,
            Status = 'Active'
        );
        insert testAsset;
        
        // Create test case
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'New',
            Origin = 'Web',
            Location__c = testLocation.Id,
            ContactId = testContact.Id,
            AssetId = testAsset.Id,
            Case_Type__c = 'Service',
            Case_Sub_Type__c = 'Delivery',
            Reference_Number__c = 'REF123',
            Is_MultiCalendar_Checked__c = true
        );
        insert testCase;
    }
    
    /**
     * Test getActionPanelData method
     */
    @isTest
    static void testGetActionPanelData() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        ActionMessagesPanelController.ActionPanelData result = 
            ActionMessagesPanelController.getActionPanelData(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(testCase.Id, result.caseId, 'Case ID should match');
        System.assertEquals('New', result.status, 'Status should match');
        System.assertEquals('Service', result.caseType, 'Case type should match');
        System.assertNotEquals(null, result.actionMessage, 'Action message should not be null');
        System.assertNotEquals(null, result.messageVariant, 'Message variant should not be null');
        System.assertNotEquals(null, result.messageIcon, 'Message icon should not be null');
    }
    
    /**
     * Test getButtonVisibility method
     */
    @isTest
    static void testGetButtonVisibility() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        ActionMessagesPanelController.ButtonVisibilityData result = 
            ActionMessagesPanelController.getButtonVisibility(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        // All button visibility flags should be initialized (true or false)
        System.assertNotEquals(null, result.showProgressCase, 'Progress Case visibility should be set');
        System.assertNotEquals(null, result.showAddQuote, 'Add Quote visibility should be set');
        System.assertNotEquals(null, result.showInitiateWorkOrder, 'Initiate WO visibility should be set');
        System.assertNotEquals(null, result.showViewCaseSummary, 'View Summary visibility should be set');
        System.assertNotEquals(null, result.showAddCaseAssets, 'Add Assets visibility should be set');
        System.assertNotEquals(null, result.showPendingInfoTask, 'Pending Task visibility should be set');
        System.assertNotEquals(null, result.showMultiDates, 'Multi Dates visibility should be set');
    }
    
    /**
     * Test message variant logic
     */
    @isTest
    static void testMessageVariants() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        
        // Test New status (should be info variant)
        ActionMessagesPanelController.ActionPanelData result1 = 
            ActionMessagesPanelController.getActionPanelData(testCase.Id);
        
        // Update to Open status
        testCase.Status = 'Open';
        update testCase;
        
        ActionMessagesPanelController.ActionPanelData result2 = 
            ActionMessagesPanelController.getActionPanelData(testCase.Id);
        
        // Update to Closed status
        testCase.Status = 'Closed';
        update testCase;
        
        ActionMessagesPanelController.ActionPanelData result3 = 
            ActionMessagesPanelController.getActionPanelData(testCase.Id);
        
        Test.stopTest();
        
        System.assertNotEquals(null, result1.messageVariant, 'New case should have message variant');
        System.assertNotEquals(null, result2.messageVariant, 'Open case should have message variant');
        System.assertNotEquals(null, result3.messageVariant, 'Closed case should have message variant');
    }
    
    /**
     * Test button visibility with different case states
     */
    @isTest
    static void testButtonVisibilityWithDifferentStates() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        
        // Test with New case
        ActionMessagesPanelController.ButtonVisibilityData result1 = 
            ActionMessagesPanelController.getButtonVisibility(testCase.Id);
        
        // Test with Open case
        testCase.Status = 'Open';
        update testCase;
        ActionMessagesPanelController.ButtonVisibilityData result2 = 
            ActionMessagesPanelController.getButtonVisibility(testCase.Id);
        
        // Test with Closed case
        testCase.Status = 'Closed';
        update testCase;
        ActionMessagesPanelController.ButtonVisibilityData result3 = 
            ActionMessagesPanelController.getButtonVisibility(testCase.Id);
        
        Test.stopTest();
        
        // Closed cases should have different button visibility
        System.assertEquals(false, result3.showInitiateWorkOrder, 
                          'Closed case should not show Initiate WO button');
        System.assertEquals(false, result3.showAddCaseAssets, 
                          'Closed case should not show Add Assets button');
    }
    
    /**
     * Test related case count
     */
    @isTest
    static void testRelatedCaseCount() {
        Case testCase = [SELECT Id, Reference_Number__c FROM Case LIMIT 1];
        
        // Create related case with same reference number
        Case relatedCase = new Case(
            Subject = 'Related Case',
            Status = 'New',
            Origin = 'Web',
            Reference_Number__c = testCase.Reference_Number__c
        );
        insert relatedCase;
        
        Test.startTest();
        ActionMessagesPanelController.ActionPanelData result = 
            ActionMessagesPanelController.getActionPanelData(testCase.Id);
        Test.stopTest();
        
        System.assertEquals(1, result.relatedCaseCount, 'Should have 1 related case');
    }
    
    /**
     * Test null/blank input handling
     */
    @isTest
    static void testNullInputHandling() {
        Test.startTest();
        
        // Test null case ID
        ActionMessagesPanelController.ActionPanelData result1 = 
            ActionMessagesPanelController.getActionPanelData(null);
        System.assertNotEquals(null, result1, 'Should handle null input gracefully');
        
        ActionMessagesPanelController.ButtonVisibilityData result2 = 
            ActionMessagesPanelController.getButtonVisibility('');
        System.assertNotEquals(null, result2, 'Should handle blank input gracefully');
        
        Test.stopTest();
    }
}