objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Category__c</fullName>
        <label>Company Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Asset_Material__c</fullName>
        <formula>TEXT(Asset.Material_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Material</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <description>Case Reason on the Case</description>
        <label>Case Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Sub_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Sub_Status__c</fullName>
        <description>Captures the sub-status for a Case State</description>
        <label>Case Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Inbound Interaction</fullName>
                </value>
                <value>
                    <fullName>Pending Customer Information</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Procurement</fullName>
                </value>
                <value>
                    <fullName>Pending Cost Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Request Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Price Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Quote Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Information</fullName>
                </value>
                <value>
                    <fullName>Pending Service Integration</fullName>
                </value>
                <value>
                    <fullName>Pending Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Manual Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pending Service Confirmation</fullName>
                </value>
                <value>
                    <fullName>Service Not Performed</fullName>
                </value>
                <value>
                    <fullName>Service Confirmed</fullName>
                </value>
                <value>
                    <fullName>Service Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Request Not Approved</fullName>
                </value>
                <value>
                    <fullName>Request Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Follow Up</fullName>
                </value>
                <value>
                    <fullName>Pending Service Issue Resolution</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Recovery</fullName>
                </value>
                <value>
                    <fullName>Pending Recovery Confirmation</fullName>
                </value>
                <value>
                    <fullName>Status Provided</fullName>
                </value>
                <value>
                    <fullName>Status Not Provided</fullName>
                </value>
                <value>
                    <fullName>Recovery Scheduled</fullName>
                </value>
                <value>
                    <fullName>Recovery Not Performed</fullName>
                </value>
                <value>
                    <fullName>Recovery Confirmed</fullName>
                </value>
                <value>
                    <fullName>Integration Error</fullName>
                </value>
                <value>
                    <fullName>Request Closed</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Client for this Case</description>
        <label>Client Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Client Name)</relationshipLabel>
        <relationshipName>Cases_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Category__c</fullName>
        <label>Company Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSI__c</fullName>
        <description>PSI of the service</description>
        <label>PSI</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_Number__c</fullName>
        <label>Profile Number #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder_Number__c</fullName>
        <description>PO Number for the case captured through the flow</description>
        <label>Customer PO #</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>This field contains the parent case number</description>
        <label>Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Service_Date_Time__c</fullName>
        <label>SLA Service Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Acorn Issue Tracking Number, AKA T-Number</description>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>All Other Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary/Regulatory</fullName>
    </customValue>
    <customValue>
        <fullName>Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Baler Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Mailback Box</fullName>
    </customValue>
    <customValue>
        <fullName>Onsite Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Discrepancies</fullName>
    </customValue>
    <customValue>
        <fullName>Bill Not Received</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Service</fullName>
    </customValue>
    <customValue>
        <fullName>Clean Up External</fullName>
    </customValue>
    <customValue>
        <fullName>Clean Up Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Closed/Closing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Communication Channel Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor/Baler/Vertical CMP</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Construction and Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Contaminated</fullName>
    </customValue>
    <customValue>
        <fullName>Cost/Price</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Days of Service</fullName>
    </customValue>
    <customValue>
        <fullName>Dig-Out</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster/Toter/Port-o-let</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Recycling Collection</fullName>
    </customValue>
    <masterLabel>Case Reason</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CaseHighlightStripController.cls
/**
 * @description CaseHighlightStripController - Apex controller for caseHighlightStrip LWC
 *
 * Provides comprehensive case highlight data for inline display in horizontal strip layout.
 * Replaces CustomCaseHighlightPanelCntrl with modern LWC-optimized approach.
 *
 * Key Responsibilities:
 * - Provide case field data for highlight strip display
 * - Determine field status/color coding (complete, warning, missing)
 * - Support click-to-edit functionality
 * - Real-time field validation status
 *
 * Design Principles:
 * - Single Responsibility: Only handles highlight strip UI data
 * - Service Layer Integration: 100% reuse of existing services
 * - Cacheable: Uses @AuraEnabled(cacheable=true) for wire services
 *
 * @author George Martin
 * @date 2025-11-18
 * @group Controllers
 */
public with sharing class CaseHighlightStripController {

    // ========================================================================
    // DATA RETRIEVAL METHODS
    // ========================================================================

    /**
     * @description Gets comprehensive case highlight data for strip display
     * @param caseId The case ID
     * @return CaseHighlightData wrapper with all highlight strip fields
     */
    @AuraEnabled(cacheable=true)
    public static CaseHighlightData getCaseHighlightData(String caseId) {
        CaseHighlightData result = new CaseHighlightData();

        try {
            if (String.isBlank(caseId)) {
                return result;
            }

            // Query case with all highlight panel fields
            Case caseRecord = CaseContextGetter.getCaseWithHighlightPanelFields(Id.valueOf(caseId));

            if (caseRecord == null) {
                return result;
            }

            // Populate basic case info
            result.caseId = caseRecord.Id;
            result.caseNumber = caseRecord.CaseNumber;
            result.referenceNumber = caseRecord.Reference_Number__c;
            result.status = caseRecord.Status;
            result.subStatus = caseRecord.Case_Sub_Status__c;

            // Entity information
            result.locationId = caseRecord.Location__c;
            result.locationName = caseRecord.Location__r != null ? caseRecord.Location__r.Name : '--';
            result.vendorId = caseRecord.Vendor__c;
            result.vendorName = caseRecord.Vendor__r != null ? caseRecord.Vendor__r.Name : '--';
            result.clientId = caseRecord.Client__c;
            result.clientName = caseRecord.Client__r != null ? caseRecord.Client__r.Name : '--';

            // Contact information
            result.contactId = caseRecord.ContactId;
            result.contactName = caseRecord.Contact != null ? caseRecord.Contact.Name : '--';

            // Asset information
            result.assetId = caseRecord.AssetId;
            result.assetName = caseRecord.Asset != null ? caseRecord.Asset.Name : '--';
            result.material = caseRecord.Asset_Material__c;

            // Case Type information
            result.recordTypeId = caseRecord.RecordTypeId;
            result.recordTypeName = caseRecord.Case_Record_Type__c;
            result.caseType = caseRecord.Case_Type__c;
            result.caseSubType = caseRecord.Case_Sub_Type__c;
            result.caseReason = caseRecord.Case_Reason__c;

            // Customer info
            result.purchaseOrderNumber = caseRecord.PurchaseOrder_Number__c;
            result.profileNumber = caseRecord.Profile_Number__c;
            result.psi = caseRecord.PSI__c;
            result.companyCategory = caseRecord.Company_Category__c;

            // Service date information
            result.serviceDate = caseRecord.Service_Date__c;
            result.slaServiceDateTime = caseRecord.SLA_Service_Date_Time__c;

            // Work order and queue information
            result.workOrderNumber = caseRecord.WorkOrder__r != null ? caseRecord.WorkOrder__r.WorkOrderNumber : '--';
            result.trackingNumber = caseRecord.Tracking_Number__c;
            result.queueName = getQueueName(caseRecord.Tracking_Number__c);

            // Determine field statuses (for color coding)
            determineFieldStatuses(result, caseRecord);

        } catch (Exception ex) {
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.CASE_TRIGGER_CLASS,
                LoggingLevel.ERROR
            );
            throw new AuraHandledException('Failed to load case highlight data: ' + ex.getMessage());
        }

        return result;
    }

    /**
     * @description Gets summary info for highlight strip (lighter weight than full data)
     * @param caseId The case ID
     * @return CaseHighlightSummary with essential fields only
     */
    @AuraEnabled(cacheable=true)
    public static CaseHighlightSummary getCaseHighlightSummary(String caseId) {
        CaseHighlightSummary result = new CaseHighlightSummary();

        try {
            if (String.isBlank(caseId)) {
                return result;
            }

            Case caseRecord = CaseContextGetter.getCaseById(Id.valueOf(caseId));

            if (caseRecord == null) {
                return result;
            }

            result.caseNumber = caseRecord.CaseNumber;
            result.status = caseRecord.Status;
            result.caseType = caseRecord.Case_Type__c;
            result.referenceNumber = caseRecord.Reference_Number__c;
            result.hasRequiredInfo = String.isNotBlank(caseRecord.PurchaseOrder_Number__c) ||
                                     String.isNotBlank(caseRecord.Profile_Number__c);

        } catch (Exception ex) {
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.CASE_TRIGGER_CLASS,
                LoggingLevel.ERROR
            );
        }

        return result;
    }

    // ========================================================================
    // FIELD STATUS DETERMINATION METHODS
    // ========================================================================

    /**
     * @description Determines status for each field (complete, warning, missing)
     * @param result The CaseHighlightData to populate statuses for
     * @param caseRecord The Case record
     */
    private static void determineFieldStatuses(CaseHighlightData result, Case caseRecord) {
        // Location status
        result.locationStatus = String.isNotBlank(result.locationName) && result.locationName != '--' ?
            'complete' : 'missing';

        // Contact status
        result.contactStatus = String.isNotBlank(result.contactName) && result.contactName != '--' ?
            'complete' : 'missing';

        // Asset status
        result.assetStatus = String.isNotBlank(result.assetName) && result.assetName != '--' ?
            'complete' : 'warning';

        // Case Type status
        result.caseTypeStatus = String.isNotBlank(result.caseType) ? 'complete' : 'missing';

        // Service Date status
        result.serviceDateStatus = result.serviceDate != null ? 'complete' : 'warning';

        // PO/Profile/PSI status (check business rules)
        Boolean poRequired = CaseBusinessRuleService.isPurchaseOrderRequired(caseRecord);
        Boolean profileRequired = CaseBusinessRuleService.isProfileNumberRequired(caseRecord);
        Boolean psiRequired = CaseBusinessRuleService.isPSIRequired(caseRecord);

        if (poRequired && String.isBlank(result.purchaseOrderNumber)) {
            result.customerInfoStatus = 'missing';
        } else if (profileRequired && String.isBlank(result.profileNumber)) {
            result.customerInfoStatus = 'missing';
        } else if (psiRequired && result.psi == null) {
            result.customerInfoStatus = 'missing';
        } else if (String.isNotBlank(result.purchaseOrderNumber) ||
                   String.isNotBlank(result.profileNumber) ||
                   result.psi != null) {
            result.customerInfoStatus = 'complete';
        } else {
            result.customerInfoStatus = 'info';
        }

        // Overall case readiness
        result.caseReadiness = determineCaseReadiness(result);
    }

    /**
     * @description Determines overall case readiness based on field statuses
     * @param result The CaseHighlightData
     * @return Readiness status: 'ready', 'warning', or 'missing'
     */
    private static String determineCaseReadiness(CaseHighlightData result) {
        if (result.locationStatus == 'missing' ||
            result.contactStatus == 'missing' ||
            result.caseTypeStatus == 'missing' ||
            result.customerInfoStatus == 'missing') {
            return 'missing';
        }

        if (result.assetStatus == 'warning' ||
            result.serviceDateStatus == 'warning') {
            return 'warning';
        }

        return 'ready';
    }

    /**
     * @description Gets queue name from tracking number
     * @param trackingNumber Tracking number
     * @return Queue name string
     */
    private static String getQueueName(String trackingNumber) {
        if (String.isBlank(trackingNumber)) {
            return '--';
        }

        // Reuse existing logic from CustomCaseHighlightPanelCntrl
        try {
            return CustomCaseHighlightPanelCntrl.getQueueName(trackingNumber);
        } catch (Exception ex) {
            return '--';
        }
    }

    // ========================================================================
    // WRAPPER CLASSES
    // ========================================================================

    /**
     * @description Comprehensive case highlight data wrapper
     */
    public class CaseHighlightData {
        // Case identification
        @AuraEnabled public Id caseId { get; set; }
        @AuraEnabled public String caseNumber { get; set; }
        @AuraEnabled public String referenceNumber { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String subStatus { get; set; }

        // Entity information
        @AuraEnabled public Id locationId { get; set; }
        @AuraEnabled public String locationName { get; set; }
        @AuraEnabled public Id vendorId { get; set; }
        @AuraEnabled public String vendorName { get; set; }
        @AuraEnabled public Id clientId { get; set; }
        @AuraEnabled public String clientName { get; set; }

        // Contact information
        @AuraEnabled public Id contactId { get; set; }
        @AuraEnabled public String contactName { get; set; }

        // Asset information
        @AuraEnabled public Id assetId { get; set; }
        @AuraEnabled public String assetName { get; set; }
        @AuraEnabled public String material { get; set; }

        // Case type information
        @AuraEnabled public Id recordTypeId { get; set; }
        @AuraEnabled public String recordTypeName { get; set; }
        @AuraEnabled public String caseType { get; set; }
        @AuraEnabled public String caseSubType { get; set; }
        @AuraEnabled public String caseReason { get; set; }

        // Customer information
        @AuraEnabled public String purchaseOrderNumber { get; set; }
        @AuraEnabled public String profileNumber { get; set; }
        @AuraEnabled public Decimal psi { get; set; }
        @AuraEnabled public String companyCategory { get; set; }

        // Service date information
        @AuraEnabled public Date serviceDate { get; set; }
        @AuraEnabled public DateTime slaServiceDateTime { get; set; }

        // Work order and queue
        @AuraEnabled public String workOrderNumber { get; set; }
        @AuraEnabled public String trackingNumber { get; set; }
        @AuraEnabled public String queueName { get; set; }

        // Field statuses (for color coding)
        @AuraEnabled public String locationStatus { get; set; }
        @AuraEnabled public String contactStatus { get; set; }
        @AuraEnabled public String assetStatus { get; set; }
        @AuraEnabled public String caseTypeStatus { get; set; }
        @AuraEnabled public String serviceDateStatus { get; set; }
        @AuraEnabled public String customerInfoStatus { get; set; }
        @AuraEnabled public String caseReadiness { get; set; }

        public CaseHighlightData() {
            this.caseNumber = '--';
            this.referenceNumber = '--';
            this.status = '--';
            this.subStatus = '--';
            this.locationName = '--';
            this.vendorName = '--';
            this.clientName = '--';
            this.contactName = '--';
            this.assetName = '--';
            this.material = '--';
            this.recordTypeName = '--';
            this.caseType = '--';
            this.caseSubType = '--';
            this.caseReason = '--';
            this.purchaseOrderNumber = '--';
            this.profileNumber = '--';
            this.companyCategory = '--';
            this.workOrderNumber = '--';
            this.trackingNumber = '--';
            this.queueName = '--';
            this.locationStatus = 'info';
            this.contactStatus = 'info';
            this.assetStatus = 'info';
            this.caseTypeStatus = 'info';
            this.serviceDateStatus = 'info';
            this.customerInfoStatus = 'info';
            this.caseReadiness = 'info';
        }
    }

    /**
     * @description Lightweight case highlight summary wrapper
     */
    public class CaseHighlightSummary {
        @AuraEnabled public String caseNumber { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String caseType { get; set; }
        @AuraEnabled public String referenceNumber { get; set; }
        @AuraEnabled public Boolean hasRequiredInfo { get; set; }

        public CaseHighlightSummary() {
            this.caseNumber = '--';
            this.status = '--';
            this.caseType = '--';
            this.referenceNumber = '--';
            this.hasRequiredInfo = false;
        }
    }
}