objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Gives the Status of the Account</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Do Not Use</fullName>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pass-Thru</fullName>
                </value>
                <value>
                    <fullName>Oak-Fee</fullName>
                </value>
                <value>
                    <fullName>Out To Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Record Type (to replace the Supplier record type)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Position__c.object
<CustomObject>
    <description>Service Container Positions for Location</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Positions</relationshipLabel>
        <relationshipName>Account_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Container_Position__c</fullName>
        <description>Position at location where container is located</description>
        <label>Container Position</label>
        <type>TextArea</type>
    </fields>
    <label>Account Position</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Order__c.object
<CustomObject>
    <fields>
        <fullName>Quote_Line__c</fullName>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Orders</relationshipLabel>
        <relationshipName>Quote_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
                <value>
                    <fullName>Removal</fullName>
                </value>
                <value>
                    <fullName>Rental Charge</fullName>
                </value>
                <value>
                    <fullName>Lock Delivery</fullName>
                </value>
                <value>
                    <fullName>Power Wash</fullName>
                </value>
                <value>
                    <fullName>Onsite Relocation</fullName>
                </value>
                <value>
                    <fullName>Container Exchange</fullName>
                </value>
                <value>
                    <fullName>Contaminated Pickup</fullName>
                </value>
                <value>
                    <fullName>Dig Out Service</fullName>
                </value>
                <value>
                    <fullName>Dry Run</fullName>
                </value>
                <value>
                    <fullName>Product Order</fullName>
                </value>
                <value>
                    <fullName>Site Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Order</label>
    <nameField>
        <displayFormat>QO-{0000}</displayFormat>
        <label>Quote Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Product Configured</fullName>
                <label>Procure Service</label>
            </value>
            <value>
                <fullName>Cost Configured</fullName>
                <label>Configure Price</label>
            </value>
            <value>
                <fullName>Price Configured</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/sCode__c.field-meta.xml
<CustomField>
    <fullName>sCode__c</fullName>
    <label>sCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CTY</fullName>
                <label>City</label>
            </value>
            <value>
                <fullName>FRCH</fullName>
                <label>Franchise</label>
            </value>
            <value>
                <fullName>UTL</fullName>
                <label>Utility</label>
            </value>
            <value>
                <fullName>LL</fullName>
                <label>Landlord</label>
            </value>
            <value>
                <fullName>OGIT</fullName>
				<isActive>false</isActive>
                <label>OGIT</label>
            </value>
            <value>
                <fullName>RCPT</fullName>
                <label>Reciprocity</label>
            </value>
            <value>
                <fullName>EXCT</fullName>
                <label>Existing Contract</label>
            </value>
            <value>
                <fullName>SPL</fullName>
                <label>Split</label>
            </value>
            <value>
                <fullName>BROKOP</fullName>
                <label>Open Market Broker</label>
            </value>
            <value>
                <fullName>BROKFR</fullName>
                <label>Franchise Market Broker</label>
            </value>
            <value>
                <fullName>BROKCT</fullName>
                <label>Local Contract Broker</label>
            </value>
            <value>
                <fullName>Enter values</fullName>
                <isActive>false</isActive>
                <label>Enter values</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payable entity related to this quote line</description>
    <inlineHelpText>The payable vendor related to this quote line.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/QuoteProcurementDMLServiceTest.cls
/**
 * @description Test class for QuoteProcurementDMLService
 *
 * Tests all DML operations, error handling, and field-level security
 * for the QuoteProcurement data persistence layer.
 *
 * @author Waste Management
 * @date 2025
 * @group Test Classes
 */
@isTest
private class QuoteProcurementDMLServiceTest {

    // ========================================================================
    // TEST SETUP
    // ========================================================================

    @testSetup
    static void setupTestData() {
        // Reuse setup from ContextGetter tests
        Account clientAccount = TestDataFactoryRefactored.createAccount('Client', 'Client');
        insert clientAccount;

        Account locationAccount = TestDataFactoryRefactored.createAccount('Location', 'Location');
        locationAccount.ParentId = clientAccount.Id;
        insert locationAccount;

        Account vendorAccount = TestDataFactoryRefactored.createAccount('Vendor', 'Vendor');
        vendorAccount.Status__c = 'Active';
        insert vendorAccount;

        Contact con = TestDataFactoryRefactored.createContact(clientAccount.Id);
        insert con;

        Product2 product = TestDataFactoryRefactored.createProduct('Rolloff');
        insert product;

        Case testCase = TestDataFactoryRefactored.createCaseWithRelationships(
            clientAccount.Id,
            locationAccount.Id,
            con.Id,
            null,
            'Service_Request'
        );
        insert testCase;

        Opportunity opp = TestDataFactoryRefactored.createOpportunity(clientAccount.Id);
        opp.Case__c = testCase.Id;
        insert opp;

        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__Account__c = locationAccount.Id,
            SBQQ__PrimaryContact__c = con.Id,
            SBQQ__Status__c = 'Draft'
        );
        insert quote;
    }

    // ========================================================================
    // QUOTELINE DML TESTS
    // ========================================================================

    @isTest
    static void testInsertQuoteLines_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>{
            new SBQQ__QuoteLine__c(
                SBQQ__Quote__c = quote.Id,
                SBQQ__Product__c = product.Id,
                SBQQ__Quantity__c = 1
            ),
            new SBQQ__QuoteLine__c(
                SBQQ__Quote__c = quote.Id,
                SBQQ__Product__c = product.Id,
                SBQQ__Quantity__c = 2
            )
        };

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.insertQuoteLines(quoteLines);
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Insert should succeed');
        System.assertEquals(2, result.successCount, 'Should insert 2 records');
        System.assertEquals(0, result.failureCount, 'Should have no failures');
        System.assertEquals(0, result.errors.size(), 'Should have no errors');
    }

    @isTest
    static void testInsertQuoteLines_EmptyList() {
        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.insertQuoteLines(
            new List<SBQQ__QuoteLine__c>()
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Should succeed with empty list');
        System.assertEquals('No records to insert', result.message, 'Should have appropriate message');
    }

    @isTest
    static void testUpdateQuoteLines_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert quoteLine;

        quoteLine.SBQQ__Quantity__c = 5;
        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.updateQuoteLines(
            new List<SBQQ__QuoteLine__c>{quoteLine}
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Update should succeed');
        System.assertEquals(1, result.successCount, 'Should update 1 record');

        SBQQ__QuoteLine__c updated = [SELECT SBQQ__Quantity__c FROM SBQQ__QuoteLine__c
                                     WHERE Id = :quoteLine.Id];
        System.assertEquals(5, updated.SBQQ__Quantity__c, 'Quantity should be updated');
    }

    @isTest
    static void testDeleteQuoteLines_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert quoteLine;

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.deleteQuoteLines(
            new List<SBQQ__QuoteLine__c>{quoteLine}
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Delete should succeed');
        System.assertEquals(1, result.successCount, 'Should delete 1 record');

        List<SBQQ__QuoteLine__c> remaining = [SELECT Id FROM SBQQ__QuoteLine__c
                                             WHERE Id = :quoteLine.Id];
        System.assertEquals(0, remaining.size(), 'Record should be deleted');
    }

    @isTest
    static void testUpsertQuoteLines_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c existingLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert existingLine;

        existingLine.SBQQ__Quantity__c = 3;

        SBQQ__QuoteLine__c newLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 2
        );

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.upsertQuoteLines(
            new List<SBQQ__QuoteLine__c>{existingLine, newLine}
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Upsert should succeed');
        System.assertEquals(2, result.successCount, 'Should upsert 2 records');
    }

    // ========================================================================
    // QUOTE DML TESTS
    // ========================================================================

    @isTest
    static void testUpdateQuotes_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        quote.SBQQ__Status__c = 'Product Configured';

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.updateQuotes(
            new List<SBQQ__Quote__c>{quote}
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Update should succeed');

        SBQQ__Quote__c updated = [SELECT SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id = :quote.Id];
        System.assertEquals('Product Configured', updated.SBQQ__Status__c, 'Status should be updated');
    }

    // ========================================================================
    // QUOTE ORDER DML TESTS
    // ========================================================================

    @isTest
    static void testInsertQuoteOrders_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert quoteLine;

        List<Quote_Order__c> orders = new List<Quote_Order__c>{
            new Quote_Order__c(
                Quote_Line__c = quoteLine.Id,
                Service_Date__c = Date.today().addDays(7),
                Service_Type__c = 'Delivery'
            )
        };

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.insertQuoteOrders(orders);
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Insert should succeed');
        System.assertEquals(1, result.successCount, 'Should insert 1 order');
    }

    @isTest
    static void testDeleteQuoteOrders_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert quoteLine;

        Quote_Order__c order = new Quote_Order__c(
            Quote_Line__c = quoteLine.Id,
            Service_Date__c = Date.today().addDays(7),
            Service_Type__c = 'Delivery'
        );
        insert order;

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.deleteQuoteOrders(
            new List<Quote_Order__c>{order}
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Delete should succeed');
    }

    // ========================================================================
    // ACCOUNT POSITION DML TESTS
    // ========================================================================

    @isTest
    static void testInsertAccountPositions_Success() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        List<Account_Position__c> positions = new List<Account_Position__c>{
            new Account_Position__c(
                AccountId__c = locationAccount.Id,
                Container_Position__c = 'Test Position'
            )
        };

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.insertAccountPositions(positions);
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Insert should succeed');
        System.assertEquals(1, result.successCount, 'Should insert 1 position');
    }

    // ========================================================================
    // BULK UPDATE OPERATION TESTS
    // ========================================================================

    @isTest
    static void testUpdateVendorDetails_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];
        Account vendor = [SELECT Id FROM Account WHERE RecordType.Name = 'Vendor' LIMIT 1];

        SBQQ__QuoteLine__c parentLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert parentLine;

        SBQQ__QuoteLine__c childLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__RequiredBy__c = parentLine.Id,
            SBQQ__Quantity__c = 1
        );
        insert childLine;

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.updateVendorDetails(
            parentLine.Id,
            vendor.Id,
            'SCODE123'
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Vendor update should succeed');

        SBQQ__QuoteLine__c updated = [SELECT Vendor__c, sCode__c FROM SBQQ__QuoteLine__c
                                     WHERE Id = :parentLine.Id];
        System.assertEquals(vendor.Id, updated.Vendor__c, 'Vendor should be updated');
        System.assertEquals('SCODE123', updated.sCode__c, 'S-Code should be updated');
    }

    @isTest
    static void testUpdateCompanyCategories_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c parentLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert parentLine;

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.updateCompanyCategories(
            parentLine.Id,
            'CAT123'
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Company category update should succeed');
    }

    @isTest
    static void testUpdateFinancialDetails_Success() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        SBQQ__QuoteLine__c parentLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert parentLine;

        SBQQ__QuoteLine__c childLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__RequiredBy__c = parentLine.Id,
            SBQQ__Quantity__c = 1
        );
        insert childLine;

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.updateFinancialDetails(
            parentLine.Id,
            true, // isQuoteOnly
            'COMP01',
            'Company Name',
            'GL123',
            'CC456'
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Financial details update should succeed');
    }

    @isTest
    static void testUpdatePositionOnQuoteLines_Success() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];

        Account_Position__c position = new Account_Position__c(
            AccountId__c = locationAccount.Id,
            Container_Position__c = 'Test Position'
        );
        insert position;

        SBQQ__QuoteLine__c parentLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert parentLine;

        QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();

        Test.startTest();
        QuoteProcurementDMLService.DMLResult result = dmlService.updatePositionOnQuoteLines(
            parentLine.Id,
            position.Id,
            'Test Comments',
            false
        );
        Test.stopTest();

        System.assertEquals(true, result.isSuccess, 'Position update should succeed');
    }

    // ========================================================================
    // SINGLETON TESTS
    // ========================================================================

    @isTest
    static void testGetInstance_ReturnsSameInstance() {
        Test.startTest();
        QuoteProcurementDMLService instance1 = QuoteProcurementDMLService.getInstance();
        QuoteProcurementDMLService instance2 = QuoteProcurementDMLService.getInstance();
        Test.stopTest();

        System.assertEquals(instance1, instance2, 'Should return same singleton instance');
    }
}