objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA_Service_Date_Time__c</fullName>
        <label>SLA Service Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <customValue>
        <fullName>Location</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ServiceDateControllerTest.cls
/**
 * @description Test class for ServiceDateController
 * 
 * Tests service date management, SLA datetime calculation, and WM Capacity Planner
 * visibility logic for the unified case management system.
 * 
 * @author Claude (AI Assistant)
 * @date 2025-11-18
 * @group Test Classes
 */
@isTest
private class ServiceDateControllerTest {
    
    /**
     * Test data setup
     */
    @testSetup
    static void setupTestData() {
        // Create test account (location)
        Account testLocation = new Account(
            Name = 'Test Location',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId()
        );
        insert testLocation;
        
        // Create test contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testLocation.Id,
            Email = 'test@example.com'
        );
        insert testContact;
        
        // Create test case
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'New',
            Origin = 'Web',
            Location__c = testLocation.Id,
            ContactId = testContact.Id,
            Case_Type__c = 'Service',
            Case_Sub_Type__c = 'Delivery',
            Service_Date__c = Date.today().addDays(7)
        );
        insert testCase;
    }
    
    /**
     * Test getServiceDateInfo method
     */
    @isTest
    static void testGetServiceDateInfo() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        ServiceDateController.ServiceDateInfo result = 
            ServiceDateController.getServiceDateInfo(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(Date.today().addDays(7), result.serviceDate, 'Service date should match');
    }
    
    /**
     * Test updateServiceDate method
     */
    @isTest
    static void testUpdateServiceDate() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Date newServiceDate = Date.today().addDays(14);
        DateTime newSLADateTime = DateTime.now().addDays(14);
        
        Test.startTest();
        ServiceDateController.updateServiceDate(testCase.Id, newServiceDate, newSLADateTime);
        Test.stopTest();
        
        Case updatedCase = [SELECT Service_Date__c, SLA_Service_Date_Time__c 
                           FROM Case WHERE Id = :testCase.Id];
        
        System.assertEquals(newServiceDate, updatedCase.Service_Date__c, 'Service date should be updated');
        System.assertEquals(newSLADateTime, updatedCase.SLA_Service_Date_Time__c, 'SLA datetime should be updated');
    }
    
    /**
     * Test updateMultiCalendarChecked method
     */
    @isTest
    static void testUpdateMultiCalendarChecked() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        ServiceDateController.updateMultiCalendarChecked(testCase.Id, true);
        Test.stopTest();
        
        Case updatedCase = [SELECT Is_MultiCalendar_Checked__c 
                           FROM Case WHERE Id = :testCase.Id];
        
        System.assertEquals(true, updatedCase.Is_MultiCalendar_Checked__c, 
                          'Multi-calendar flag should be updated');
    }
    
    /**
     * Test calculateSLADateTime method with valid inputs
     */
    @isTest
    static void testCalculateSLADateTime() {
        Date serviceDate = Date.today().addDays(7);
        String serviceTime = '14:30';
        
        Test.startTest();
        DateTime result = ServiceDateController.calculateSLADateTime(serviceDate, serviceTime);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(14, result.hour(), 'Hour should be 14');
        System.assertEquals(30, result.minute(), 'Minute should be 30');
    }
    
    /**
     * Test calculateSLADateTime method with default time
     */
    @isTest
    static void testCalculateSLADateTimeWithDefaultTime() {
        Date serviceDate = Date.today().addDays(7);
        
        Test.startTest();
        DateTime result = ServiceDateController.calculateSLADateTime(serviceDate, '');
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(8, result.hour(), 'Default hour should be 8');
        System.assertEquals(0, result.minute(), 'Default minute should be 0');
    }
    
    /**
     * Test validateServiceDate method
     */
    @isTest
    static void testValidateServiceDate() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Map<String, Object> result = ServiceDateController.validateServiceDate(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assert(result.containsKey('isValid'), 'Result should contain isValid key');
    }
    
    /**
     * Test null/blank input handling
     */
    @isTest
    static void testNullInputHandling() {
        Test.startTest();
        
        // Test null case ID
        ServiceDateController.ServiceDateInfo result1 = 
            ServiceDateController.getServiceDateInfo(null);
        System.assertNotEquals(null, result1, 'Should handle null input gracefully');
        
        // Test null service date
        DateTime result2 = ServiceDateController.calculateSLADateTime(null, '10:00');
        System.assertEquals(null, result2, 'Should return null for null service date');
        
        Test.stopTest();
    }
}