objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Manually_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to change the case sub-status &quot;Pending Manual Dispatch&quot; for Manual Dispatch process.</description>
        <label>Contact Manually Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prepayment_Required__c</fullName>
        <description>Prepayment Required, Yes, No</description>
        <label>Prepayment Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Business_Unit__c</fullName>
        <description>Denotes which WM BU the vendor operates under</description>
        <label>Vendor BU</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Record Type (to replace the Supplier record type)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Quote_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quote Only</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Only__c.field-meta.xml
<CustomField>
    <fullName>Quote_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Product Configured</fullName>
                <label>Procure Service</label>
            </value>
            <value>
                <fullName>Cost Configured</fullName>
                <label>Configure Price</label>
            </value>
            <value>
                <fullName>Price Configured</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/BypassPriceReview__c.field-meta.xml
<CustomField>
    <fullName>BypassPriceReview__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassPriceReview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Description_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Waste__c</fullName>
    <label>Description of Waste</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DoNotCreateMASTicket__c.field-meta.xml
<CustomField>
    <fullName>DoNotCreateMASTicket__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DoNotCreateMASTicket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASAccount__c.field-meta.xml
<CustomField>
    <fullName>MASAccount__c</fullName>
    <label>MASAccount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASCompany__c.field-meta.xml
<CustomField>
    <fullName>MASCompany__c</fullName>
    <label>MASCompany</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASLibrary__c.field-meta.xml
<CustomField>
    <fullName>MASLibrary__c</fullName>
    <inlineHelpText>MAS Library must begin with &quot;ARDTA.&quot; followed by the library name. Example: ARDTA.268</inlineHelpText>
    <label>MASLibrary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Occurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Type__c</fullName>
    <label>Occurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OC</fullName>
                <label>On-Call</label>
            </value>
            <value>
                <fullName>SOC</fullName>
                <label>Scheduled On-Call</label>
            </value>
            <value>
                <fullName>SCH</fullName>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>OnCall`</fullName>
                <isActive>false</isActive>
                <label>OnCall`</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.
If you want to change the Start Date, please update the Vendor Commit Date on the Bundle.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Service_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Service_Schedule__c</fullName>
    <formula>IF(ISPICKVAL(Occurrence_Type__c, &quot;OC&quot;), &quot;On-Call&quot;,
&quot;E&quot; &amp; TEXT(Frequency_Interval__c) &amp; TEXT(Schedule_Frequency__c) &amp; IF(ISPICKVAL(Schedule_Frequency__c, &quot;W&quot;), &quot;(&quot; &amp; (
IF(INCLUDES(Service_Days__c, &quot;S1&quot;), &quot;Su&quot;, &quot;&quot;) &amp;
IF(INCLUDES(Service_Days__c, &quot;M&quot;), &quot;M&quot;, &quot;&quot;) &amp;
IF(INCLUDES(Service_Days__c, &quot;T&quot;), &quot;T&quot;, &quot;&quot;) &amp;
IF(INCLUDES(Service_Days__c, &quot;W&quot;), &quot;W&quot;, &quot;&quot;) &amp;
IF(INCLUDES(Service_Days__c, &quot;T1&quot;), &quot;R&quot;, &quot;&quot;) &amp;
IF(INCLUDES(Service_Days__c, &quot;F&quot;), &quot;F&quot;, &quot;&quot;) &amp;
IF(INCLUDES(Service_Days__c, &quot;S&quot;), &quot;Sa&quot;, &quot;&quot;) &amp; &quot;)&quot; 
)&amp; &quot; - &quot; &amp;  TEXT(Final_Frequency__c)  &amp; &quot;x&quot;, &quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payable entity related to this quote line</description>
    <inlineHelpText>The payable vendor related to this quote line.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/QuoteProcurementWrapperServiceTest.cls
/**
 * @description Test class for QuoteProcurementWrapperService
 *
 * Tests wrapper building operations including:
 * - Building ProductsWrapper from quote data
 * - Creating nested wrapper structures
 * - Retrieving case quotes
 * - Handling complex quote line hierarchies
 *
 * Utilizes TestDataFactoryRefactored for consistent test data creation.
 *
 * @author Waste Management
 * @date 2025
 * @group Test Classes
 */
@isTest
private class QuoteProcurementWrapperServiceTest {

    /**
     * @description Set up test data for all test methods
     */
    @testSetup
    static void setupTestData() {
        // Create test account with parent
        Account parentAccount = TestDataFactoryRefactored.createAccount();
        parentAccount.AccountNumber = 'TEST-PARENT-001';
        insert parentAccount;

        Account testAccount = TestDataFactoryRefactored.createAccount();
        testAccount.ParentId = parentAccount.Id;
        insert testAccount;

        // Create test contact
        Contact testContact = TestDataFactoryRefactored.createContact(testAccount.Id);
        insert testContact;

        // Create test case
        Case testCase = TestDataFactoryRefactored.createCase(testAccount.Id, testContact.Id);
        insert testCase;

        // Create opportunity linked to case
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Case__c = testCase.Id
        );
        insert testOpp;

        // Create quote
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Opportunity2__c = testOpp.Id,
            SBQQ__Status__c = 'Draft',
            SBQQ__PrimaryContact__c = testContact.Id,
            Quote_Only__c = false,
            SBQQ__Type__c = 'Quote'
        );
        insert testQuote;

        // Create test products
        Product2 containerProduct = TestDataFactoryRefactored.createProduct('Test Container', 'Container');
        Product2 wasteCategoryProduct = TestDataFactoryRefactored.createProduct('Test Waste Category', 'Waste Category');
        Product2 wasteStreamProduct = TestDataFactoryRefactored.createProduct('Test Waste Stream', 'Waste Stream');
        Product2 accessoryProduct = TestDataFactoryRefactored.createProduct('Test Accessory', 'Accessories');
        insert new List<Product2>{containerProduct, wasteCategoryProduct, wasteStreamProduct, accessoryProduct};

        // Create vendor
        Account vendor = new Account(
            Name = 'Test Vendor',
            AccountNumber = 'VEND-001',
            Vendor_Business_Unit__c = 'Test BU',
            Contact_Manually_Vendor__c = false,
            Prepayment_Required__c = 'No'
        );
        insert vendor;

        // Create parent quote line (container)
        SBQQ__QuoteLine__c parentQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = containerProduct.Id,
            SBQQ__Number__c = 1,
            SBQQ__Quantity__c = 1,
            Equipment_Size__c = '10 Yard',
            SBQQ__StartDate__c = Date.today(),
            SBQQ__EndDate__c = Date.today().addDays(365),
            Vendor__c = vendor.Id,
            Occurrence_Type__c = 'TOS',
            Service_Schedule__c = 'Weekly',
            Description_of_Waste__c = 'Test Waste',
            MASLibrary__c = 'TEST',
            MASCompany__c = 'TC',
            MASAccount__c = '12345',
            BypassPriceReview__c = false,
            DoNotCreateMASTicket__c = false
        );
        insert parentQL;

        // Create child quote lines
        SBQQ__QuoteLine__c wasteCategoryQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = wasteCategoryProduct.Id,
            SBQQ__RequiredBy__c = parentQL.Id,
            SBQQ__Number__c = 2,
            SBQQ__Quantity__c = 1,
            SBQQ__OptionLevel__c = 1,
            SBQQ__UnitCost__c = 100.00,
            SBQQ__ListPrice__c = 150.00,
            Cost_Unit_of_Measure__c = 'Each',
            PriceUOM__c = 'Each'
        );

        SBQQ__QuoteLine__c wasteStreamQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = wasteStreamProduct.Id,
            SBQQ__RequiredBy__c = wasteCategoryQL.Id,
            SBQQ__Number__c = 3,
            SBQQ__Quantity__c = 1,
            SBQQ__OptionLevel__c = 2,
            SBQQ__UnitCost__c = 50.00,
            SBQQ__ListPrice__c = 75.00
        );

        SBQQ__QuoteLine__c accessoryQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = accessoryProduct.Id,
            SBQQ__RequiredBy__c = parentQL.Id,
            SBQQ__Number__c = 4,
            SBQQ__Quantity__c = 2,
            SBQQ__OptionLevel__c = 1,
            SBQQ__UnitCost__c = 25.00,
            SBQQ__ListPrice__c = 40.00,
            Occurrence_Type__c = 'TOS'
        );

        insert new List<SBQQ__QuoteLine__c>{wasteCategoryQL, wasteStreamQL, accessoryQL};
    }

    /**
     * @description Test buildWrapper - success scenario
     */
    @isTest
    static void testBuildWrapper_Success() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Wrapper should not be null');
        System.assertEquals(true, result.disableMAS, 'MAS should be disabled by default');
        System.assertEquals(true, result.disableCost, 'Cost should be disabled by default');
        System.assertEquals(true, result.disablePrice, 'Price should be disabled by default');
        System.assertNotEquals(null, result.configuredProducts, 'Configured products should not be null');
    }

    /**
     * @description Test buildWrapper - verify configured products
     */
    @isTest
    static void testBuildWrapper_VerifyConfiguredProducts() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        System.assert(result.configuredProducts.size() > 0, 'Should have configured products');

        QuoteProcurementController.HeaderWrapper header = result.configuredProducts[0];
        System.assertNotEquals(null, header.parentId, 'Parent ID should be set');
        System.assertNotEquals(null, header.quoteID, 'Quote ID should be set');
        System.assertNotEquals(null, header.equipmentType, 'Equipment type should be set');
        System.assertEquals('10 Yard', header.equipmentSize, 'Equipment size should match');
    }

    /**
     * @description Test buildWrapper - verify MAS wrapper
     */
    @isTest
    static void testBuildWrapper_VerifyMASWrapper() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        QuoteProcurementController.HeaderWrapper header = result.configuredProducts[0];
        System.assertNotEquals(null, header.MAS, 'MAS wrapper should not be null');
        System.assertEquals('TEST', header.MAS.MASLibrary, 'MAS library should match');
        System.assertEquals('TC', header.MAS.MASCompany, 'MAS company should match');
        System.assertEquals('12345', header.MAS.MASAccount, 'MAS account should match');
        System.assertEquals(false, header.MAS.MASBypassPrice, 'Bypass price should match');
    }

    /**
     * @description Test buildWrapper - verify detail wrappers
     */
    @isTest
    static void testBuildWrapper_VerifyDetailWrappers() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        QuoteProcurementController.HeaderWrapper header = result.configuredProducts[0];
        System.assertNotEquals(null, header.details, 'Details should not be null');

        // Should have waste category and accessory (waste stream is handled separately)
        Boolean hasWasteCategory = false;
        Boolean hasAccessory = false;

        for (QuoteProcurementController.DetailWrapper detail : header.details) {
            if (detail.componentType != null) {
                if (detail.componentType.contains('Waste Category')) {
                    hasWasteCategory = true;
                    System.assertNotEquals(null, detail.vendorCost, 'Cost should be set');
                    System.assertNotEquals(null, detail.customerPrice, 'Price should be set');
                }
                if (detail.componentType.contains('Accessory')) {
                    hasAccessory = true;
                    System.assertEquals(2, detail.componentQuantity, 'Quantity should match');
                }
            }
        }

        System.assert(hasWasteCategory, 'Should have waste category detail');
        System.assert(hasAccessory, 'Should have accessory detail');
    }

    /**
     * @description Test buildWrapper - verify material type from waste stream
     */
    @isTest
    static void testBuildWrapper_VerifyMaterialType() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        QuoteProcurementController.HeaderWrapper header = result.configuredProducts[0];
        // Material type should be set from waste stream
        System.assertNotEquals(null, header.materialType, 'Material type should be set from waste stream');
    }

    /**
     * @description Test buildWrapper - empty quote (no quote lines)
     */
    @isTest
    static void testBuildWrapper_EmptyQuote() {
        Account testAccount = [SELECT Id FROM Account WHERE ParentId != null LIMIT 1];

        // Create empty quote
        SBQQ__Quote__c emptyQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Status__c = 'Draft'
        );
        insert emptyQuote;

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(emptyQuote.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Wrapper should not be null');
        System.assertEquals(emptyQuote.Id, result.singleQuoteId, 'Should set single quote ID for empty quote');
        System.assert(result.configuredProducts == null || result.configuredProducts.isEmpty(),
                     'Should have no configured products');
    }

    /**
     * @description Test getCaseQuotes - success scenario
     */
    @isTest
    static void testGetCaseQuotes_Success() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        List<QuoteProcurementController.ProductsWrapper> result =
            QuoteProcurementWrapperService.getCaseQuotes(testCase.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(1, result.size(), 'Should have one quote for the case');
        System.assertNotEquals(null, result[0].configuredProducts, 'Quote should have configured products');
    }

    /**
     * @description Test getCaseQuotes - multiple quotes for case
     */
    @isTest
    static void testGetCaseQuotes_MultipleQuotes() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account testAccount = [SELECT Id FROM Account WHERE ParentId != null LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Create second quote for same case
        SBQQ__Quote__c secondQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Opportunity2__c = testOpp.Id,
            SBQQ__Status__c = 'Draft'
        );
        insert secondQuote;

        Test.startTest();
        List<QuoteProcurementController.ProductsWrapper> result =
            QuoteProcurementWrapperService.getCaseQuotes(testCase.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(2, result.size(), 'Should have two quotes for the case');
    }

    /**
     * @description Test getCaseQuotes - no quotes for case
     */
    @isTest
    static void testGetCaseQuotes_NoQuotes() {
        Account testAccount = [SELECT Id FROM Account WHERE ParentId != null LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];

        // Create case with no quotes
        Case newCase = TestDataFactoryRefactored.createCase(testAccount.Id, testContact.Id);
        insert newCase;

        Test.startTest();
        List<QuoteProcurementController.ProductsWrapper> result =
            QuoteProcurementWrapperService.getCaseQuotes(newCase.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(0, result.size(), 'Should have no quotes for new case');
    }

    /**
     * @description Test buildWrapper - verify vendor information
     */
    @isTest
    static void testBuildWrapper_VerifyVendorInfo() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        QuoteProcurementController.HeaderWrapper header = result.configuredProducts[0];
        System.assertNotEquals(null, header.vendorId, 'Vendor ID should be set');
        System.assertNotEquals(null, header.vendorName, 'Vendor name should be set');
        System.assertEquals('VEND-001', header.vendorNumber, 'Vendor number should match');
        System.assertEquals('No', header.vendorManualDispatch, 'Vendor manual dispatch should match');
        System.assertEquals('No', header.vendorPrepayment, 'Vendor prepayment should match');
    }

    /**
     * @description Test buildWrapper - verify quote information
     */
    @isTest
    static void testBuildWrapper_VerifyQuoteInfo() {
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        QuoteProcurementController.ProductsWrapper result =
            QuoteProcurementWrapperService.buildWrapper(testQuote.Id);
        Test.stopTest();

        QuoteProcurementController.HeaderWrapper header = result.configuredProducts[0];
        System.assertEquals('Draft', header.quoteStatus, 'Quote status should match');
        System.assertEquals(false, header.quoteOnly, 'Quote only should match');
        System.assertEquals('Quote', header.quoteType, 'Quote type should match');
        System.assertNotEquals(null, header.primaryContact, 'Primary contact should be set');
    }

    /**
     * @description Test buildWrapper - verify error handling
     */
    @isTest
    static void testBuildWrapper_InvalidQuoteId() {
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            QuoteProcurementWrapperService.buildWrapper('INVALID_ID_123');
        } catch (AuraHandledException e) {
            exceptionThrown = true;
            System.assert(e.getMessage().contains('Failed to build wrapper'),
                         'Should throw proper exception for invalid quote ID');
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Exception should be thrown for invalid quote ID');
    }

    /**
     * @description Test getCaseQuotes - verify error handling
     */
    @isTest
    static void testGetCaseQuotes_InvalidCaseId() {
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            QuoteProcurementWrapperService.getCaseQuotes('INVALID_ID_123');
        } catch (AuraHandledException e) {
            exceptionThrown = true;
            System.assert(e.getMessage().contains('Failed to retrieve case quotes'),
                         'Should throw proper exception for invalid case ID');
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Exception should be thrown for invalid case ID');
    }
}