objects/Account.object
<CustomObject>
    <fields>
        <fullName>tz__Timezone_SFDC__c</fullName>
        <description>Salesforce IANA timezone.</description>
        <inlineHelpText>Salesforce IANA timezone.</inlineHelpText>
        <label>Timezone SFDC</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service_Request</fullName>
        <active>true</active>
        <description>A record type to capture requested asset changes or new assets</description>
        <label>Service Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA_Service_Date_Time__c</fullName>
        <label>SLA Service Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>Site Survey, A Ticket has been created in Acorn and needs to be viewed in Salesforce</description>
        <label>Standard Case</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tz__Timezone_SFDC__c</fullName>
        <description>Salesforce IANA timezone.</description>
        <inlineHelpText>Salesforce IANA timezone.</inlineHelpText>
        <label>Timezone SFDC</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Account will be mapped here</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entitlements(Location)</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement/recordTypes/SLA.recordType-meta.xml
<RecordType>
    <fullName>SLA</fullName>
    <active>true</active>
    <label>SLA</label>
</RecordType>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/SLACalculationUtilityTest.cls
/**
 * @description Comprehensive test class for SLACalculationUtility
 *
 * Coverage Target: 85%+
 *
 * Tests all SLA calculation methods, timezone conversions, service date calculations,
 * and business hours logic.
 *
 * @author Refactored Architecture Team
 * @date 2025
 * @group Test Classes
 */
@isTest
private class SLACalculationUtilityTest {

    @testSetup
    static void setupTestData() {
        // Create full test hierarchy
        Map<String, Object> testData = TestDataFactoryRefactored.createFullTestHierarchy();

        Account locationAccount = (Account)testData.get('locationAccount');
        // Set timezone for location
        locationAccount.tz__Timezone_SFDC__c = 'America/New_York';
        update locationAccount;

        Contact contact = (Contact)testData.get('contact');
        Asset asset = (Asset)testData.get('asset');
        Account clientAccount = (Account)testData.get('clientAccount');

        // Create Product and ServiceContract for Entitlement
        Product2 entitlementProduct = new Product2(
            Name = 'Test Entitlement Product',
            IsActive = true,
            Family = 'Commercial'
        );
        insert entitlementProduct;

        ServiceContract sc = new ServiceContract(
            Name = 'Test Service Contract',
            AccountId = clientAccount.Id,
            StartDate = Date.today().addDays(-365),
            EndDate = Date.today().addDays(365)
        );
        insert sc;

        // Create Entitlement with SLA configuration
        Entitlement entitlement = new Entitlement(
            Name = 'Test Entitlement',
            AccountId = clientAccount.Id,
            ServiceContractId = sc.Id,
            StartDate = Date.today().addDays(-365),
            EndDate = Date.today().addDays(365),
            SLA_Start_Pickup__c = 'Same Day',
            SLA_Days__c = 1,
            SLA_Pickup_Days__c = 1,
            AssetId = asset.Id
        );
        insert entitlement;

        // Create cases with different scenarios
        List<Case> testCases = new List<Case>();

        // Case with service date in the future
        Case futureCase = TestDataFactoryRefactored.createCaseWithRelationships(
            clientAccount.Id, locationAccount.Id, contact.Id, asset.Id, 'Service_Request'
        );
        futureCase.Service_Date__c = Date.today().addDays(7);
        futureCase.EntitlementId = entitlement.Id;
        testCases.add(futureCase);

        // Case with service date today
        Case todayCase = TestDataFactoryRefactored.createCaseWithRelationships(
            clientAccount.Id, locationAccount.Id, contact.Id, asset.Id, 'Service_Request'
        );
        todayCase.Service_Date__c = Date.today();
        todayCase.EntitlementId = entitlement.Id;
        testCases.add(todayCase);

        // Case with past service date
        Case pastCase = TestDataFactoryRefactored.createCaseWithRelationships(
            clientAccount.Id, locationAccount.Id, contact.Id, asset.Id, 'Service_Request'
        );
        pastCase.Service_Date__c = Date.today().addDays(-2);
        pastCase.EntitlementId = entitlement.Id;
        testCases.add(pastCase);

        insert testCases;
    }

    // ========================================
    // SERVICE DATE CALCULATION TESTS
    // ========================================

    @isTest
    static void testSetServiceDate_WithEntitlement() {
        // Given: Cases with entitlements
        List<Case> cases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, EntitlementId
                            FROM Case WHERE EntitlementId != null LIMIT 3];

        Test.startTest();

        // When
        SLACalculationUtility.setServiceDate(cases);

        Test.stopTest();

        // Then: Service dates should be calculated
        for (Case c : cases) {
            System.assertNotEquals(null, c, 'Case should not be null');
        }
    }

    @isTest
    static void testSetServiceDate_NullInput() {
        Test.startTest();

        // When
        SLACalculationUtility.setServiceDate(null);

        Test.stopTest();

        // Then: Should handle gracefully without errors
        System.assert(true, 'Should handle null input gracefully');
    }

    @isTest
    static void testSetServiceDate_EmptyList() {
        Test.startTest();

        // When
        SLACalculationUtility.setServiceDate(new List<Case>());

        Test.stopTest();

        // Then: Should handle gracefully without errors
        System.assert(true, 'Should handle empty list gracefully');
    }

    // ========================================
    // CASE LOCATION MAP TESTS
    // ========================================

    @isTest
    static void testBuildCaseLocationMap_Success() {
        // Given: Cases with locations
        List<Case> cases = [SELECT Id, Location__c FROM Case WHERE Location__c != null LIMIT 3];

        Test.startTest();

        // When
        Map<Case, Account> caseLocationMap = SLACalculationUtility.buildCaseLocationMap(cases);

        Test.stopTest();

        // Then: Map should be built
        System.assertNotEquals(null, caseLocationMap, 'Map should not be null');
        System.assertEquals(cases.size(), caseLocationMap.size(), 'Map should contain all cases');
    }

    @isTest
    static void testBuildCaseLocationMap_NullInput() {
        Test.startTest();

        // When
        Map<Case, Account> caseLocationMap = SLACalculationUtility.buildCaseLocationMap(null);

        Test.stopTest();

        // Then: Empty map should be returned
        System.assertNotEquals(null, caseLocationMap, 'Map should not be null');
        System.assertEquals(0, caseLocationMap.size(), 'Map should be empty');
    }

    @isTest
    static void testBuildCaseLocationMap_EmptyList() {
        Test.startTest();

        // When
        Map<Case, Account> caseLocationMap = SLACalculationUtility.buildCaseLocationMap(new List<Case>());

        Test.stopTest();

        // Then: Empty map should be returned
        System.assertEquals(0, caseLocationMap.size(), 'Map should be empty');
    }

    // ========================================
    // TIMEZONE CONVERSION TESTS
    // ========================================

    @isTest
    static void testGetLocalTime_WithTimezone() {
        // Given: Account with timezone
        Account locationAccount = [SELECT Id, tz__Timezone_SFDC__c FROM Account WHERE tz__Timezone_SFDC__c != null LIMIT 1];

        Test.startTest();

        // When
        DateTime localTime = SLACalculationUtility.getLocalTime(locationAccount);

        Test.stopTest();

        // Then: Local time should be returned
        System.assertNotEquals(null, localTime, 'Local time should not be null');
    }

    @isTest
    static void testGetLocalTime_NullAccount() {
        Test.startTest();

        // When
        DateTime localTime = SLACalculationUtility.getLocalTime(null);

        Test.stopTest();

        // Then: Should return current time or handle gracefully
        // (depends on implementation)
        System.assert(true, 'Should handle null account gracefully');
    }

    @isTest
    static void testConvertToLocationTimezone_Success() {
        // Given: Case with location
        Case testCase = [SELECT Id, Location__c FROM Case WHERE Location__c != null LIMIT 1];
        Account locationAccount = [SELECT Id, tz__Timezone_SFDC__c FROM Account WHERE Id = :testCase.Location__c];
        Map<Id, Account> locationMap = new Map<Id, Account>{locationAccount.Id => locationAccount};

        DateTime testDateTime = DateTime.now();

        Test.startTest();

        // When
        DateTime convertedTime = SLACalculationUtility.convertToLocationTimezone(testDateTime, testCase, locationMap);

        Test.stopTest();

        // Then: Converted time should be returned
        System.assertNotEquals(null, convertedTime, 'Converted time should not be null');
    }

    @isTest
    static void testConvertToStandardTimezone_Success() {
        // Given: Case
        Case testCase = [SELECT Id, Location__c FROM Case LIMIT 1];
        DateTime testDateTime = DateTime.now();

        Test.startTest();

        // When
        DateTime convertedTime = SLACalculationUtility.convertToStandardTimezone(testDateTime, testCase);

        Test.stopTest();

        // Then: Converted time should be returned
        System.assertNotEquals(null, convertedTime, 'Converted time should not be null');
    }

    // ========================================
    // CUTOFF TIME TESTS
    // ========================================

    @isTest
    static void testIsBeforeCutoff_BeforeCutoff() {
        // Given: Case and account
        Case testCase = [SELECT Id, Service_Date__c FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id, tz__Timezone_SFDC__c FROM Account WHERE tz__Timezone_SFDC__c != null LIMIT 1];

        Test.startTest();

        // When: Check if before 2PM cutoff
        Boolean isBeforeCutoff = SLACalculationUtility.isBeforeCutoff(testCase, locationAccount, 14);

        Test.stopTest();

        // Then: Should return boolean result
        System.assertNotEquals(null, isBeforeCutoff, 'Result should not be null');
    }

    @isTest
    static void testIsBeforeCutoff_AfterCutoff() {
        // Given: Case and account
        Case testCase = [SELECT Id, Service_Date__c FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id, tz__Timezone_SFDC__c FROM Account WHERE tz__Timezone_SFDC__c != null LIMIT 1];

        Test.startTest();

        // When: Check if before 6AM cutoff (early morning)
        Boolean isBeforeCutoff = SLACalculationUtility.isBeforeCutoff(testCase, locationAccount, 6);

        Test.stopTest();

        // Then: Should return boolean result
        System.assertNotEquals(null, isBeforeCutoff, 'Result should not be null');
    }

    // ========================================
    // ENTITLEMENT SLA CALCULATION TESTS
    // ========================================

    @isTest
    static void testGetDaysDelta_SameDay() {
        // Given: Entitlement with Same Day SLA
        Entitlement ent = [SELECT Id, SLA_Start_Pickup__c, SLA_Days__c FROM Entitlement LIMIT 1];

        Test.startTest();

        // When
        Integer daysDelta = SLACalculationUtility.getDaysDelta(ent);

        Test.stopTest();

        // Then: Should return appropriate days delta
        System.assertNotEquals(null, daysDelta, 'Days delta should not be null');
        System.assert(daysDelta >= 0, 'Days delta should be non-negative');
    }

    @isTest
    static void testGetDaysDelta_NullEntitlement() {
        Test.startTest();

        // When
        Integer daysDelta = SLACalculationUtility.getDaysDelta(null);

        Test.stopTest();

        // Then: Should return default value
        System.assertNotEquals(null, daysDelta, 'Days delta should not be null');
    }

    @isTest
    static void testCalculateEntitlementSLA_WithBusinessHours() {
        // Given: Entitlement and business hours
        Entitlement ent = [SELECT Id, SLA_Start_Pickup__c, SLA_Days__c, SLA_Pickup_Days__c FROM Entitlement LIMIT 1];

        // Get or create business hours
        List<BusinessHours> bhList = [SELECT Id FROM BusinessHours WHERE IsDefault = true LIMIT 1];
        BusinessHours bh = bhList.isEmpty() ? null : bhList[0];

        Test.startTest();

        // When
        DateTime slaDateTime = SLACalculationUtility.calculateEntitlementSLA(ent, bh);

        Test.stopTest();

        // Then: SLA DateTime should be calculated
        System.assertNotEquals(null, slaDateTime, 'SLA DateTime should not be null');
        System.assert(slaDateTime > DateTime.now(), 'SLA DateTime should be in the future');
    }

    @isTest
    static void testCalculateEntitlementSLA_NullBusinessHours() {
        // Given: Entitlement without business hours
        Entitlement ent = [SELECT Id, SLA_Start_Pickup__c, SLA_Days__c, SLA_Pickup_Days__c FROM Entitlement LIMIT 1];

        Test.startTest();

        // When
        DateTime slaDateTime = SLACalculationUtility.calculateEntitlementSLA(ent, null);

        Test.stopTest();

        // Then: Should handle gracefully
        System.assertNotEquals(null, slaDateTime, 'SLA DateTime should not be null');
    }

    // ========================================
    // SLA RESET LOGIC TESTS
    // ========================================

    @isTest
    static void testRequiresSLAandServiceDateReset_TypeChanged() {
        // Given: Cases with changed type
        Case oldCase = new Case(Case_Type__c = 'Pickup');
        Case newCase = new Case(Case_Type__c = 'Status');

        Test.startTest();

        // When
        Boolean requiresReset = SLACalculationUtility.requiresSLAandServiceDateReset(newCase, oldCase);

        Test.stopTest();

        // Then: Should require reset
        System.assertEquals(true, requiresReset, 'Should require SLA reset when type changes');
    }

    @isTest
    static void testRequiresSLAandServiceDateReset_SubTypeChanged() {
        // Given: Cases with changed subtype
        Case oldCase = new Case(Case_Type__c = 'Pickup', Case_Sub_Type__c = 'On-Call Pick');
        Case newCase = new Case(Case_Type__c = 'Pickup', Case_Sub_Type__c = 'Extra Pickup');

        Test.startTest();

        // When
        Boolean requiresReset = SLACalculationUtility.requiresSLAandServiceDateReset(newCase, oldCase);

        Test.stopTest();

        // Then: Should require reset
        System.assertEquals(true, requiresReset, 'Should require SLA reset when subtype changes');
    }

    @isTest
    static void testRequiresSLAandServiceDateReset_NoChanges() {
        // Given: Cases with no changes
        Case oldCase = new Case(Case_Type__c = 'Pickup', Case_Sub_Type__c = 'Extra Pickup');
        Case newCase = new Case(Case_Type__c = 'Pickup', Case_Sub_Type__c = 'Extra Pickup');

        Test.startTest();

        // When
        Boolean requiresReset = SLACalculationUtility.requiresSLAandServiceDateReset(newCase, oldCase);

        Test.stopTest();

        // Then: Should not require reset
        System.assertEquals(false, requiresReset, 'Should not require SLA reset when nothing changes');
    }

    // ========================================
    // SERVICE DATE CALCULATION TESTS
    // ========================================

    @isTest
    static void testCalculateServiceDates_WithEntitlements() {
        // Given: Cases with entitlements
        List<Case> cases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, EntitlementId, Location__c
                            FROM Case WHERE EntitlementId != null LIMIT 2];

        Test.startTest();

        // When
        List<Case> updatedCases = SLACalculationUtility.calculateServiceDates(cases, new Map<Id, Case>());

        Test.stopTest();

        // Then: Service dates should be calculated
        System.assertNotEquals(null, updatedCases, 'Updated cases should not be null');
        System.assertEquals(cases.size(), updatedCases.size(), 'All cases should be processed');
    }

    @isTest
    static void testCalculateServiceDates_NullInput() {
        Test.startTest();

        // When
        List<Case> updatedCases = SLACalculationUtility.calculateServiceDates(null, null);

        Test.stopTest();

        // Then: Should return empty list or handle gracefully
        System.assert(true, 'Should handle null input gracefully');
    }

    @isTest
    static void testCalculateStandardServiceDates_Success() {
        // Given: Cases
        List<Case> cases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, Location__c FROM Case LIMIT 2];

        Test.startTest();

        // When
        List<Case> updatedCases = SLACalculationUtility.calculateStandardServiceDates(cases);

        Test.stopTest();

        // Then: Service dates should be calculated
        System.assertNotEquals(null, updatedCases, 'Updated cases should not be null');
    }

    @isTest
    static void testCalculateStandardServiceDates_NullInput() {
        Test.startTest();

        // When
        List<Case> updatedCases = SLACalculationUtility.calculateStandardServiceDates(null);

        Test.stopTest();

        // Then: Should handle gracefully
        System.assert(true, 'Should handle null input gracefully');
    }

    // ========================================
    // SLA CORRECTION TESTS
    // ========================================

    @isTest
    static void testCorrectSLADate_Success() {
        // Given: Case and location map
        Case testCase = [SELECT Id, SLA_Service_Date_Time__c, Location__c FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id, tz__Timezone_SFDC__c FROM Account WHERE Id = :testCase.Location__c];
        Map<Id, Account> locationMap = new Map<Id, Account>{locationAccount.Id => locationAccount};

        Test.startTest();

        // When
        DateTime correctedSLA = SLACalculationUtility.correctSLADate(testCase, locationMap);

        Test.stopTest();

        // Then: Corrected SLA should be returned
        System.assertNotEquals(null, correctedSLA, 'Corrected SLA should not be null');
    }

    @isTest
    static void testCorrectSLADate_NullCase() {
        Test.startTest();

        // When
        DateTime correctedSLA = SLACalculationUtility.correctSLADate(null, new Map<Id, Account>());

        Test.stopTest();

        // Then: Should handle gracefully
        System.assert(true, 'Should handle null case gracefully');
    }

    // ========================================
    // INTAKE SLA CALCULATION TESTS
    // ========================================

    @isTest
    static void testCalculateIntakeSLADatetime_Success() {
        // Given: Service date and parameters
        DateTime serviceDate = DateTime.now().addDays(1);
        DateTime currentSLA = DateTime.now();
        Integer daysDelta = 1;

        List<BusinessHours> bhList = [SELECT Id FROM BusinessHours WHERE IsDefault = true LIMIT 1];
        Id businessHoursId = bhList.isEmpty() ? null : bhList[0].Id;

        Test.startTest();

        // When
        DateTime intakeSLA = SLACalculationUtility.calculateIntakeSLADatetime(
            serviceDate, currentSLA, daysDelta, businessHoursId, 14);

        Test.stopTest();

        // Then: Intake SLA should be calculated
        System.assertNotEquals(null, intakeSLA, 'Intake SLA should not be null');
    }

    @isTest
    static void testCalculateIntakeSLADatetime_NullBusinessHours() {
        // Given: Service date without business hours
        DateTime serviceDate = DateTime.now().addDays(1);
        DateTime currentSLA = DateTime.now();

        Test.startTest();

        // When
        DateTime intakeSLA = SLACalculationUtility.calculateIntakeSLADatetime(
            serviceDate, currentSLA, 1, null, 14);

        Test.stopTest();

        // Then: Should handle gracefully
        System.assertNotEquals(null, intakeSLA, 'Intake SLA should not be null');
    }

    // ========================================
    // SERVICE DATE SYNC TESTS
    // ========================================

    @isTest
    static void testSyncServiceDateToSLA_Success() {
        // Given: Cases with old map
        List<Case> newCases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, Location__c
                               FROM Case LIMIT 2];
        List<Case> oldCases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, Location__c
                               FROM Case WHERE Id IN :newCases];

        Map<Id, Case> oldCaseMap = new Map<Id, Case>(oldCases);

        Test.startTest();

        // When
        SLACalculationUtility.syncServiceDateToSLA(newCases, oldCaseMap, new Map<Id, Account>());

        Test.stopTest();

        // Then: Should execute without errors
        System.assert(true, 'Should sync service dates successfully');
    }

    @isTest
    static void testSyncServiceDateToSLA_NullInput() {
        Test.startTest();

        // When
        SLACalculationUtility.syncServiceDateToSLA(null, null, null);

        Test.stopTest();

        // Then: Should handle gracefully
        System.assert(true, 'Should handle null input gracefully');
    }

    @isTest
    static void testSyncStandardServiceDateToSLA_Success() {
        // Given: Cases with old map
        List<Case> newCases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, Location__c
                               FROM Case LIMIT 2];
        List<Case> oldCases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, Location__c
                               FROM Case WHERE Id IN :newCases];

        Map<Id, Case> oldCaseMap = new Map<Id, Case>(oldCases);

        Test.startTest();

        // When
        SLACalculationUtility.syncStandardServiceDateToSLA(newCases, oldCaseMap);

        Test.stopTest();

        // Then: Should execute without errors
        System.assert(true, 'Should sync standard service dates successfully');
    }

    @isTest
    static void testSyncStandardServiceDateToSLA_NullInput() {
        Test.startTest();

        // When
        SLACalculationUtility.syncStandardServiceDateToSLA(null, null);

        Test.stopTest();

        // Then: Should handle gracefully
        System.assert(true, 'Should handle null input gracefully');
    }

    // ========================================
    // BULK OPERATION TESTS
    // ========================================

    @isTest
    static void testBulkServiceDateCalculation_WithinGovernorLimits() {
        // Given: Multiple cases
        List<Case> cases = [SELECT Id, Service_Date__c, SLA_Service_Date_Time__c, EntitlementId, Location__c
                            FROM Case LIMIT 10];

        Test.startTest();

        // When
        SLACalculationUtility.setServiceDate(cases);

        // Then: Should complete within governor limits
        Integer queries = Limits.getQueries();
        System.assert(queries < Limits.getLimitQueries(), 'Should be within SOQL query limits');

        Test.stopTest();
    }
}