objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>SLA_Override_Comment__c</fullName>
        <inlineHelpText>Provide the SLA Override Comments if Bypass SLA Override Reason is selected as &apos;Other&apos;.</inlineHelpText>
        <label>SLA Override Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SLA_Override_Reason__c</fullName>
        <description>The field provide SLA Override reason in the case when the Service Date is not equal to the SLA Date.</description>
        <label>SLA Override Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Repairs</fullName>
                </value>
                <value>
                    <fullName>Corporate Visit/Walkthrough</fullName>
                </value>
                <value>
                    <fullName>Power Outage</fullName>
                </value>
                <value>
                    <fullName>Potential Violation</fullName>
                </value>
                <value>
                    <fullName>Weather/Natural Disaster</fullName>
                </value>
                <value>
                    <fullName>Internal Error</fullName>
                </value>
                <value>
                    <fullName>Vendor Error</fullName>
                </value>
                <value>
                    <fullName>Vendor not able to meet SLA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>NAM/PM</fullName>
                    <isActive>false</isActive>
                    <label>NAM/PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SLA_Override_Comment__c.field-meta.xml
<CustomField>
    <fullName>SLA_Override_Comment__c</fullName>
    <label>SLA Override Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SLA_Override_Reason__c.field-meta.xml
<CustomField>
    <fullName>SLA_Override_Reason__c</fullName>
    <label>SLA Override Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repairs</fullName>
            </value>
            <value>
                <fullName>Corporate Visit/Walkthrough</fullName>
            </value>
            <value>
                <fullName>Power Outage</fullName>
            </value>
            <value>
                <fullName>Potential Violation</fullName>
            </value>
            <value>
                <fullName>Weather/Natural Disaster</fullName>
            </value>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>Vendor Error</fullName>
            </value>
            <value>
                <fullName>Vendor not able to meet SLA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/QuoteProcurementIntegrationServiceTest.cls
/**
 * @description Test class for QuoteProcurementIntegrationService
 * @author Waste Management
 * @date 2025
 */
@isTest
private class QuoteProcurementIntegrationServiceTest {

    @testSetup
    static void setupTestData() {
        Account clientAccount = TestDataFactoryRefactored.createAccount('Client', 'Client');
        insert clientAccount;

        Product2 product = TestDataFactoryRefactored.createProduct('Rolloff');
        insert product;

        Case testCase = TestDataFactoryRefactored.createCase('Service_Request');
        testCase.AccountId = clientAccount.Id;
        insert testCase;

        Opportunity opp = TestDataFactoryRefactored.createOpportunity(clientAccount.Id);
        opp.Case__c = testCase.Id;
        insert opp;

        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__Account__c = clientAccount.Id
        );
        insert quote;

        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1,
            SLA_Override_Reason__c = 'Test Reason',
            SLA_Override_Comment__c = 'Test Comment'
        );
        insert quoteLine;
    }

    @isTest
    static void testAddCommentForSLAOverrideFromIntake() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        QuoteProcurementIntegrationService.addCommentForSLAOverrideFromIntake(testCase.Id);
        Test.stopTest();

        // Should not throw exception
        System.assert(true, 'Method should execute without errors');
    }

    @isTest
    static void testAddCommentForSLAOverride() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        QuoteProcurementIntegrationService.addCommentForSLAOverride(
            testCase.Id,
            'Test SLA Comment',
            'Customer Request'
        );
        Test.stopTest();

        // Should not throw exception
        System.assert(true, 'Method should execute without errors');
    }

    @isTest
    static void testInputWrapperForMIFFlow() {
        Test.startTest();
        QuoteProcurementIntegrationService.InputWrapperForMIFFlow wrapper =
            new QuoteProcurementIntegrationService.InputWrapperForMIFFlow();
        wrapper.caseId = 'test123';
        wrapper.slaComment = 'test comment';
        wrapper.slaReason = 'test reason';
        Test.stopTest();

        System.assertNotEquals(null, wrapper.caseId, 'Wrapper should store case ID');
    }
}