objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Category__c</fullName>
        <label>Company Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FacilityCode__c</fullName>
        <description>To Store Facility Code.</description>
        <label>FacilityCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Vendor_ID__c</fullName>
        <description>Numeric ID assigned by the system to the parent vendor</description>
        <formula>Parent.Vendor_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Vendor ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Gives the Status of the Account</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Do Not Use</fullName>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pass-Thru</fullName>
                </value>
                <value>
                    <fullName>Oak-Fee</fullName>
                </value>
                <value>
                    <fullName>Out To Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Business_Unit__c</fullName>
        <description>Denotes which WM BU the vendor operates under</description>
        <label>Vendor BU</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Record Type (to replace the Supplier record type)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Position__c.object
<CustomObject>
    <description>Service Container Positions for Location</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Positions</relationshipLabel>
        <relationshipName>Account_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AlternateCity__c</fullName>
        <label>Alternate City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AlternatePostalCode__c</fullName>
        <label>Alternate Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AlternateState__c</fullName>
        <label>Alternate State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AlternateStreet__c</fullName>
        <label>Alternate Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Container_Position__c</fullName>
        <description>Position at location where container is located</description>
        <label>Container Position</label>
        <type>TextArea</type>
    </fields>
    <label>Account Position</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Code__c.object
<CustomObject>
    <fields>
        <fullName>Client_Account__c</fullName>
        <description>Lookup to client Accounts</description>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Category__c</fullName>
        <label>Company Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Temporary and Permanent</fullName>
                </value>
                <value>
                    <fullName>Seasonal</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Codes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Codes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Code</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active projects may be associated to quotes</errorMessage>
        <filterItems>
            <field>Project_Code__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Code__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Project_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/QuoteProcurementSearchService.cls
/**
 * @description QuoteProcurementSearchService - Search and lookup operations layer
 *
 * This service handles all SOSL search operations for vendors, positions, and projects.
 * It provides consistent search interfaces and result formatting.
 *
 * Key Responsibilities:
 * - Vendor SOSL searches
 * - Account Position searches
 * - Project Code searches
 * - Result sorting and formatting
 *
 * @author Waste Management
 * @date 2025
 * @group Service Layer - Search Operations
 */
public with sharing class QuoteProcurementSearchService {

    // ========================================================================
    // PUBLIC API - VENDOR SEARCH
    // ========================================================================

    /**
     * @description Search for vendors using SOSL
     * Refactored from: searchVendors() in QuoteProcurementController
     * @param searchString The search term
     * @return List<Account> List of matching vendor accounts
     */
    @AuraEnabled
    public static List<Account> searchVendors(String searchString) {
        List<Account> vendorList = new List<Account>();

        List<List<SObject>> searchList = [
            FIND :searchString
            IN ALL FIELDS
            RETURNING Account(
                Id, Name, AccountNumber, Vendor_Business_Unit__c, ShippingState,
                ShippingCity, FacilityCode__c, Parent_Vendor_Id__c, Status__c
                WHERE RecordType.Name = 'Vendor'
            )
        ];

        if (!searchList.isEmpty()) {
            vendorList = (Account[])searchList[0];
        }

        return vendorList;
    }

    // ========================================================================
    // PUBLIC API - POSITION SEARCH
    // ========================================================================

    /**
     * @description Get all positions for a location
     * Refactored from: allPositions() in QuoteProcurementController
     * @param locationId The location Account ID
     * @return List<Account_Position__c> All positions for location
     */
    @AuraEnabled
    public static List<Account_Position__c> getAllPositions(Id locationId) {
        return QuoteProcurementContextGetter.getAllPositions(locationId);
    }

    /**
     * @description Search positions for a location
     * Refactored from: searchPositions() in QuoteProcurementController
     * @param locationId The location Account ID
     * @param searchString The search term (optional)
     * @return List<Account_Position__c> Matching positions
     */
    @AuraEnabled
    public static List<Account_Position__c> searchPositions(Id locationId, String searchString) {
        List<Account_Position__c> positions = new List<Account_Position__c>();

        if (String.isBlank(searchString)) {
            return getAllPositions(locationId);
        }

        List<List<SObject>> searchList = [
            FIND :searchString
            IN ALL FIELDS
            RETURNING Account_Position__c(
                Id, Name, Container_Position__c, AlternateStreet__c,
                AlternateCity__c, AlternateState__c, AlternatePostalCode__c
                WHERE AccountId__c = :locationId
                ORDER BY Container_Position__c ASC
            )
        ];

        if (!searchList.isEmpty()) {
            positions = (Account_Position__c[])searchList[0];
        }

        return positions;
    }

    // ========================================================================
    // PUBLIC API - PROJECT SEARCH
    // ========================================================================

    /**
     * @description Search for active projects
     * Refactored from: getActiveProjects() in QuoteProcurementController
     * @param quoteId The Quote ID
     * @param searchString The search term
     * @return List<Project_Code__c> Matching projects
     */
    @AuraEnabled
    public static List<Project_Code__c> searchActiveProjects(Id quoteId, String searchString) {
        SBQQ__Quote__c currentQuote = [
            SELECT Id, Project__c, Project__r.Name, SBQQ__Account__c, SBQQ__Account__r.ParentId
            FROM SBQQ__Quote__c
            WHERE Id = :quoteId
            LIMIT 1
        ];

        List<List<SObject>> projectSOSL = [
            FIND :searchString
            IN NAME FIELDS
            RETURNING Project_Code__c(
                Id, Name, Project_Manager__r.Name, Program_Manager__r.Name,
                Effective_Date__c, End_Date__c, Duration__c, Company_Category__c
                WHERE Client_Account__c = :currentQuote.SBQQ__Account__r.ParentId
                ORDER BY Project_Manager__r.Name ASC, Effective_Date__c DESC
            )
        ];

        List<Project_Code__c> activeProjects = new List<Project_Code__c>();
        if (!projectSOSL.isEmpty()) {
            activeProjects = (Project_Code__c[])projectSOSL[0];
        }

        return activeProjects;
    }
}