objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSI__c</fullName>
        <description>PSI of the service</description>
        <label>PSI</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_Number__c</fullName>
        <label>Profile Number #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseOrder_Number__c</fullName>
        <description>PO Number for the case captured through the flow</description>
        <label>Customer PO #</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <customValue>
        <fullName>Location</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/BusinessRuleValidatorControllerTest.cls
/**
 * @description Test class for BusinessRuleValidatorController
 * 
 * Tests business rule evaluation, validation, and button visibility logic
 * for the unified case management system.
 * 
 * @author George Martin
 * @date 2025-11-18
 * @group Test Classes
 */
@isTest
private class BusinessRuleValidatorControllerTest {
    
    /**
     * Test data setup
     */
    @testSetup
    static void setupTestData() {
        // Create test account (location)
        Account testLocation = new Account(
            Name = 'Test Location',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId()
        );
        insert testLocation;
        
        // Create test contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testLocation.Id,
            Email = 'test@example.com'
        );
        insert testContact;
        
        // Create test asset
        Product2 testProduct = new Product2(Name = 'Test Product');
        insert testProduct;
        
        Asset testAsset = new Asset(
            Name = 'Test Asset',
            AccountId = testLocation.Id,
            Product2Id = testProduct.Id,
            Status = 'Active'
        );
        insert testAsset;
        
        // Create test case
        Case testCase = new Case(
            Subject = 'Test Case',
            Status = 'New',
            Origin = 'Web',
            Location__c = testLocation.Id,
            ContactId = testContact.Id,
            AssetId = testAsset.Id,
            Case_Type__c = 'Service',
            Case_Sub_Type__c = 'Delivery',
            PurchaseOrder_Number__c = 'PO123',
            Profile_Number__c = 'PROF456'
        );
        insert testCase;
    }
    
    /**
     * Test evaluateBusinessRules method
     */
    @isTest
    static void testEvaluateBusinessRules() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        BusinessRuleValidatorController.BusinessRuleEvaluation result = 
            BusinessRuleValidatorController.evaluateBusinessRules(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assert(result.messages != null, 'Messages list should be initialized');
    }
    
    /**
     * Test isPurchaseOrderRequired method
     */
    @isTest
    static void testIsPurchaseOrderRequired() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Boolean result = BusinessRuleValidatorController.isPurchaseOrderRequired(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
    }
    
    /**
     * Test isProfileNumberRequired method
     */
    @isTest
    static void testIsProfileNumberRequired() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Boolean result = BusinessRuleValidatorController.isProfileNumberRequired(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
    }
    
    /**
     * Test isPSIRequired method
     */
    @isTest
    static void testIsPSIRequired() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Boolean result = BusinessRuleValidatorController.isPSIRequired(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
    }
    
    /**
     * Test shouldShowProgressCaseButton method
     */
    @isTest
    static void testShouldShowProgressCaseButton() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Boolean result = BusinessRuleValidatorController.shouldShowProgressCaseButton(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
    }
    
    /**
     * Test shouldShowAddQuoteButton method
     */
    @isTest
    static void testShouldShowAddQuoteButton() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Boolean result = BusinessRuleValidatorController.shouldShowAddQuoteButton(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
    }
    
    /**
     * Test updateCustomerInfoFields method
     */
    @isTest
    static void testUpdateCustomerInfoFields() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        BusinessRuleValidatorController.FieldUpdates updates = 
            new BusinessRuleValidatorController.FieldUpdates();
        updates.purchaseOrderNumber = 'PO999';
        updates.profileNumber = 'PROF999';
        updates.psi = 10.5;
        
        String updatesJson = JSON.serialize(updates);
        
        Test.startTest();
        BusinessRuleValidatorController.updateCustomerInfoFields(testCase.Id, updatesJson);
        Test.stopTest();
        
        Case updatedCase = [SELECT PurchaseOrder_Number__c, Profile_Number__c, PSI__c 
                           FROM Case WHERE Id = :testCase.Id];
        
        System.assertEquals('PO999', updatedCase.PurchaseOrder_Number__c, 'PO should be updated');
        System.assertEquals('PROF999', updatedCase.Profile_Number__c, 'Profile should be updated');
        System.assertEquals(10.5, updatedCase.PSI__c, 'PSI should be updated');
    }
    
    /**
     * Test getCurrentCustomerInfo method
     */
    @isTest
    static void testGetCurrentCustomerInfo() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        BusinessRuleValidatorController.CustomerInfoFields result = 
            BusinessRuleValidatorController.getCurrentCustomerInfo(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals('PO123', result.purchaseOrderNumber, 'PO should match');
        System.assertEquals('PROF456', result.profileNumber, 'Profile should match');
    }
    
    /**
     * Test validateCustomerInfo method
     */
    @isTest
    static void testValidateCustomerInfo() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        Test.startTest();
        Map<String, Object> result = BusinessRuleValidatorController.validateCustomerInfo(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assert(result.containsKey('isValid'), 'Result should contain isValid key');
    }
    
    /**
     * Test null/blank input handling
     */
    @isTest
    static void testNullInputHandling() {
        Test.startTest();
        
        // Test null inputs
        BusinessRuleValidatorController.BusinessRuleEvaluation result1 = 
            BusinessRuleValidatorController.evaluateBusinessRules(null);
        System.assertNotEquals(null, result1, 'Should handle null input gracefully');
        
        Boolean result2 = BusinessRuleValidatorController.isPurchaseOrderRequired('');
        System.assertEquals(false, result2, 'Should return false for blank input');
        
        Test.stopTest();
    }
}