objects/Account_Title__c.object
<CustomObject>
    <description>This object is repository to hold titles</description>
    <label>Account Title</label>
    <nameField>
        <label>Account Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Title</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <errorMessage>Please select title which are available on contact&apos;s account.</errorMessage>
            <filterItems>
                <field>Account_Title__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Account_Title__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Title__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Department__c.object
<CustomObject>
    <description>This object is being used for storing departments</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactContextGetter.cls
public class ContactContextGetter {

    /* The purpose of the contact context getter is to retrieve data related to contacts only.  
     * These methods should not perform complex mutations or calculations, and should only exist 
     * to retrieve data related to the contact structure
	*/
    
    //Getter methods for account
    //Method 1 - Return Contact records.
    public static Map<Id, Contact> getContactById(Set<Id> idSet) {

        //Call the universal query utility while limiting on the basis of Id (constraint)
        List<Contact> contactList = (List<Contact>) UniversalQueryUtility.universalQuery('Contact', idSet, 'Id');
        Map<Id, Contact> contactCache = new Map<Id, Contact>();
        contactCache.putAll(contactList);
        
        return contactCache;
    }
    
    //Additional getter methods, while these could be standalone getters on their own classes they are 
    //explicit to the contact object and cannot exist without them, so we will include those queries on this
    //getter class
    
    //Method 2 - Return Department name for contacts based on Department Id
    public static Map<Id, Department__c> getDepartmentById(Set<Id> idSet) {

        //Call the universal query utility while limiting on the basis of Id (constraint)
        List<Department__c> departmentList = (List<Department__c>) UniversalQueryUtility.universalQuery('Department__c', idSet, 'Id');
        Map<Id, Department__c> departmentCache = new Map<Id, Department__c>();
        departmentCache.putAll(departmentList);
        
        return departmentCache;
    }
    
    //Method 3 - Return Title name for contacts based on Title Id
    public static Map<Id, Account_Title__c> getTitleById(Set<Id> idSet) {

        //Call the universal query utility while limiting on the basis of Id (constraint)
        List<Account_Title__c> titleList = (List<Account_Title__c>) UniversalQueryUtility.universalQuery('Account_Title__c', idSet, 'Id');
        Map<Id, Account_Title__c> titleCache = new Map<Id, Account_Title__c>();
        titleCache.putAll(titleList);
        
        return titleCache;
    }
    
}