objects/Account.object
<CustomObject>
    <fields>
        <fullName>FacilityCode__c</fullName>
        <description>To Store Facility Code.</description>
        <label>FacilityCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Business_Unit__c</fullName>
        <description>Denotes which WM BU the vendor operates under</description>
        <label>Vendor BU</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ByPassMASServiceChange__c.field-meta.xml
<CustomField>
    <fullName>ByPassMASServiceChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassMASServiceChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/BypassPriceReview__c.field-meta.xml
<CustomField>
    <fullName>BypassPriceReview__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassPriceReview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DoNotCreateMASTicket__c.field-meta.xml
<CustomField>
    <fullName>DoNotCreateMASTicket__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DoNotCreateMASTicket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DoNotCreateTaskGridTickets__c.field-meta.xml
<CustomField>
    <fullName>DoNotCreateTaskGridTickets__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field was added for the story SDT-29392</description>
    <label>DoNotCreateTaskGridTickets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASAccount__c.field-meta.xml
<CustomField>
    <fullName>MASAccount__c</fullName>
    <label>MASAccount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASBox__c.field-meta.xml
<CustomField>
    <fullName>MASBox__c</fullName>
    <label>MASBox</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASCompany__c.field-meta.xml
<CustomField>
    <fullName>MASCompany__c</fullName>
    <label>MASCompany</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASCustomerUniqueId__c.field-meta.xml
<CustomField>
    <fullName>MASCustomerUniqueId__c</fullName>
    <label>MASCustomerUniqueId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASLibrary__c.field-meta.xml
<CustomField>
    <fullName>MASLibrary__c</fullName>
    <inlineHelpText>MAS Library must begin with &quot;ARDTA.&quot; followed by the library name. Example: ARDTA.268</inlineHelpText>
    <label>MASLibrary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MASServiceLine__c.field-meta.xml
<CustomField>
    <fullName>MASServiceLine__c</fullName>
    <label>MASServiceLine</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SetupComment__c.field-meta.xml
<CustomField>
    <fullName>SetupComment__c</fullName>
    <description>Updated Datatype and Size for Story SDT-25787</description>
    <label>SetupComment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/VCRCode__c.field-meta.xml
<CustomField>
    <fullName>VCRCode__c</fullName>
    <label>VCRCode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACQ</fullName>
                <label>New Business Acquisition</label>
            </value>
            <value>
                <fullName>NBT</fullName>
                <label>New Business Temporary</label>
            </value>
            <value>
                <fullName>NBC</fullName>
                <label>New Business Competition</label>
            </value>
            <value>
                <fullName>NRI</fullName>
                <label>New Business Reinstate</label>
            </value>
            <value>
                <fullName>NBG</fullName>
                <label>New Business Greenfield</label>
            </value>
            <value>
                <fullName>NBW</fullName>
                <label>New Business New Waste Stream</label>
            </value>
            <value>
                <fullName>DIV</fullName>
                <label>Lost Business Divestiture</label>
            </value>
            <value>
                <fullName>LCL</fullName>
                <label>Lost Closed Business</label>
            </value>
            <value>
                <fullName>LCP</fullName>
                <label>Lost Business Competition</label>
            </value>
            <value>
                <fullName>LBP</fullName>
                <label>Lost Bad Pay</label>
            </value>
            <value>
                <fullName>LBT</fullName>
                <label>Lost Business Temporary Service</label>
            </value>
            <value>
                <fullName>LOP</fullName>
                <label>Lost Business Cancellation</label>
            </value>
            <value>
                <fullName>LBW</fullName>
                <label>Lost Business Waste Stream</label>
            </value>
            <value>
                <fullName>INP</fullName>
                <label>Increase in Permanent or Temporary Service</label>
            </value>
            <value>
                <fullName>INL</fullName>
                <label>Increase in Seasonal Service</label>
            </value>
            <value>
                <fullName>ISS</fullName>
                <label>Increase in Snapshot Service</label>
            </value>
            <value>
                <fullName>IPI</fullName>
                <label>Increase in price: individually secured price increase</label>
            </value>
            <value>
                <fullName>IFE</fullName>
                <label>Increase in price due to fuel, environmental (EVF), and/or Regulatory Cost Recovery (RCR).</label>
            </value>
            <value>
                <fullName>DIS</fullName>
                <label>Decrease in Service</label>
            </value>
            <value>
                <fullName>DIL</fullName>
                <label>Decrease in Seasonal Service</label>
            </value>
            <value>
                <fullName>RBP</fullName>
                <label>Price decrease due to price increase roll back</label>
            </value>
            <value>
                <fullName>RFE</fullName>
                <label>Price decrease due to fuel, environmental (EVF), and/or Regulatory Cost Recovery (RCR).</label>
            </value>
            <value>
                <fullName>NOW</fullName>
                <label>New Ownership</label>
            </value>
            <value>
                <fullName>LOW</fullName>
                <label>Lost Ownership</label>
            </value>
            <value>
                <fullName>NSC</fullName>
                <label>New Service Type</label>
            </value>
            <value>
                <fullName>LSC</fullName>
                <label>Lost Service Type</label>
            </value>
            <value>
                <fullName>NBL</fullName>
                <label>New Business Location Move</label>
            </value>
            <value>
                <fullName>LNL</fullName>
                <label>Lost Due to Location Move</label>
            </value>
            <value>
                <fullName>CID</fullName>
                <label>Commission ID change</label>
            </value>
            <value>
                <fullName>CRL</fullName>
                <label>Contract renewal change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payable entity related to this quote line</description>
    <inlineHelpText>The payable vendor related to this quote line.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/QuoteProcurementMASService.cls
/**
 * @description QuoteProcurementMASService - MAS (Management Automation System) operations layer
 *
 * This service handles all MAS-related operations including MAS detail retrieval,
 * validation, and updates for QuoteLines. It consolidates MAS library/company code
 * management and VCR code handling.
 *
 * Key Responsibilities:
 * - MAS detail retrieval by facility code and business unit
 * - MAS field updates for QuoteLine bundles
 * - Bypass price review determination
 * - VCR code validation
 *
 * @author Waste Management
 * @date 2025
 * @group Service Layer - MAS Operations
 */
public with sharing class QuoteProcurementMASService {

    // ========================================================================
    // PUBLIC API - MAS DETAIL RETRIEVAL
    // ========================================================================

    /**
     * @description Get MAS details for a QuoteLine
     * Refactored from: returnUniqueMASDetails() in QuoteProcurementController
     * @param quoteLineId The QuoteLine ID
     * @return List<AggregateResult> MAS details
     */
    @AuraEnabled
    public static List<AggregateResult> getMASDetailsForQuoteLine(Id quoteLineId) {
        SBQQ__QuoteLine__c parentLine = QuoteProcurementContextGetter.getQuoteLineMASDetails(quoteLineId);

        if (parentLine == null) {
            return new List<AggregateResult>();
        }

        Boolean newServiceCase = (parentLine.SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.RecordType.Name ==
                                 Constant_Util.New_Service_Case);
        String lineOfBusiness = getLineOfBusiness(parentLine.SBQQ__Product__r.Family);
        String facilityCode = parentLine.Vendor__r.FacilityCode__c;
        String businessUnit = parentLine.Vendor__r.Vendor_Business_Unit__c;

        List<AggregateResult> masDetails = new List<AggregateResult>();

        // Try facility code first
        if (String.isNotBlank(facilityCode)) {
            masDetails = QuoteProcurementContextGetter.getMASDetailsByFacility(
                facilityCode,
                lineOfBusiness,
                newServiceCase
            );
        }

        // Fallback to business unit
        if (masDetails.isEmpty() && String.isNotBlank(businessUnit)) {
            masDetails = QuoteProcurementContextGetter.getMASDetailsByBusinessUnit(
                businessUnit,
                lineOfBusiness
            );
        }

        return masDetails;
    }

    /**
     * @description Get MAS wrapper for a QuoteLine
     * Refactored from: getMasDetails() in QuoteProcurementController
     * @param quoteLineId The QuoteLine ID
     * @return MASWrapper MAS details wrapper
     */
    @AuraEnabled
    public static MASWrapper getMASWrapper(Id quoteLineId) {
        MASWrapper masWrapper = new MASWrapper();
        SBQQ__QuoteLine__c parentLine = QuoteProcurementContextGetter.getQuoteLineMASDetails(quoteLineId);

        if (parentLine != null) {
            masWrapper.MASLibrary = parentLine.MASLibrary__c;
            masWrapper.MASCompany = parentLine.MASCompany__c;
            masWrapper.MASAccount = parentLine.MASAccount__c;
            masWrapper.MASUniqueId = parentLine.MASCustomerUniqueId__c;
            masWrapper.MASServiceLine = parentLine.MASServiceLine__c;
            masWrapper.MASBox = parentLine.MASBox__c;
            masWrapper.MASComment = parentLine.SetupComment__c;
            masWrapper.MASBypassPrice = parentLine.BypassPriceReview__c;
            masWrapper.MASDoNotCreate = parentLine.DoNotCreateMASTicket__c;
            masWrapper.DoNotCreateTaskGridTickets = parentLine.DoNotCreateTaskGridTickets__c;
            masWrapper.VCRCode = parentLine.VCRCode__c;

            // Show checkbox for non-new service cases
            if (parentLine.SBQQ__Quote__r.SBQQ__Opportunity2__r.Case__r.RecordType.Name !=
                Constant_Util.New_Service_Case) {
                masWrapper.IsDoNotCreateTaskGridTicketVisible = true;
            }

            masWrapper.MASCommentSize = Schema.SObjectType.SBQQ__QuoteLine__c.fields.SetupComment__c.getLength();
        }

        return masWrapper;
    }

    // ========================================================================
    // PUBLIC API - MAS UPDATES
    // ========================================================================

    /**
     * @description Update MAS details for a QuoteLine bundle
     * Refactored from: writeMASDetails() in QuoteProcurementController
     * @param parentQuoteLineId The parent QuoteLine ID
     * @param masData MAS data wrapper
     * @return MASResponseWrapper Response with success/error info
     */
    @AuraEnabled
    public static MASResponseWrapper updateMASDetails(Id parentQuoteLineId, MASWrapper masData) {
        MASResponseWrapper response = new MASResponseWrapper();

        try {
            List<SBQQ__QuoteLine__c> quoteLines = [
                SELECT Id, MASLibrary__c, MASCompany__c, MASAccount__c, MASCustomerUniqueId__c,
                       MASServiceLine__c, MASBox__c, BypassPriceReview__c, BypassMASServiceChange__c,
                       SetupComment__c, DoNotCreateMASTicket__c, DoNotCreateTaskGridTickets__c,
                       VCRCode__c
                FROM SBQQ__QuoteLine__c
                WHERE Id = :parentQuoteLineId
                      OR SBQQ__RequiredBy__c = :parentQuoteLineId
                      OR SBQQ__RequiredBy__r.SBQQ__RequiredBy__c = :parentQuoteLineId
            ];

            for (SBQQ__QuoteLine__c quoteLine : quoteLines) {
                if (String.isNotBlank(masData.MASLibrary)) {
                    quoteLine.MASLibrary__c = masData.MASLibrary;
                }
                if (String.isNotBlank(masData.MASCompany)) {
                    quoteLine.MASCompany__c = masData.MASCompany;
                }
                if (masData.MASAccount != null) {
                    quoteLine.MASAccount__c = masData.MASAccount;
                }
                if (masData.MASUniqueId != null) {
                    quoteLine.MASCustomerUniqueId__c = masData.MASUniqueId;
                }
                if (masData.MASServiceLine != null) {
                    quoteLine.MASServiceLine__c = masData.MASServiceLine;
                }
                if (String.isNotBlank(masData.MASBox)) {
                    quoteLine.MASBox__c = masData.MASBox;
                }
                if (String.isNotBlank(masData.MASComment)) {
                    quoteLine.SetupComment__c = masData.MASComment;
                }
                quoteLine.BypassPriceReview__c = masData.MASBypassPrice;
                quoteLine.DoNotCreateMASTicket__c = masData.MASDoNotCreate;
                quoteLine.DoNotCreateTaskGridTickets__c = masData.DoNotCreateTaskGridTickets;
                if (String.isNotBlank(masData.VCRCode)) {
                    quoteLine.VCRCode__c = masData.VCRCode;
                }
            }

            // Use DML Service for field-level security check
            QuoteProcurementDMLService dmlService = QuoteProcurementDMLService.getInstance();
            QuoteProcurementDMLService.DMLResult result = dmlService.updateQuoteLines(quoteLines);

            response.IsSuccess = result.isSuccess;
            response.ErrorMessage = result.isSuccess ? '' : result.message;

        } catch (Exception ex) {
            response.IsSuccess = false;
            response.ErrorMessage = ex.getMessage();
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.ERROR_APPLICATION,
                LoggingLevel.ERROR
            );
        }

        return response;
    }

    // ========================================================================
    // PUBLIC API - BYPASS PRICE REVIEW
    // ========================================================================

    /**
     * @description Determine if price review should be bypassed
     * Delegates to BusinessRuleService
     * @param quoteLineId The QuoteLine ID
     * @param masLibrary The MAS Library code
     * @return Boolean True if bypass enabled
     */
    @AuraEnabled
    public static Boolean shouldBypassPriceReview(Id quoteLineId, String masLibrary) {
        return QuoteProcurementBusinessRuleService.shouldBypassPriceReview(quoteLineId, masLibrary);
    }

    // ========================================================================
    // PRIVATE HELPER METHODS
    // ========================================================================

    /**
     * @description Get MAS line of business from product family
     * @param productFamily The product family
     * @return String Line of business code
     */
    private static String getLineOfBusiness(String productFamily) {
        if (productFamily == Constant_Util.ROLLOFF) {
            return 'O';
        } else if (productFamily == Constant_Util.COMMERCIAL) {
            return 'C';
        }
        return null;
    }

    // ========================================================================
    // INNER CLASSES
    // ========================================================================

    /**
     * @description Wrapper for MAS details
     */
    public class MASWrapper {
        @AuraEnabled public String MASLibrary {get; set;}
        @AuraEnabled public String MASCompany {get; set;}
        @AuraEnabled public Decimal MASAccount {get; set;}
        @AuraEnabled public Decimal MASUniqueId {get; set;}
        @AuraEnabled public Decimal MASServiceLine {get; set;}
        @AuraEnabled public String MASBox {get; set;}
        @AuraEnabled public String MASComment {get; set;}
        @AuraEnabled public Boolean MASBypassPrice {get; set;}
        @AuraEnabled public Boolean MASDoNotCreate {get; set;}
        @AuraEnabled public Boolean DoNotCreateTaskGridTickets {get; set;}
        @AuraEnabled public Boolean IsDoNotCreateTaskGridTicketVisible {get; set;}
        @AuraEnabled public String VCRCode {get; set;}
        @AuraEnabled public Integer MASCommentSize {get; set;}
    }

    /**
     * @description Wrapper for MAS update response
     */
    public class MASResponseWrapper {
        @AuraEnabled public Boolean IsSuccess {get; set;}
        @AuraEnabled public String ErrorMessage {get; set;}
    }
}