objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Position__c.object
<CustomObject>
    <description>Service Container Positions for Location</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Positions</relationshipLabel>
        <relationshipName>Account_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Container_Position__c</fullName>
        <description>Position at location where container is located</description>
        <label>Container Position</label>
        <type>TextArea</type>
    </fields>
    <label>Account Position</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/QuoteProcurementPositionServiceTest.cls
/**
 * @description Test class for QuoteProcurementPositionService
 * @author Waste Management
 * @date 2025
 */
@isTest
private class QuoteProcurementPositionServiceTest {

    @testSetup
    static void setupTestData() {
        Account locationAccount = TestDataFactoryRefactored.createAccount('Location', 'Location');
        insert locationAccount;

        Product2 product = TestDataFactoryRefactored.createProduct('Rolloff');
        insert product;

        Account clientAccount = TestDataFactoryRefactored.createAccount('Client', 'Client');
        insert clientAccount;

        Opportunity opp = TestDataFactoryRefactored.createOpportunity(clientAccount.Id);
        insert opp;

        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__Account__c = locationAccount.Id
        );
        insert quote;

        SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = quote.Id,
            SBQQ__Product__c = product.Id,
            SBQQ__Quantity__c = 1
        );
        insert quoteLine;
    }

    @isTest
    static void testCreateOnsitePosition_Success() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Test.startTest();
        String result = QuoteProcurementPositionService.createOnsitePosition(
            locationAccount.Id,
            'New Onsite Position'
        );
        Test.stopTest();

        System.assertEquals('Success', result, 'Position creation should succeed');

        List<Account_Position__c> positions = [SELECT Id FROM Account_Position__c
                                              WHERE AccountId__c = :locationAccount.Id
                                              AND Container_Position__c = 'New Onsite Position'];
        System.assertEquals(1, positions.size(), 'Position should be created');
    }

    @isTest
    static void testCreateOnsitePosition_Duplicate() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Account_Position__c existingPosition = new Account_Position__c(
            AccountId__c = locationAccount.Id,
            Container_Position__c = 'Duplicate Position'
        );
        insert existingPosition;

        Test.startTest();
        String result = QuoteProcurementPositionService.createOnsitePosition(
            locationAccount.Id,
            'Duplicate Position'
        );
        Test.stopTest();

        System.assertEquals('Duplicate', result, 'Should return duplicate error');
    }

    @isTest
    static void testCreateOffsitePosition_Success() {
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Test.startTest();
        String result = QuoteProcurementPositionService.createOffsitePosition(
            locationAccount.Id,
            'Offsite Test',
            '123 Test St',
            'Test City',
            'CA',
            '90210'
        );
        Test.stopTest();

        System.assertEquals('Success', result, 'Offsite position creation should succeed');
    }

    @isTest
    static void testGetQuoteLinePositions() {
        SBQQ__QuoteLine__c quoteLine = [SELECT Id FROM SBQQ__QuoteLine__c LIMIT 1];

        Test.startTest();
        List<SBQQ__QuoteLine__c> result =
            QuoteProcurementPositionService.getQuoteLinePositions(quoteLine.Id);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Should return quoteline positions');
    }
}