objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <formula>TEXT(Product2.Equipment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Equipment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Extra_Pickup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates when scheduled server has On-Call Extra Pickup defined</description>
        <label>Has XPU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <formula>OR((End_Date__c + 14)&gt;=today(),ISNULL(End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Core_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Core Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Occurrence_Type__c</fullName>
        <label>Occurrence Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>On-Call</fullName>
                </value>
                <value>
                    <fullName>Scheduled On-Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Header_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to Link Service Detail to Service Header, will be populated with the same values as ParentID. Needed for SDG_Enhanced Grids</description>
        <label>Service Header ID</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Service_Request</fullName>
        <active>true</active>
        <description>A record type to capture requested asset changes or new assets</description>
        <label>Service Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <description>Type of container/equipment if this is an equipment to align with Acorn values for container type</description>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Container_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBS_Case_Asset__c.object
<CustomObject>
    <description>Join between Cases and their 1 or more Assets (Service Details)</description>
    <fields>
        <fullName>AssetId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Asset.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Detail</value>
            </filterItems>
            <filterItems>
                <field>Asset.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Asset_Header__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Case Assets</relationshipLabel>
        <relationshipName>Case_Assets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Header</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Asset.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Header</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Case Assets (Asset Header)</relationshipLabel>
        <relationshipName>Case_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseId__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Assets</relationshipLabel>
        <relationshipName>Case_Assets1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>AssetId__r.End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>AssetId__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Case Asset</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Case Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <customValue>
        <fullName>Location</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Recycling</fullName>
        <isActive>false</isActive>
        <label>Recycling</label>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Container_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bagster Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Baler - Horizontal</fullName>
    </customValue>
    <customValue>
        <fullName>Baler - Mini</fullName>
    </customValue>
    <customValue>
        <fullName>Baler - Vertical</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bladder</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>Cart Dumper - Stand Alone</fullName>
    </customValue>
    <customValue>
        <fullName>Carts</fullName>
    </customValue>
    <customValue>
        <fullName>Catwalk</fullName>
    </customValue>
    <customValue>
        <fullName>Client Owned</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Appartment Style</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Box Only</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Breakaway</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Dewatering</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - DRC</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Enclosure</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Integrated Cart Dumper</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Pacman</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Pac Tainer</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Pre-crusher</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - RUNI</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Self-Contained</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Self Contained East</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Tank/Stubby</fullName>
    </customValue>
    <masterLabel>Container Type</masterLabel>
</GlobalValueSet>

classes/CaseAssetValidatorTest.cls
/**
 * @description Comprehensive test class for CaseAssetValidator
 *
 * This test class provides complete coverage for the CaseAssetValidator service,
 * testing all validation methods, case asset management, and helper functions.
 *
 * Coverage Target: 85%+
 *
 * @author Waste Management
 * @date 2025
 * @group Test Classes
 */
@isTest
private class CaseAssetValidatorTest {

    @testSetup
    static void setupTestData() {
        // Create full test hierarchy
        Map<String, Object> testData = TestDataFactoryRefactored.createFullTestHierarchy();

        Account locationAccount = (Account)testData.get('locationAccount');
        Product2 prod = (Product2)testData.get('product');

        // Update product to have Equipment Type
        prod.Equipment_Type__c = 'Container';
        update prod;

        // Create Commercial Scheduled asset with proper hierarchy
        Asset commercialScheduled = new Asset(
            Name = 'Commercial Scheduled Asset',
            AccountId = locationAccount.Id,
            Product2Id = prod.Id,
            Status = 'Installed',
            ProductFamily = 'Commercial',
            Occurrence_Type__c = 'Scheduled',
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            Is_Active__c = true,
            Service_Header_Id__c = null // Will be set to own ID after insert
        );
        insert commercialScheduled;

        commercialScheduled.Service_Header_Id__c = commercialScheduled.Id;
        update commercialScheduled;

        // Create child pickup service (scheduled with XPU)
        Asset childPickupScheduled = new Asset(
            Name = 'Scheduled Pickup with XPU',
            AccountId = locationAccount.Id,
            ParentId = commercialScheduled.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Pickup',
            Occurrence_Type__c = 'Scheduled',
            Has_Extra_Pickup__c = true,
            Is_Core_Service__c = true,
            Is_Active__c = true,
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            ProductFamily = 'Commercial',
            Service_Header_Id__c = commercialScheduled.Id
        );
        insert childPickupScheduled;

        // Create Commercial On-Call asset
        Asset commercialOnCall = new Asset(
            Name = 'Commercial OnCall Asset',
            AccountId = locationAccount.Id,
            Product2Id = prod.Id,
            Status = 'Installed',
            ProductFamily = 'Commercial',
            Occurrence_Type__c = 'On-Call',
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            Is_Active__c = true,
            Service_Header_Id__c = null
        );
        insert commercialOnCall;

        commercialOnCall.Service_Header_Id__c = commercialOnCall.Id;
        update commercialOnCall;

        // Create child on-call pickup service
        Asset childPickupOnCall = new Asset(
            Name = 'OnCall Pickup',
            AccountId = locationAccount.Id,
            ParentId = commercialOnCall.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Pickup',
            Occurrence_Type__c = 'On-Call',
            Has_Extra_Pickup__c = false,
            Is_Core_Service__c = true,
            Is_Active__c = true,
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            ProductFamily = 'Commercial',
            Service_Header_Id__c = commercialOnCall.Id
        );
        insert childPickupOnCall;

        // Create Rolloff asset with children
        Asset rolloffAsset = new Asset(
            Name = 'Rolloff Asset',
            AccountId = locationAccount.Id,
            Product2Id = prod.Id,
            Status = 'Installed',
            ProductFamily = 'Rolloff',
            Occurrence_Type__c = 'On-Call',
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            Is_Active__c = true,
            Service_Header_Id__c = null
        );
        insert rolloffAsset;

        rolloffAsset.Service_Header_Id__c = rolloffAsset.Id;
        update rolloffAsset;

        // Create rolloff child assets
        List<Asset> rolloffChildren = new List<Asset>();

        // Core disposal service
        rolloffChildren.add(new Asset(
            Name = 'Disposal Service',
            AccountId = locationAccount.Id,
            ParentId = rolloffAsset.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Disposal',
            Is_Core_Service__c = true,
            Is_Active__c = true,
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            ProductFamily = 'Rolloff',
            Service_Header_Id__c = rolloffAsset.Id
        ));

        // Recycling service
        rolloffChildren.add(new Asset(
            Name = 'Recycling Service',
            AccountId = locationAccount.Id,
            ParentId = rolloffAsset.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Recycling',
            Is_Core_Service__c = false,
            Is_Active__c = true,
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            ProductFamily = 'Rolloff',
            Service_Header_Id__c = rolloffAsset.Id
        ));

        insert rolloffChildren;

        // Create Services asset
        Asset servicesAsset = new Asset(
            Name = 'Services Asset',
            AccountId = locationAccount.Id,
            Product2Id = prod.Id,
            Status = 'Installed',
            ProductFamily = 'Services',
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            Is_Active__c = true,
            Service_Header_Id__c = null
        );
        insert servicesAsset;

        servicesAsset.Service_Header_Id__c = servicesAsset.Id;
        update servicesAsset;

        // Create services child assets
        Asset bulkService = new Asset(
            Name = 'Bulk Service',
            AccountId = locationAccount.Id,
            ParentId = servicesAsset.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Bulk',
            Is_Active__c = true,
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(365),
            ProductFamily = 'Services',
            Service_Header_Id__c = servicesAsset.Id
        );
        insert bulkService;

        // Create expired asset for testing date validation
        Asset expiredAsset = new Asset(
            Name = 'Expired Asset',
            AccountId = locationAccount.Id,
            Product2Id = prod.Id,
            Status = 'Installed',
            ProductFamily = 'Commercial',
            Occurrence_Type__c = 'Scheduled',
            Start_Date__c = Date.today().addDays(-365),
            End_Date__c = Date.today().addDays(-1),
            Is_Active__c = false,
            Service_Header_Id__c = null
        );
        insert expiredAsset;

        // Create case with SBS_Case_Asset__c relationships
        Case testCase = (Case)testData.get('case');
        Asset mainAsset = (Asset)testData.get('asset');

        SBS_Case_Asset__c caseAsset = new SBS_Case_Asset__c(
            CaseId__c = testCase.Id,
            AssetId__c = mainAsset.Id,
            Asset_Header__c = mainAsset.Id
        );
        insert caseAsset;
    }

    // ========================================================================
    // VALIDATE PICKUP ASSET - COMMERCIAL SCHEDULED TESTS
    // ========================================================================

    @isTest
    static void testValidatePickupAsset_CommercialScheduled_Success() {
        Asset commercialAsset = [SELECT Id FROM Asset WHERE Name = 'Commercial Scheduled Asset' LIMIT 1];
        Date serviceDate = Date.today().addDays(7);

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(commercialAsset.Id, serviceDate);
        Test.stopTest();

        System.assertEquals(true, result.isValid, 'Commercial scheduled should be valid');
        System.assertEquals('COMMERCIAL', result.validationType, 'Should validate as commercial');
    }

    @isTest
    static void testValidatePickupAsset_CommercialScheduled_NoXPU() {
        // Create commercial asset without XPU child
        Account loc = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];

        Asset noXPUAsset = new Asset(
            Name = 'No XPU Asset',
            AccountId = loc.Id,
            Product2Id = prod.Id,
            ProductFamily = 'Commercial',
            Occurrence_Type__c = 'Scheduled',
            Start_Date__c = Date.today().addDays(-30),
            Is_Active__c = true
        );
        insert noXPUAsset;

        // Add child without XPU
        Asset childNoXPU = new Asset(
            Name = 'No XPU Child',
            AccountId = loc.Id,
            ParentId = noXPUAsset.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Pickup',
            Occurrence_Type__c = 'Scheduled',
            Has_Extra_Pickup__c = false,
            Is_Core_Service__c = true,
            Is_Active__c = true,
            Start_Date__c = Date.today().addDays(-30),
            ProductFamily = 'Commercial'
        );
        insert childNoXPU;

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(noXPUAsset.Id, Date.today().addDays(7));
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should fail without XPU component');
        System.assert(result.errorMessage.contains('Extra Pickup'), 'Error should mention XPU');
    }

    @isTest
    static void testValidatePickupAsset_CommercialScheduled_NoCoreService() {
        Account loc = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];

        Asset noCoreAsset = new Asset(
            Name = 'No Core Service Asset',
            AccountId = loc.Id,
            Product2Id = prod.Id,
            ProductFamily = 'Commercial',
            Occurrence_Type__c = 'Scheduled',
            Start_Date__c = Date.today().addDays(-30),
            Is_Active__c = true
        );
        insert noCoreAsset;

        // Add child that is not core service
        Asset childNotCore = new Asset(
            Name = 'Not Core Child',
            AccountId = loc.Id,
            ParentId = noCoreAsset.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Pickup',
            Occurrence_Type__c = 'Scheduled',
            Has_Extra_Pickup__c = true,
            Is_Core_Service__c = false,
            Is_Active__c = false,
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(-1),
            ProductFamily = 'Commercial'
        );
        insert childNotCore;

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(noCoreAsset.Id, Date.today().addDays(7));
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should fail without active core service');
    }

    // ========================================================================
    // VALIDATE PICKUP ASSET - COMMERCIAL ON-CALL TESTS
    // ========================================================================

    @isTest
    static void testValidatePickupAsset_CommercialOnCall_Success() {
        Asset onCallAsset = [SELECT Id FROM Asset WHERE Name = 'Commercial OnCall Asset' LIMIT 1];
        Date serviceDate = Date.today().addDays(7);

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(onCallAsset.Id, serviceDate);
        Test.stopTest();

        System.assertEquals(true, result.isValid, 'On-call asset should be valid');
    }

    @isTest
    static void testValidatePickupAsset_CommercialOnCall_MultiplePickups() {
        Account loc = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];

        Asset multiPickup = new Asset(
            Name = 'Multi Pickup Asset',
            AccountId = loc.Id,
            Product2Id = prod.Id,
            ProductFamily = 'Commercial',
            Occurrence_Type__c = 'On-Call',
            Start_Date__c = Date.today().addDays(-30),
            Is_Active__c = true
        );
        insert multiPickup;

        // Add multiple on-call pickup children
        List<Asset> children = new List<Asset>();
        for (Integer i = 0; i < 2; i++) {
            children.add(new Asset(
                Name = 'OnCall Pickup ' + i,
                AccountId = loc.Id,
                ParentId = multiPickup.Id,
                Product2Id = prod.Id,
                Service_Type__c = 'Pickup',
                Occurrence_Type__c = 'On-Call',
                Has_Extra_Pickup__c = false,
                Is_Core_Service__c = true,
                Is_Active__c = true,
                Start_Date__c = Date.today().addDays(-30),
                ProductFamily = 'Commercial'
            ));
        }
        insert children;

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(multiPickup.Id, Date.today().addDays(7));
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should fail with multiple on-call pickups');
        System.assert(result.errorMessage.contains('corrupted'), 'Error should mention corruption');
    }

    // ========================================================================
    // VALIDATE PICKUP ASSET - ROLLOFF TESTS
    // ========================================================================

    @isTest
    static void testValidatePickupAsset_Rolloff_WithCoreService() {
        Asset rolloffAsset = [SELECT Id FROM Asset WHERE ProductFamily = 'Rolloff' LIMIT 1];
        Date serviceDate = Date.today().addDays(7);

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(rolloffAsset.Id, serviceDate);
        Test.stopTest();

        System.assertEquals(true, result.isValid, 'Rolloff with core service should be valid');
        System.assertEquals('ROLLOFF', result.validationType, 'Type should be ROLLOFF');
    }

    @isTest
    static void testValidatePickupAsset_Rolloff_NoActiveComponents() {
        Account loc = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];

        Asset rolloffNoCore = new Asset(
            Name = 'Rolloff No Core',
            AccountId = loc.Id,
            Product2Id = prod.Id,
            ProductFamily = 'Rolloff',
            Start_Date__c = Date.today().addDays(-30),
            Is_Active__c = true
        );
        insert rolloffNoCore;

        // Add expired child
        Asset expiredChild = new Asset(
            Name = 'Expired Disposal',
            AccountId = loc.Id,
            ParentId = rolloffNoCore.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Disposal',
            Is_Core_Service__c = true,
            Is_Active__c = false,
            Start_Date__c = Date.today().addDays(-365),
            End_Date__c = Date.today().addDays(-1),
            ProductFamily = 'Rolloff'
        );
        insert expiredChild;

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(rolloffNoCore.Id, Date.today().addDays(7));
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should fail without active components');
    }

    @isTest
    static void testValidatePickupAsset_AssetNotActive() {
        Asset expiredAsset = [SELECT Id FROM Asset WHERE Name = 'Expired Asset' LIMIT 1];

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(expiredAsset.Id, Date.today());
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Expired asset should be invalid');
        System.assert(result.errorMessage.contains('not active'), 'Error should mention inactive');
    }

    // ========================================================================
    // VALIDATE PICKUP ASSET - EDGE CASES
    // ========================================================================

    @isTest
    static void testValidatePickupAsset_NullAsset() {
        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(null, Date.today());
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should be invalid for null asset');
        System.assert(result.errorMessage.contains('required'), 'Error should mention required');
    }

    @isTest
    static void testValidatePickupAsset_NullServiceDate() {
        Asset testAsset = [SELECT Id FROM Asset LIMIT 1];

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(testAsset.Id, null);
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should be invalid for null service date');
    }

    @isTest
    static void testValidatePickupAsset_InvalidAssetId() {
        Id fakeAssetId = '02i000000000000AAA';

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validatePickupAsset(fakeAssetId, Date.today());
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should be invalid for non-existent asset');
    }

    // ========================================================================
    // VALIDATE NON-PICKUP ASSET TESTS
    // ========================================================================

    @isTest
    static void testValidateNonPickupAsset_Success() {
        Asset commercialAsset = [SELECT Id FROM Asset WHERE Name = 'Commercial Scheduled Asset' LIMIT 1];
        Date serviceDate = Date.today().addDays(7);

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validateNonPickupAsset(commercialAsset.Id, serviceDate);
        Test.stopTest();

        System.assertEquals(true, result.isValid, 'Should be valid with active children');
        System.assertEquals('NON_PICKUP', result.validationType, 'Type should be NON_PICKUP');
    }

    @isTest
    static void testValidateNonPickupAsset_NoActiveChildren() {
        Account loc = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];

        Asset noActiveChildren = new Asset(
            Name = 'No Active Children',
            AccountId = loc.Id,
            Product2Id = prod.Id,
            ProductFamily = 'Commercial',
            Start_Date__c = Date.today().addDays(-30),
            Is_Active__c = true
        );
        insert noActiveChildren;

        // Add expired child
        Asset expiredChild = new Asset(
            Name = 'Expired Child',
            AccountId = loc.Id,
            ParentId = noActiveChildren.Id,
            Product2Id = prod.Id,
            Service_Type__c = 'Pickup',
            Is_Active__c = false,
            Start_Date__c = Date.today().addDays(-365),
            End_Date__c = Date.today().addDays(-1),
            ProductFamily = 'Commercial'
        );
        insert expiredChild;

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validateNonPickupAsset(noActiveChildren.Id, Date.today().addDays(7));
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should fail without active children');
        System.assert(result.errorMessage.contains('end date'), 'Error should mention end dates');
    }

    @isTest
    static void testValidateNonPickupAsset_NullInputs() {
        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validateNonPickupAsset(null, null);
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should be invalid for null inputs');
    }

    // ========================================================================
    // VALIDATE CASE ASSETS TESTS
    // ========================================================================

    @isTest
    static void testValidateCaseAssets_Success() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validateCaseAssets(testCase.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals('CASE_ASSETS', result.validationType, 'Type should be CASE_ASSETS');
    }

    @isTest
    static void testValidateCaseAssets_NullCaseId() {
        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validateCaseAssets(null);
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should be invalid for null case ID');
        System.assert(result.errorMessage.contains('required'), 'Error should mention required');
    }

    @isTest
    static void testValidateCaseAssets_NoCaseAssets() {
        // Create a case without case assets
        Case newCase = TestDataFactoryRefactored.createCase('Service_Request');
        insert newCase;

        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            CaseAssetValidator.validateCaseAssets(newCase.Id);
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'Should be invalid with no case assets');
    }

    // ========================================================================
    // REMOVE OBSOLETE ASSET LINKS TESTS
    // ========================================================================

    @isTest
    static void testRemoveObsoleteAssetLinks_Success() {
        Case testCase = [SELECT Id, AssetId FROM Case WHERE AssetId != null LIMIT 1];
        Map<String, String> oldCaseAssetMap = new Map<String, String>();
        oldCaseAssetMap.put(testCase.Id, testCase.AssetId);

        Test.startTest();
        CaseAssetValidator.removeObsoleteAssetLinks(oldCaseAssetMap);
        Test.stopTest();

        System.assert(true, 'Method should execute without errors');
    }

    @isTest
    static void testRemoveObsoleteAssetLinks_EmptyMap() {
        Test.startTest();
        CaseAssetValidator.removeObsoleteAssetLinks(new Map<String, String>());
        Test.stopTest();

        System.assert(true, 'Should handle empty map gracefully');
    }

    // ========================================================================
    // CREATE CASE ASSET RELATIONSHIPS TESTS
    // ========================================================================

    @isTest
    static void testCreateCaseAssetRelationships_Insert() {
        Case newCase = TestDataFactoryRefactored.createCase('Service_Request');
        Asset testAsset = [SELECT Id, Service_Header_Id__c, Service_Type__c, Is_Active__c, ProductFamily, Start_Date__c, End_Date__c
                          FROM Asset WHERE Name = 'Commercial Scheduled Asset' LIMIT 1];
        newCase.AssetId = testAsset.Id;
        newCase.Service_Date__c = Date.today().addDays(7);
        insert newCase;

        Map<Id, Case> caseMap = new Map<Id, Case>{newCase.Id => newCase};
        Map<Id, Asset> assetMap = new Map<Id, Asset>{testAsset.Id => testAsset};

        Test.startTest();
        CaseAssetValidator.createCaseAssetRelationships(caseMap, null, assetMap);
        Test.stopTest();

        System.assert(true, 'Method should execute without errors');
    }

    @isTest
    static void testCreateCaseAssetRelationships_Update() {
        Case testCase = [SELECT Id, AssetId, Service_Date__c FROM Case WHERE AssetId != null LIMIT 1];
        Case oldCase = testCase.clone(true, true, true, true);

        // Change asset
        Asset newAsset = [SELECT Id, Service_Header_Id__c, Service_Type__c, Is_Active__c, ProductFamily, Start_Date__c, End_Date__c
                         FROM Asset WHERE Id != :testCase.AssetId LIMIT 1];
        testCase.AssetId = newAsset.Id;

        Map<Id, Case> newCaseMap = new Map<Id, Case>{testCase.Id => testCase};
        Map<Id, Case> oldCaseMap = new Map<Id, Case>{oldCase.Id => oldCase};
        Map<Id, Asset> assetMap = new Map<Id, Asset>{newAsset.Id => newAsset};

        Test.startTest();
        CaseAssetValidator.createCaseAssetRelationships(newCaseMap, oldCaseMap, assetMap);
        Test.stopTest();

        System.assert(true, 'Should handle update scenario');
    }

    // ========================================================================
    // MARK DUPLICATE SERVICE DATE CASES TESTS
    // ========================================================================

    @isTest
    static void testMarkDuplicateServiceDateCases_NoDuplicates() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();
        CaseAssetValidator.markDuplicateServiceDateCases(caseMap);
        Test.stopTest();

        System.assert(true, 'Method should execute without errors');
    }

    @isTest
    static void testMarkDuplicateServiceDateCases_EmptyMap() {
        Test.startTest();
        CaseAssetValidator.markDuplicateServiceDateCases(new Map<Id, Case>());
        Test.stopTest();

        System.assert(true, 'Should handle empty map gracefully');
    }

    // ========================================================================
    // IS PARENT CASE WITHIN TIME WINDOW TESTS
    // ========================================================================

    @isTest
    static void testIsParentCaseWithinTimeWindow_NoParent() {
        Case testCase = [SELECT Id FROM Case WHERE ParentId = null LIMIT 1];

        Test.startTest();
        Boolean result = CaseAssetValidator.isParentCaseWithinTimeWindow(testCase.Id, 15);
        Test.stopTest();

        System.assertEquals(false, result, 'Should return false for case without parent');
    }

    @isTest
    static void testIsParentCaseWithinTimeWindow_NullCaseId() {
        Test.startTest();
        Boolean result = CaseAssetValidator.isParentCaseWithinTimeWindow(null, 15);
        Test.stopTest();

        System.assertEquals(false, result, 'Should return false for null case ID');
    }

    @isTest
    static void testIsParentCaseWithinTimeWindow_WithParent() {
        // Create parent and child case
        Case parentCase = TestDataFactoryRefactored.createCase('Service_Request');
        insert parentCase;

        Case childCase = TestDataFactoryRefactored.createCase('Service_Request');
        childCase.ParentId = parentCase.Id;
        insert childCase;

        Test.startTest();
        Boolean result = CaseAssetValidator.isParentCaseWithinTimeWindow(childCase.Id, 15);
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
    }

    // ========================================================================
    // VALIDATE CLOSED CASE EDITS TESTS
    // ========================================================================

    @isTest
    static void testValidateClosedCaseEdits() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Map<Id, Case> caseMap = new Map<Id, Case>{testCase.Id => testCase};

        Test.startTest();
        CaseAssetValidator.validateClosedCaseEdits(caseMap);
        Test.stopTest();

        System.assert(true, 'Method should execute without errors');
    }

    // ========================================================================
    // SHOULD RESET SLA TESTS
    // ========================================================================

    @isTest
    static void testShouldResetSLA_TypeChanged() {
        Case oldCase = TestDataFactoryRefactored.createCase('Service_Request');
        oldCase.Case_Type__c = 'Pickup';

        Case newCase = oldCase.clone(false, false, false, false);
        newCase.Case_Type__c = 'Delivery';

        Test.startTest();
        Boolean result = CaseAssetValidator.shouldResetSLA(newCase, oldCase);
        Test.stopTest();

        System.assertEquals(true, result, 'Should reset SLA when case type changes');
    }

    @isTest
    static void testShouldResetSLA_SubTypeChanged() {
        Case oldCase = TestDataFactoryRefactored.createCase('Service_Request');
        oldCase.Case_Sub_Type__c = 'Extra Pickup';

        Case newCase = oldCase.clone(false, false, false, false);
        newCase.Case_Sub_Type__c = 'Delivery';

        Test.startTest();
        Boolean result = CaseAssetValidator.shouldResetSLA(newCase, oldCase);
        Test.stopTest();

        System.assertEquals(true, result, 'Should reset SLA when subtype changes');
    }

    @isTest
    static void testShouldResetSLA_LocationChanged() {
        Account loc1 = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Account loc2 = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' AND Id != :loc1.Id LIMIT 1];

        Case oldCase = TestDataFactoryRefactored.createCase('Service_Request');
        oldCase.Location__c = loc1.Id;

        Case newCase = oldCase.clone(false, false, false, false);
        newCase.Location__c = loc2.Id;

        Test.startTest();
        Boolean result = CaseAssetValidator.shouldResetSLA(newCase, oldCase);
        Test.stopTest();

        System.assertEquals(true, result, 'Should reset SLA when location changes');
    }

    @isTest
    static void testShouldResetSLA_AssetChanged() {
        Asset asset1 = [SELECT Id FROM Asset LIMIT 1];
        Asset asset2 = [SELECT Id FROM Asset WHERE Id != :asset1.Id LIMIT 1];

        Case oldCase = TestDataFactoryRefactored.createCase('Service_Request');
        oldCase.AssetId = asset1.Id;

        Case newCase = oldCase.clone(false, false, false, false);
        newCase.AssetId = asset2.Id;

        Test.startTest();
        Boolean result = CaseAssetValidator.shouldResetSLA(newCase, oldCase);
        Test.stopTest();

        System.assertEquals(true, result, 'Should reset SLA when asset changes');
    }

    @isTest
    static void testShouldResetSLA_NoChanges() {
        Case oldCase = TestDataFactoryRefactored.createCase('Service_Request');
        Case newCase = oldCase.clone(false, false, false, false);

        Test.startTest();
        Boolean result = CaseAssetValidator.shouldResetSLA(newCase, oldCase);
        Test.stopTest();

        System.assertEquals(false, result, 'Should not reset SLA when nothing changes');
    }

    // ========================================================================
    // IDENTIFY ROL ASSETS THAT AFFECT SUBTYPE TESTS
    // ========================================================================

    @isTest
    static void testIdentifyROLAssetsThatAffectSubtype() {
        Asset rolloffAsset = [SELECT Id, Product2.Family FROM Asset WHERE ProductFamily = 'Rolloff' LIMIT 1];
        Map<Id, Asset> assetMap = new Map<Id, Asset>{rolloffAsset.Id => rolloffAsset};

        Test.startTest();
        Set<Id> result = CaseAssetValidator.identifyROLAssetsThatAffectSubtype(assetMap);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result should not be null');
    }

    @isTest
    static void testIdentifyROLAssetsThatAffectSubtype_EmptyMap() {
        Test.startTest();
        Set<Id> result = CaseAssetValidator.identifyROLAssetsThatAffectSubtype(new Map<Id, Asset>());
        Test.stopTest();

        System.assertEquals(0, result.size(), 'Should return empty set for empty map');
    }

    // ========================================================================
    // VALIDATE PICKUP ASSETS (BULK) TESTS
    // ========================================================================

    @isTest
    static void testValidatePickupAssets_BulkSuccess() {
        List<Asset> assets = [SELECT Id FROM Asset LIMIT 3];
        Map<Id, Date> assetParam = new Map<Id, Date>();
        for (Asset a : assets) {
            assetParam.put(a.Id, Date.today().addDays(7));
        }

        Test.startTest();
        Map<Id, String> results = CaseAssetValidator.validatePickupAssets(assetParam);
        Test.stopTest();

        System.assertEquals(assets.size(), results.size(), 'Should return result for each asset');
    }

    @isTest
    static void testValidatePickupAssets_NullMap() {
        Test.startTest();
        Map<Id, String> results = CaseAssetValidator.validatePickupAssets(null);
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty map for null input');
    }

    @isTest
    static void testValidatePickupAssets_EmptyMap() {
        Test.startTest();
        Map<Id, String> results = CaseAssetValidator.validatePickupAssets(new Map<Id, Date>());
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty map for empty input');
    }

    // ========================================================================
    // VALIDATE NON-PICKUP ASSETS (BULK) TESTS
    // ========================================================================

    @isTest
    static void testValidateNonPickupAssets_BulkSuccess() {
        List<Asset> assets = [SELECT Id FROM Asset LIMIT 3];
        Map<Id, Date> assetParam = new Map<Id, Date>();
        for (Asset a : assets) {
            assetParam.put(a.Id, Date.today().addDays(7));
        }

        Test.startTest();
        Map<Id, String> results = CaseAssetValidator.validateNonPickupAssets(assetParam);
        Test.stopTest();

        System.assertEquals(assets.size(), results.size(), 'Should return result for each asset');
    }

    @isTest
    static void testValidateNonPickupAssets_NullMap() {
        Test.startTest();
        Map<Id, String> results = CaseAssetValidator.validateNonPickupAssets(null);
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty map for null input');
    }

    @isTest
    static void testValidateNonPickupAssets_EmptyMap() {
        Test.startTest();
        Map<Id, String> results = CaseAssetValidator.validateNonPickupAssets(new Map<Id, Date>());
        Test.stopTest();

        System.assertEquals(0, results.size(), 'Should return empty map for empty input');
    }

    // ========================================================================
    // VALIDATION RESULT WRAPPER TESTS
    // ========================================================================

    @isTest
    static void testValidationResult_Constructor() {
        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            new CaseAssetValidator.ValidationResult(true, 'Test message', 'TEST_TYPE');
        Test.stopTest();

        System.assertEquals(true, result.isValid, 'isValid should be true');
        System.assertEquals('Test message', result.errorMessage, 'Error message should match');
        System.assertEquals('TEST_TYPE', result.validationType, 'Validation type should match');
    }

    @isTest
    static void testValidationResult_InvalidCase() {
        Test.startTest();
        CaseAssetValidator.ValidationResult result =
            new CaseAssetValidator.ValidationResult(false, 'Validation failed', 'ERROR');
        Test.stopTest();

        System.assertEquals(false, result.isValid, 'isValid should be false');
        System.assertNotEquals(null, result.errorMessage, 'Error message should be populated');
    }
}