objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service_Request</fullName>
        <active>true</active>
        <description>A record type to capture requested asset changes or new assets</description>
        <label>Service Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Status__c</fullName>
        <description>Captures the sub-status for a Case State</description>
        <label>Case Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Inbound Interaction</fullName>
                </value>
                <value>
                    <fullName>Pending Customer Information</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Procurement</fullName>
                </value>
                <value>
                    <fullName>Pending Cost Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Request Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Price Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Quote Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Information</fullName>
                </value>
                <value>
                    <fullName>Pending Service Integration</fullName>
                </value>
                <value>
                    <fullName>Pending Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Manual Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pending Service Confirmation</fullName>
                </value>
                <value>
                    <fullName>Service Not Performed</fullName>
                </value>
                <value>
                    <fullName>Service Confirmed</fullName>
                </value>
                <value>
                    <fullName>Service Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Request Not Approved</fullName>
                </value>
                <value>
                    <fullName>Request Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Follow Up</fullName>
                </value>
                <value>
                    <fullName>Pending Service Issue Resolution</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Recovery</fullName>
                </value>
                <value>
                    <fullName>Pending Recovery Confirmation</fullName>
                </value>
                <value>
                    <fullName>Status Provided</fullName>
                </value>
                <value>
                    <fullName>Status Not Provided</fullName>
                </value>
                <value>
                    <fullName>Recovery Scheduled</fullName>
                </value>
                <value>
                    <fullName>Recovery Not Performed</fullName>
                </value>
                <value>
                    <fullName>Recovery Confirmed</fullName>
                </value>
                <value>
                    <fullName>Integration Error</fullName>
                </value>
                <value>
                    <fullName>Request Closed</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chargeable__c</fullName>
        <label>Chargeable</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Client for this Case</description>
        <label>Client Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Client Name)</relationshipLabel>
        <relationshipName>Cases_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Close_Irrelevant_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>This field contains the parent case number</description>
        <label>Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>Site Survey, A Ticket has been created in Acorn and needs to be viewed in Salesforce</description>
        <label>Standard Case</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Location Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CaseTriggerHandlerTest.cls
/**
 * @description Test class for CaseTriggerHandler
 *
 * This test class provides coverage for the CaseTriggerHandler,
 * which orchestrates all Case trigger operations.
 *
 * Coverage Target: 75%+
 *
 * @author Waste Management
 * @date 2025
 * @group Test Classes
 */
@isTest
private class CaseTriggerHandlerTest {

    // ========================================================================
    // TEST SETUP
    // ========================================================================

    @testSetup
    static void setupTestData() {
        // Create Code Switch setting
        TestDataFactory.createProcessBuilderTOFlow();

        // Create full test hierarchy
        TestDataFactory.createFullTestHierarchy();
    }

    // ========================================================================
    // BEFORE INSERT TESTS
    // ========================================================================

    @isTest
    static void testBeforeInsert_BasicCase() {
        // Given: Test data exists
        Account clientAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Client' LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Asset testAsset = [SELECT Id FROM Asset LIMIT 1];

        Test.startTest();

        // When: Inserting a new case
        Case testCase = TestDataFactory.createCaseWithRelationships(
            clientAccount.Id,
            locationAccount.Id,
            testContact.Id,
            testAsset.Id,
            'Service_Request'
        );
        testCase.Status = 'New';
        insert testCase;

        Test.stopTest();

        // Then: Case is inserted successfully with proper field values
        Case result = [SELECT Id, Status, Reference_Number__c FROM Case WHERE Id = :testCase.Id];
        System.assertNotEquals(null, result, 'Case should be inserted');
        System.assertEquals('New', result.Status, 'Status should be New');
    }

    @isTest
    static void testBeforeInsert_ClosedPickupCase() {
        // Given: A closed pickup case
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Test.startTest();

        // When: Inserting a closed pickup case
        Case testCase = TestDataFactory.createCase('Service_Request');
        testCase.Status = 'Closed';
        testCase.Case_type__c = 'Pickup';
        testCase.Location__c = locationAccount.Id;
        insert testCase;

        Test.stopTest();

        // Then: Sub-status is auto-populated
        Case result = [SELECT Id, Case_Sub_Status__c FROM Case WHERE Id = :testCase.Id];
        System.assertNotEquals(null, result.Case_Sub_Status__c, 'Sub-status should be populated');
    }

    // ========================================================================
    // BEFORE UPDATE TESTS
    // ========================================================================

    @isTest
    static void testBeforeUpdate_StatusChange() {
        // Given: An existing case
        Case testCase = [SELECT Id, Status FROM Case LIMIT 1];
        String originalStatus = testCase.Status;

        Test.startTest();

        // When: Updating case status
        testCase.Status = 'Open';
        update testCase;

        Test.stopTest();

        // Then: Case is updated
        Case result = [SELECT Id, Status FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Open', result.Status, 'Status should be updated');
    }

    @isTest
    static void testBeforeUpdate_CloseIrrelevantCase() {
        // Given: A case with Close_Irrelevant_Case__c flag
        Case testCase = [SELECT Id, Status, Close_Irrelevant_Case__c FROM Case LIMIT 1];

        Test.startTest();

        // When: Setting close irrelevant flag
        testCase.Close_Irrelevant_Case__c = true;
        update testCase;

        Test.stopTest();

        // Then: Case is auto-closed
        Case result = [SELECT Id, Status FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Closed', result.Status, 'Case should be auto-closed');
    }

    // ========================================================================
    // AFTER INSERT TESTS
    // ========================================================================

    @isTest
    static void testAfterInsert_CaseCreation() {
        // Given: Test data for new case
        Account clientAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Client' LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        Test.startTest();

        // When: Creating a new case
        Case testCase = TestDataFactory.createCase('Service_Request');
        testCase.Client__c = clientAccount.Id;
        testCase.Location__c = locationAccount.Id;
        testCase.Chargeable__c = 'Yes';
        insert testCase;

        Test.stopTest();

        // Then: Case is created successfully
        Case result = [SELECT Id, Chargeable__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Yes', result.Chargeable__c, 'Chargeable field should be set');
    }

    // ========================================================================
    // AFTER UPDATE TESTS
    // ========================================================================

    @isTest
    static void testAfterUpdate_CaseUpdate() {
        // Given: An existing case
        Case testCase = [SELECT Id, Chargeable__c FROM Case LIMIT 1];

        Test.startTest();

        // When: Updating case
        testCase.Chargeable__c = 'No';
        update testCase;

        Test.stopTest();

        // Then: Case is updated
        Case result = [SELECT Id, Chargeable__c FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('No', result.Chargeable__c, 'Chargeable should be updated');
    }

    // ========================================================================
    // HELPER METHOD TESTS
    // ========================================================================

    @isTest
    static void testGetAssetRecordValue() {
        // Given: An asset exists
        Asset testAsset = [SELECT Id FROM Asset LIMIT 1];
        Set<Id> assetIds = new Set<Id>{testAsset.Id};

        Test.startTest();

        // When: Getting asset record
        Map<Id, Asset> results = CaseTriggerHandler.getAssetRecordValue(assetIds, true);

        Test.stopTest();

        // Then: Asset is returned
        System.assertNotEquals(null, results, 'Results should not be null');
        System.assert(results.containsKey(testAsset.Id), 'Should contain asset');
    }

    @isTest
    static void testGetLocationRecordValue() {
        // Given: A location account exists
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];
        Set<Id> locationIds = new Set<Id>{locationAccount.Id};

        Test.startTest();

        // When: Getting location record
        Map<Id, Account> results = CaseTriggerHandler.getLocationRecordValue(locationIds);

        Test.stopTest();

        // Then: Location is returned
        System.assertNotEquals(null, results, 'Results should not be null');
        System.assert(results.containsKey(locationAccount.Id), 'Should contain location');
    }

    @isTest
    static void testGetLocationRecordValueStandardCase() {
        Test.startTest();

        // When: Getting standard case location
        Map<Id, Account> results = CaseTriggerHandler.getLocationRecordValueStandardCase();

        Test.stopTest();

        // Then: Query executes without error
        System.assertNotEquals(null, results, 'Results should not be null');
    }

    // ========================================================================
    // BULK OPERATIONS TESTS
    // ========================================================================

    @isTest
    static void testBulkInsert_MultipleCases() {
        // Given: Test data for multiple cases
        Account clientAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Client' LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Location' LIMIT 1];

        List<Case> casesToInsert = new List<Case>();
        for (Integer i = 0; i < 10; i++) {
            Case c = TestDataFactory.createCase('Service_Request');
            c.Client__c = clientAccount.Id;
            c.Location__c = locationAccount.Id;
            c.Subject = 'Bulk Test Case ' + i;
            casesToInsert.add(c);
        }

        Test.startTest();

        // When: Inserting multiple cases
        insert casesToInsert;

        Test.stopTest();

        // Then: All cases are inserted
        List<Case> results = [SELECT Id FROM Case WHERE Id IN :casesToInsert];
        System.assertEquals(10, results.size(), 'All cases should be inserted');
    }

    @isTest
    static void testBulkUpdate_MultipleCases() {
        // Given: Multiple existing cases
        List<Case> testCases = [SELECT Id, Status FROM Case LIMIT 5];

        Test.startTest();

        // When: Updating multiple cases
        for (Case c : testCases) {
            c.Status = 'Open';
        }
        update testCases;

        Test.stopTest();

        // Then: All cases are updated
        List<Case> results = [SELECT Id, Status FROM Case WHERE Id IN :testCases];
        for (Case c : results) {
            System.assertEquals('Open', c.Status, 'Status should be Open');
        }
    }

    // ========================================================================
    // ERROR HANDLING TESTS
    // ========================================================================

    @isTest
    static void testGetAssetRecordValue_EmptySet() {
        Test.startTest();

        // When: Getting asset with empty set
        Map<Id, Asset> results = CaseTriggerHandler.getAssetRecordValue(new Set<Id>(), true);

        Test.stopTest();

        // Then: Empty map is returned
        System.assertNotEquals(null, results, 'Results should not be null');
        System.assertEquals(0, results.size(), 'Empty map should be returned');
    }

    @isTest
    static void testGetAssetRecordValue_NullSet() {
        Test.startTest();

        // When: Getting asset with null set
        Map<Id, Asset> results = CaseTriggerHandler.getAssetRecordValue(null, true);

        Test.stopTest();

        // Then: Empty map is returned
        System.assertNotEquals(null, results, 'Results should not be null');
        System.assertEquals(0, results.size(), 'Empty map should be returned for null');
    }
}