objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Records</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Service Location Records</description>
        <label>Location</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor Record Type (to replace the Supplier record type)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <description>Exception Reason on Service in Acorn.</description>
        <label>Exception Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Schedule</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Vendor Acquisition</fullName>
                </value>
                <value>
                    <fullName>Client Initiated Change</fullName>
                </value>
                <value>
                    <fullName>Oakleaf Initiated Change</fullName>
                </value>
                <value>
                    <fullName>Vendor Initiated Change</fullName>
                </value>
                <value>
                    <fullName>Retire Payable Exception</fullName>
                </value>
                <value>
                    <fullName>Cancel Payable Exception</fullName>
                </value>
                <value>
                    <fullName>Un-Retire Payable Exception</fullName>
                </value>
                <value>
                    <fullName>WO Component Cancelllation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Client for this Case</description>
        <label>Client Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Client Name)</relationshipLabel>
        <relationshipName>Cases_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>This field contains the parent case number</description>
        <label>Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Work_Order_Instructions__c</fullName>
        <description>Work Order instructions for the case captured from the flow</description>
        <label>System Work Order Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Acorn_WorkOrder_Number__c</fullName>
        <label>Acorn WorkOrder Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <formula>Text(Case.Case_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders (Client Name)</relationshipLabel>
        <relationshipName>Work_Orders_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. - Customer Location</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders (Customer Location)</relationshipLabel>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dispatch_Email__c</fullName>
        <label>Dispatch Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dry_Run_Cost__c</fullName>
        <label>Dry Run Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dry_Run_Cost_in_Currency__c</fullName>
        <label>Dry Run Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Dry_Run_Price__c</fullName>
        <label>Dry Run Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dry_Run_Price_in_Currency__c</fullName>
        <label>Dry Run Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Dry_Run_Root_Cause__c</fullName>
        <label>Dry Run Root Cause</label>
        <length>60000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Description__c</fullName>
        <label>Cancellation Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <label>Cancellation Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked Can</fullName>
                </value>
                <value>
                    <fullName>Client&apos;s Request</fullName>
                </value>
                <value>
                    <fullName>Contamination</fullName>
                </value>
                <value>
                    <fullName>Dry Run</fullName>
                </value>
                <value>
                    <fullName>Duplicate Request</fullName>
                </value>
                <value>
                    <fullName>Equipment Issues</fullName>
                </value>
                <value>
                    <fullName>Schedule Change - Client</fullName>
                </value>
                <value>
                    <fullName>Schedule Change - Vendor</fullName>
                </value>
                <value>
                    <fullName>Weather Conditions</fullName>
                </value>
                <value>
                    <fullName>Vendor did not perform service</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Incorrect Service</fullName>
                </value>
                <value>
                    <fullName>Incorrect Service Date</fullName>
                </value>
                <value>
                    <fullName>Incorrect Hauler</fullName>
                </value>
                <value>
                    <fullName>Incorrect Work-Order Description</fullName>
                </value>
                <value>
                    <fullName>Incorrect Amount</fullName>
                </value>
                <value>
                    <fullName>Work Order Cleanup</fullName>
                </value>
                <value>
                    <fullName>Incorrect Container Selected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Instructions__c</fullName>
        <label>Work Order Instructions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Resend</fullName>
                </value>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Dry Run</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor_Account_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. - Vendor Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Service_Status__c</fullName>
        <label>Vendor Service Status</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/WorkOrderTriggerHandlerTest.cls
/*************************************************************
@Name: WorkOrderTriggerHandlerTest
@Author: Claude AI
@CreateDate: 12/01/2025
@Description: Comprehensive test class for WorkOrderTriggerHandler
@Coverage: WorkOrderTriggerHandler
**************************************************************/
@isTest
private class WorkOrderTriggerHandlerTest {

    @testSetup
    static void setupTestData() {
        // Create test account (Client)
        Account clientAccount = new Account(
            Name = 'Test Client Account'
        );
        insert clientAccount;

        // Create location account
        Account locationAccount = new Account(
            Name = 'Test Location Account',
            ParentId = clientAccount.Id,
            ShippingCountry = 'USA',
            ShippingCity = 'Test City',
            ShippingStreet = '123 Test St',
            ShippingState = 'CA',
            ShippingPostalCode = '12345'
        );
        insert locationAccount;

        // Create vendor account
        Account vendorAccount = new Account(
            Name = 'Test Vendor Account'
        );
        insert vendorAccount;

        // Create contact for vendor
        Contact vendorContact = new Contact(
            FirstName = 'Vendor',
            LastName = 'Contact',
            Email = 'vendor@example.com',
            AccountId = vendorAccount.Id
        );
        insert vendorContact;

        // Create AccountContactRelation with Dispatch role
        List<AccountContactRelation> acrList = [SELECT Id FROM AccountContactRelation
                                                 WHERE AccountId = :vendorAccount.Id
                                                 AND ContactId = :vendorContact.Id LIMIT 1];
        if (!acrList.isEmpty()) {
            acrList[0].Roles = 'Dispatch';
            update acrList[0];
        }

        // Create test contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'test@example.com',
            AccountId = locationAccount.Id
        );
        insert testContact;

        // Create test asset
        Asset testAsset = new Asset(
            Name = 'Test Asset',
            AccountId = locationAccount.Id,
            ContactId = testContact.Id
        );
        insert testAsset;

        // Create test case
        Case testCase = new Case(
            Subject = 'Test Case for WorkOrder',
            Status = 'Open',
            Origin = 'Web',
            AccountId = locationAccount.Id,
            ContactId = testContact.Id,
            AssetId = testAsset.Id,
            Case_Type__c = 'Service',
            Service_Date__c = System.today().addDays(7),
            Work_Order_Instructions__c = 'Test instructions for work order',
            Reference_Number__c = '12345'
        );
        insert testCase;
    }

    @isTest
    static void testBeforeInsert() {
        Case testCase = [SELECT Id, Work_Order_Instructions__c, ContactId FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        Test.startTest();

        // Create WorkOrder
        WorkOrder newWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'New',
            Subject = 'Test Work Order'
        );
        insert newWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was inserted with instructions from Case
        WorkOrder insertedWO = [SELECT Id, Instructions__c, ContactId, Client__c
                                FROM WorkOrder WHERE Id = :newWorkOrder.Id];
        System.assertEquals(testCase.Work_Order_Instructions__c, insertedWO.Instructions__c,
                          'Instructions should match Case');
        System.assertEquals(testCase.ContactId, insertedWO.ContactId,
                          'ContactId should match Case');
        System.assertNotEquals(null, insertedWO.Client__c, 'Client should be populated');
    }

    @isTest
    static void testBeforeInsertWithoutCase() {
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        Test.startTest();

        // Create WorkOrder without Case
        WorkOrder newWorkOrder = new WorkOrder(
            Customer_Location__c = locationAccount.Id,
            Status = 'New',
            Subject = 'Test Work Order No Case'
        );
        insert newWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was inserted
        WorkOrder insertedWO = [SELECT Id, Client__c FROM WorkOrder WHERE Id = :newWorkOrder.Id];
        System.assertNotEquals(null, insertedWO.Client__c, 'Client should be populated from location');
    }

    @isTest
    static void testBeforeUpdate() {
        Case testCase = [SELECT Id, Work_Order_Instructions__c FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];
        Account vendorAccount = [SELECT Id FROM Account WHERE Name = 'Test Vendor Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'New',
            Subject = 'Test Work Order Update'
        );
        insert testWorkOrder;

        Test.startTest();

        // Update WorkOrder
        testWorkOrder.Status = 'Sent';
        testWorkOrder.Vendor_Account_Id__c = vendorAccount.Id;
        testWorkOrder.Service_Date__c = System.today().addDays(10);
        update testWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was updated
        WorkOrder updatedWO = [SELECT Id, Status, Vendor_Account_Id__c FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals('Sent', updatedWO.Status);
        System.assertEquals(vendorAccount.Id, updatedWO.Vendor_Account_Id__c);
    }

    @isTest
    static void testBeforeUpdateIntegrationStatus() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'Sent',
            Subject = 'Test Integration Status'
        );
        insert testWorkOrder;

        Test.startTest();

        // Reset bypass flag
        RecurrsiveTriggerHandler.bypassValidation = false;

        // Update fields that should trigger Integration_Status__c = 'Update'
        testWorkOrder.Service_Date__c = System.today().addDays(15);
        testWorkOrder.Instructions__c = 'Updated instructions';
        update testWorkOrder;

        Test.stopTest();

        // Verify Integration Status was set
        WorkOrder updatedWO = [SELECT Id, Integration_Status__c FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals('Update', updatedWO.Integration_Status__c);
    }

    @isTest
    static void testAfterInsert() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];
        Account vendorAccount = [SELECT Id FROM Account WHERE Name = 'Test Vendor Account' LIMIT 1];

        Test.startTest();

        // Create WorkOrder with Acorn number
        WorkOrder newWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Vendor_Account_Id__c = vendorAccount.Id,
            Status = 'New',
            Subject = 'Test After Insert',
            Acorn_WorkOrder_Number__c = 'ACORN-12345'
        );
        insert newWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was inserted
        WorkOrder insertedWO = [SELECT Id, Acorn_WorkOrder_Number__c FROM WorkOrder WHERE Id = :newWorkOrder.Id];
        System.assertEquals('ACORN-12345', insertedWO.Acorn_WorkOrder_Number__c);
    }

    @isTest
    static void testAfterUpdate() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];
        Account vendorAccount = [SELECT Id FROM Account WHERE Name = 'Test Vendor Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Vendor_Account_Id__c = vendorAccount.Id,
            Status = 'New',
            Subject = 'Test After Update'
        );
        insert testWorkOrder;

        Test.startTest();

        // Update WorkOrder status
        testWorkOrder.Status = 'Work Complete';
        update testWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was updated
        WorkOrder updatedWO = [SELECT Id, Status FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals('Work Complete', updatedWO.Status);
    }

    @isTest
    static void testAfterUpdateVendorStatusChange() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];
        Account vendorAccount = [SELECT Id FROM Account WHERE Name = 'Test Vendor Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Vendor_Account_Id__c = vendorAccount.Id,
            Status = 'Sent',
            Subject = 'Test Vendor Status',
            Vendor_Service_Status__c = 'Pending'
        );
        insert testWorkOrder;

        Test.startTest();

        // Update vendor status
        testWorkOrder.Vendor_Service_Status__c = 'Confirmed - Positive';
        update testWorkOrder;

        Test.stopTest();

        // Verify vendor status was updated
        WorkOrder updatedWO = [SELECT Id, Vendor_Service_Status__c FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals('Confirmed - Positive', updatedWO.Vendor_Service_Status__c);
    }

    @isTest
    static void testAfterUpdateServiceDateChange() {
        Case testCase = [SELECT Id, Service_Date__c FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'Sent',
            Subject = 'Test Service Date Change',
            Service_Date__c = System.today().addDays(7)
        );
        insert testWorkOrder;

        Test.startTest();

        // Update service date
        testWorkOrder.Service_Date__c = System.today().addDays(14);
        update testWorkOrder;

        Test.stopTest();

        // Verify service date was updated
        WorkOrder updatedWO = [SELECT Id, Service_Date__c FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals(System.today().addDays(14), updatedWO.Service_Date__c);
    }

    @isTest
    static void testAfterUpdateCancellation() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'Sent',
            Subject = 'Test Cancellation'
        );
        insert testWorkOrder;

        Test.startTest();

        // Cancel WorkOrder
        testWorkOrder.Status = 'Cancelled';
        testWorkOrder.Exception_Reason__c = 'Test Reason';
        testWorkOrder.Exception_Description__c = 'Test Description';
        update testWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was cancelled
        WorkOrder updatedWO = [SELECT Id, Status, Exception_Reason__c FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals('Cancelled', updatedWO.Status);
        System.assertEquals('Test Reason', updatedWO.Exception_Reason__c);
    }

    @isTest
    static void testAfterUpdateRejection() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'Sent',
            Subject = 'Test Rejection'
        );
        insert testWorkOrder;

        Test.startTest();

        // Reject WorkOrder
        testWorkOrder.Status = 'Rejected';
        update testWorkOrder;

        Test.stopTest();

        // Verify WorkOrder was rejected
        WorkOrder updatedWO = [SELECT Id, Status FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals('Rejected', updatedWO.Status);
    }

    @isTest
    static void testUpdateDispatchEmail() {
        Account vendorAccount = [SELECT Id FROM Account WHERE Name = 'Test Vendor Account' LIMIT 1];
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        Test.startTest();

        // Create WorkOrder with vendor
        WorkOrder newWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Vendor_Account_Id__c = vendorAccount.Id,
            Status = 'New',
            Subject = 'Test Dispatch Email'
        );
        insert newWorkOrder;

        Test.stopTest();

        // Verify dispatch email was populated
        WorkOrder insertedWO = [SELECT Id, Dispatch_Email__c FROM WorkOrder WHERE Id = :newWorkOrder.Id];
        System.assertNotEquals(null, insertedWO.Dispatch_Email__c, 'Dispatch email should be populated');
    }

    @isTest
    static void testUpdateDryRunDetail() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Insert WorkOrder
        WorkOrder testWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'New',
            Subject = 'Test Dry Run',
            Dry_Run_Cost__c = 100.00,
            Dry_Run_Price__c = 150.00
        );
        insert testWorkOrder;

        Test.startTest();

        // Update Dry Run details
        testWorkOrder.Dry_Run_Cost__c = 120.00;
        testWorkOrder.Dry_Run_Price__c = 180.00;
        testWorkOrder.Dry_Run_Root_Cause__c = 'Test Root Cause';
        update testWorkOrder;

        Test.stopTest();

        // Verify Dry Run details were updated
        WorkOrder updatedWO = [SELECT Id, Dry_Run_Cost__c, Dry_Run_Price__c,
                               Dry_Run_Cost_in_Currency__c, Dry_Run_Price_in_Currency__c
                               FROM WorkOrder WHERE Id = :testWorkOrder.Id];
        System.assertEquals(120.00, updatedWO.Dry_Run_Cost__c);
        System.assertEquals(120.00, updatedWO.Dry_Run_Cost_in_Currency__c);
    }

    @isTest
    static void testBulkInsert() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        Test.startTest();

        // Create 200 work orders
        List<WorkOrder> bulkWorkOrders = new List<WorkOrder>();
        for (Integer i = 0; i < 200; i++) {
            bulkWorkOrders.add(new WorkOrder(
                CaseId = testCase.Id,
                Customer_Location__c = locationAccount.Id,
                Status = 'New',
                Subject = 'Bulk Work Order ' + i
            ));
        }
        insert bulkWorkOrders;

        Test.stopTest();

        // Verify all work orders were inserted
        List<WorkOrder> insertedWOs = [SELECT Id FROM WorkOrder WHERE Subject LIKE 'Bulk Work Order%'];
        System.assertEquals(200, insertedWOs.size(), 'All work orders should be inserted');
    }

    @isTest
    static void testBulkUpdate() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Create work orders
        List<WorkOrder> bulkWorkOrders = new List<WorkOrder>();
        for (Integer i = 0; i < 200; i++) {
            bulkWorkOrders.add(new WorkOrder(
                CaseId = testCase.Id,
                Customer_Location__c = locationAccount.Id,
                Status = 'New',
                Subject = 'Bulk Update WO ' + i
            ));
        }
        insert bulkWorkOrders;

        Test.startTest();

        // Update all work orders
        for (WorkOrder wo : bulkWorkOrders) {
            wo.Status = 'Sent';
        }
        update bulkWorkOrders;

        Test.stopTest();

        // Verify all work orders were updated
        List<WorkOrder> updatedWOs = [SELECT Id, Status FROM WorkOrder WHERE Subject LIKE 'Bulk Update WO%'];
        System.assertEquals(200, updatedWOs.size());
        for (WorkOrder wo : updatedWOs) {
            System.assertEquals('Sent', wo.Status);
        }
    }

    @isTest
    static void testSkipTriggerFlag() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];

        // Set skip trigger flag
        Constant_UTIL.skipWOTrigger = true;

        Test.startTest();

        // Create WorkOrder with flag set
        WorkOrder newWorkOrder = new WorkOrder(
            CaseId = testCase.Id,
            Customer_Location__c = locationAccount.Id,
            Status = 'New',
            Subject = 'Test Skip Trigger'
        );
        insert newWorkOrder;

        // Update with flag set
        newWorkOrder.Status = 'Sent';
        update newWorkOrder;

        Test.stopTest();

        // Reset flag
        Constant_UTIL.skipWOTrigger = false;

        // Verify operations completed
        WorkOrder finalWO = [SELECT Id, Status FROM WorkOrder WHERE Id = :newWorkOrder.Id];
        System.assertEquals('Sent', finalWO.Status);
    }

    @isTest
    static void testGetCaseDetails() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Set<Id> caseIdSet = new Set<Id>{testCase.Id};

        Test.startTest();

        Map<Id, Case> caseMap = WorkOrderTriggerHandler.getCaseDetails(caseIdSet);

        Test.stopTest();

        System.assertNotEquals(null, caseMap, 'Case map should not be null');
        System.assertEquals(1, caseMap.size(), 'Case map should contain one case');
        System.assert(caseMap.containsKey(testCase.Id), 'Case map should contain test case');
    }

    @isTest
    static void testGetAccountDetails() {
        Account locationAccount = [SELECT Id FROM Account WHERE Name = 'Test Location Account' LIMIT 1];
        Set<Id> accountIdSet = new Set<Id>{locationAccount.Id};

        Test.startTest();

        Map<Id, Account> accountMap = WorkOrderTriggerHandler.getAccountDetails(accountIdSet);

        Test.stopTest();

        System.assertNotEquals(null, accountMap, 'Account map should not be null');
        System.assertEquals(1, accountMap.size(), 'Account map should contain one account');
        System.assert(accountMap.containsKey(locationAccount.Id), 'Account map should contain location account');
    }
}