objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Vendor_ID__c</fullName>
        <description>Numeric ID assigned by the system to the parent vendor</description>
        <formula>Parent.Vendor_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Vendor ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Core_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Core Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBID_text_c__c</fullName>
        <description>Formula field to convert SBID number field to text</description>
        <formula>TEXT(	Acorn_SBID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SBID text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets (Supplier)</relationshipLabel>
        <relationshipName>Assets_Supplier</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Availability_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Availability_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_Service_DateTime__c</fullName>
        <description>SLA Date Time field value for UI purpose</description>
        <formula>IF(OR(ISPICKVAL(Case_Type__c,&quot;Activate&quot;),ISPICKVAL(Case_Type__c,&quot;Modify&quot;),ISPICKVAL(Case_Type__c,&quot;Deactivate&quot;)), (IF(OR(ISBLANK(SLA_Service_Date_Time__c)),
&quot;&quot;,
MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 6, 2 ) &amp; &quot;/&quot; &amp;
MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 9, 2 ) &amp; &quot;/&quot; &amp;
LEFT( TEXT( SLA_Service_Date_Time__c + (7/24)), 4 ) &amp; &quot; &quot; &amp;
TEXT(
IF(
OR(
VALUE( MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 12, 2 ) ) = 0,
VALUE( MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 12, 2 ) ) = 12
),
12,
VALUE( MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 12, 2 ) )
-
IF(
VALUE( MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 12, 2 ) ) &lt; 12,
0,
12
)
)
)
&amp;&quot;:&quot;&amp;
MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 15, 2 )
&amp;&quot; &quot;&amp;
IF(
VALUE( MID( TEXT( SLA_Service_Date_Time__c + (7/24) ), 12, 2 ) ) &lt; 12,
&quot;PM&quot;,
&quot;&quot;
)
&amp; &quot; &quot; &amp;
IF( $Setup.tz__lt_app_settings__c.tz__Abbreviation__c, &apos;EST&apos;,&quot;&quot;))) ,
(IF(OR(ISBLANK( Location__r.tz__UTC_Offset_F__c ),ISBLANK(SLA_Service_Date_Time__c)),
&quot;&quot;,
MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 6, 2 ) &amp; &quot;/&quot; &amp;
MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 9, 2 ) &amp; &quot;/&quot; &amp;
LEFT( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 4 ) &amp; &quot; &quot; &amp;
TEXT(
IF(
OR(
VALUE( MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 12, 2 ) ) = 0,
VALUE( MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 12, 2 ) ) = 12
),
12,
VALUE( MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 12, 2 ) )
-
IF(
VALUE( MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 12, 2 ) ) &lt; 12,
0,
12
)
)
)
&amp;&quot;:&quot;&amp;
MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 15, 2 )
&amp;&quot; &quot;&amp;
IF(
VALUE( MID( TEXT( SLA_Service_Date_Time__c + Location__r.tz__UTC_Offset_F__c /24 ), 12, 2 ) ) &lt; 12,
&quot;AM&quot;,
&quot;PM&quot;
)
&amp; &quot; &quot; &amp;
IF( $Setup.tz__lt_app_settings__c.tz__Abbreviation__c, Location__r.tz__Timezone_F__c,&quot;&quot;)))

)</formula>
        <label>SLA Service Date/Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date of service associated to the case</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Supplier for this Case</description>
        <label>Supplier Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. - Case.Supplier</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Primary Supplier)</relationshipLabel>
        <relationshipName>Cases_Supplier1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WMCapacityController.cls
/**
 * @description Controller for WM Capacity Planner Lightning components
 * Refactored to delegate service date calculation logic to SLACalculationUtility
 * This class now serves as a thin presentation layer for UI interactions
 */
public with sharing class WMCapacityController {

    @AuraEnabled
    public static void updateCase(Id caseId, String serviceDate) {
        Case c = [SELECT Id, Service_Date__c, Availability_Confirmed__c, Availability_Checked__c
                  FROM Case WHERE Id=:caseId];

        String parseDate = date.parse(serviceDate).format();

        c.Service_Date__c = date.parse(parseDate);
        c.Availability_Confirmed__c = TRUE;
        c.Availability_Checked__c = TRUE;

        update c;
		GetCaseInformation.insertPlannerComment(caseId, parseDate, true, false);
    }

    @AuraEnabled
    public static void confirmCheck(Id caseId) {
        Case c = [SELECT Id, Availability_Checked__c FROM Case WHERE Id=:caseId];

        c.Availability_Checked__c = TRUE;

        update c;
    }

    @AuraEnabled
    public static String getSLADate(Id caseId) {

        String slaDate;

		//Updated on 5/15/2020 by George Martin - Returning the same field to the capacity controller that is being returned
		//to the Case UI

        Case c = [SELECT SLA_Service_DateTime__c
                 FROM Case
                 WHERE Id =: caseId];

        If (c.SLA_Service_DateTime__c != Null) {
            slaDate = string.valueOf(c.SLA_Service_DateTime__c);
            if (slaDate.contains('-')) {
                slaDate = slaDate.substringBefore(' ');
                String year = slaDate.substringBefore('-').substringBefore(' ');
                String day = slaDate.substringAfterLast('-');
                String month = slaDate.substringBeforeLast('-').substringAfter('-');
                slaDate = month + '/' + day + '/' + year;
            } else {
                slaDate = slaDate.substringBefore(' ');
            }
        }

        return slaDate;
    }

    @AuraEnabled
    public static String getAcornBaseline(Id caseId) {

        String baseline;
        Case c = [SELECT Id, AssetId FROM Case WHERE Id=:caseId];
        Id serviceHeader = c.AssetId;

        Asset[] details = [SELECT Id, Is_Core_Service__c, SBID_Text_c__c, Supplier__r.Parent_Vendor_ID__c
                           FROM Asset
                           WHERE ParentId=:serviceHeader AND Is_Core_service__c = TRUE AND
                           Start_Date__c <= Today AND (End_Date__c >= Today OR End_Date__c = Null)
                           LIMIT 1
                          ];

        If (details == Null || details[0].SBID_text_c__c == Null) {
            return baseline;
        }

        If (details[0].Supplier__r.Parent_Vendor_ID__c == '8') {
        	baseline = details[0].SBID_Text_c__c;
        }


        return baseline;
    }

    /**
     * @description Retrieves available service dates from WM Capacity Planner API
     * REFACTORED: Delegates to SLACalculationUtility for the actual API call
     * @param baseline The SBID (Service Baseline ID) to query
     * @return List of available dates in MM/DD/YYYY format
     */
    @AuraEnabled
    public static List<String> getAvailableDates(String baseline) {
        // Delegate to SLACalculationUtility
        return SLACalculationUtility.callWMCapacityPlannerAPI(baseline);
    }

    // ================================================================================
    // DEPRECATED: These methods/classes have been consolidated into SLACalculationUtility
    // Kept here temporarily for backward compatibility with any direct references
    // ================================================================================

    /**
     * @deprecated Use SLACalculationUtility.parseCapacityJSON instead
     */
    @Deprecated
    @AuraEnabled
	public static List<String> parseCapJSON(capacityResponse jsonResp, String requestedDate) {
		List<String> dates = new List<String>();
		List<String> availDates = new List<String>();
        List<Capacity> capacities = new List<Capacity>();
		if(jsonResp.Data!=null){
            capacities = jsonResp.Data.Site.Capacity;
        }
		for (Capacity cap : capacities) {
                for (String d : cap.AvailableDates) {
                    String year = d.substringBefore('/');
                    String day = d.substringAfterLast('/');
                    String month = d.substringBeforeLast('/').substringAfter('/');
                    d = month + '/' + day + '/' + year;
                    availDates.add(d);
                }
            }

			return availDates;
	}

    /**
     * @deprecated Use SLACalculationUtility.CapacityResponse instead
     */
    @Deprecated
    public inherited sharing class capacityResponse {
        public Data Data;
        public WorkOrderWebservices.ErrorMessageWrapper Problem;
    }

    /**
     * @deprecated Use SLACalculationUtility.CapacitySiteData instead
     */
    @Deprecated
    public inherited sharing class Data {
        public Site Site;
    }

    /**
     * @deprecated Use SLACalculationUtility.CapacitySite instead
     */
    @Deprecated
    public inherited sharing class Site {
        public String Name;
        public List<Capacity> Capacity;
    }

    /**
     * @deprecated Use SLACalculationUtility.CapacityData instead
     */
    @Deprecated
    public inherited sharing class Capacity {
        public String LineOfBusiness;
        public String Status;
        public List<String> AvailableDates;
    }

    /**
     * @deprecated Use SLACalculationUtility.parseCapacityResponse instead
     */
    @Deprecated
    public static capacityResponse parseCapacity(String json) {
        return (capacityResponse) System.JSON.deserialize(json, capacityResponse.class);
    }

    public inherited sharing class dualList {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;

        public dualList(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}