objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Location</description>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service_Request</fullName>
        <active>true</active>
        <description>A record type to capture requested asset changes or new assets</description>
        <label>Service Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Status__c</fullName>
        <description>Captures the sub-status for a Case State</description>
        <label>Case Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Inbound Interaction</fullName>
                </value>
                <value>
                    <fullName>Pending Customer Information</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Procurement</fullName>
                </value>
                <value>
                    <fullName>Pending Cost Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Request Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Price Configuration</fullName>
                </value>
                <value>
                    <fullName>Pending Quote Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Information</fullName>
                </value>
                <value>
                    <fullName>Pending Service Integration</fullName>
                </value>
                <value>
                    <fullName>Pending Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Manual Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pending Service Confirmation</fullName>
                </value>
                <value>
                    <fullName>Service Not Performed</fullName>
                </value>
                <value>
                    <fullName>Service Confirmed</fullName>
                </value>
                <value>
                    <fullName>Service Not Confirmed</fullName>
                </value>
                <value>
                    <fullName>Request Not Approved</fullName>
                </value>
                <value>
                    <fullName>Request Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Follow Up</fullName>
                </value>
                <value>
                    <fullName>Pending Service Issue Resolution</fullName>
                </value>
                <value>
                    <fullName>Pending Schedule Recovery</fullName>
                </value>
                <value>
                    <fullName>Pending Recovery Confirmation</fullName>
                </value>
                <value>
                    <fullName>Status Provided</fullName>
                </value>
                <value>
                    <fullName>Status Not Provided</fullName>
                </value>
                <value>
                    <fullName>Recovery Scheduled</fullName>
                </value>
                <value>
                    <fullName>Recovery Not Performed</fullName>
                </value>
                <value>
                    <fullName>Recovery Confirmed</fullName>
                </value>
                <value>
                    <fullName>Integration Error</fullName>
                </value>
                <value>
                    <fullName>Request Closed</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Location)</relationshipLabel>
        <relationshipName>Cases_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CaseAttributeServiceTest.cls
/**
 * @description Test class for CaseAttributeService
 *
 * Coverage Target: 75%+
 *
 * @author Waste Management
 * @date 2025
 * @group Test Classes
 */
@isTest
private class CaseAttributeServiceTest {

    @testSetup
    static void setupTestData() {
        TestDataFactory.createFullTestHierarchy();
    }

    @isTest
    static void testInitializeCase_Single() {
        // Given
        Case testCase = TestDataFactory.createCase('Service_Request');

        Test.startTest();
        // When
        Case result = CaseAttributeService.initializeCase(testCase);
        Test.stopTest();

        // Then
        System.assertNotEquals(null, result, 'Case should be initialized');
    }

    @isTest
    static void testInitializeCases_Bulk() {
        // Given
        List<Case> cases = TestDataFactory.createCases(5, 'Service_Request');

        Test.startTest();
        // When
        CaseAttributeService.initializeCases(cases);
        Test.stopTest();

        // Then
        System.assertEquals(5, cases.size(), 'All cases should be processed');
    }

    @isTest
    static void testInitializeCases_ClosedPickup() {
        // Given
        Case testCase = TestDataFactory.createCase('Service_Request');
        testCase.Status = 'Closed';
        testCase.Case_type__c = 'Pickup';

        Test.startTest();
        // When
        CaseAttributeService.initializeCase(testCase);
        Test.stopTest();

        // Then
        System.assertNotEquals(null, testCase.Case_Sub_Status__c, 'Sub-status should be set');
    }

    @isTest
    static void testInitializeCases_NullInput() {
        Test.startTest();
        // When
        CaseAttributeService.initializeCases(null);
        Test.stopTest();

        // Then - No exception should be thrown
        System.assert(true, 'Should handle null gracefully');
    }

    @isTest
    static void testInitializeCases_EmptyList() {
        Test.startTest();
        // When
        CaseAttributeService.initializeCases(new List<Case>());
        Test.stopTest();

        // Then - No exception should be thrown
        System.assert(true, 'Should handle empty list gracefully');
    }

    @isTest
    static void testUpdateCaseAttributes() {
        // Given
        Map<String, Object> testData = TestDataFactory.createFullTestHierarchy();
        Asset testAsset = (Asset)testData.get('asset');
        Account locationAccount = (Account)testData.get('locationAccount');

        Case testCase = TestDataFactory.createCase('Service_Request');
        testCase.AssetId = testAsset.Id;
        testCase.Location__c = locationAccount.Id;

        Map<Id, Asset> containerMap = new Map<Id, Asset>{testAsset.Id => testAsset};
        Map<Id, Account> locationMap = new Map<Id, Account>{locationAccount.Id => locationAccount};

        Test.startTest();
        // When
        CaseAttributeService.updateCaseAttributes(new List<Case>{testCase}, containerMap, locationMap);
        Test.stopTest();

        // Then
        System.assertNotEquals(null, testCase, 'Case should be updated');
    }
}