objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Length of Service, for example Temp, Perm or Seas</description>
        <label>Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Seasonal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <formula>TEXT(Product2.Equipment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Equipment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occurrence_Type__c</fullName>
        <label>Occurrence Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>On-Call</fullName>
                </value>
                <value>
                    <fullName>Scheduled On-Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CPQ_New_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox will be checked when the Case owner have Salesforce CPQ License</description>
        <label>CPQ New Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <description>Case Reason on the Case</description>
        <label>Case Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Sub_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Rolloff</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>Landfill</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>New_Service_Case</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>For customer requests regarding the addition of temporary or permanent service at their location, such as delivery or installation of a compactor.</description>
        <label>New Service Case</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <description>Type of container/equipment if this is an equipment to align with Acorn values for container type</description>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Container_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Case_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>All Other Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary/Regulatory</fullName>
    </customValue>
    <customValue>
        <fullName>Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Baler Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Mailback Box</fullName>
    </customValue>
    <customValue>
        <fullName>Onsite Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Discrepancies</fullName>
    </customValue>
    <customValue>
        <fullName>Bill Not Received</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Service</fullName>
    </customValue>
    <customValue>
        <fullName>Clean Up External</fullName>
    </customValue>
    <customValue>
        <fullName>Clean Up Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Closed/Closing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Communication Channel Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor/Baler/Vertical CMP</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Construction and Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Contaminated</fullName>
    </customValue>
    <customValue>
        <fullName>Cost/Price</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Days of Service</fullName>
    </customValue>
    <customValue>
        <fullName>Dig-Out</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster/Toter/Port-o-let</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Recycling Collection</fullName>
    </customValue>
    <masterLabel>Case Reason</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Container_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural Waste</fullName>
    </customValue>
    <customValue>
        <fullName>Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Bagster Bag</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Baler - Horizontal</fullName>
    </customValue>
    <customValue>
        <fullName>Baler - Mini</fullName>
    </customValue>
    <customValue>
        <fullName>Baler - Vertical</fullName>
    </customValue>
    <customValue>
        <fullName>Basket</fullName>
    </customValue>
    <customValue>
        <fullName>Bladder</fullName>
    </customValue>
    <customValue>
        <fullName>Box</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>Cart Dumper - Stand Alone</fullName>
    </customValue>
    <customValue>
        <fullName>Carts</fullName>
    </customValue>
    <customValue>
        <fullName>Catwalk</fullName>
    </customValue>
    <customValue>
        <fullName>Client Owned</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Appartment Style</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Box Only</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Breakaway</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Dewatering</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - DRC</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Enclosure</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Integrated Cart Dumper</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Pacman</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Pac Tainer</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Pre-crusher</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - RUNI</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Self-Contained</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Self Contained East</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor - Tank/Stubby</fullName>
    </customValue>
    <masterLabel>Container Type</masterLabel>
</GlobalValueSet>

classes/CaseTypeConfiguratorController.cls
/**
 * Case Type Configurator Controller
 *
 * Unified LWC controller for record type and case type/sub-type/reason configuration.
 * Replaces changeRecordTypeController and FillCaseSubType functionality.
 *
 * Features:
 * - Record type selection with filtering
 * - Dependent picklist values for Case Type, Sub-Type, and Reason
 * - Auto-population based on asset and record type
 * - Validation of selections
 * - Case update with new values
 *
 * Refactored from: changeRecordTypeController.cls
 *
 * @author George Martin
 * @date 2025-11-18
 */
public with sharing class CaseTypeConfiguratorController {

    // ========================================
    // Record Type Methods
    // ========================================

    /**
     * Get available record types for Case object
     *
     * @return List of available record types
     */
    @AuraEnabled(cacheable=true)
    public static List<RecordTypeOption> getAvailableRecordTypes() {
        try {
            List<RecordTypeOption> options = new List<RecordTypeOption>();

            // Exclude certain record types from selection
            List<RecordType> recordTypes = [
                SELECT Id, Name, Description
                FROM RecordType
                WHERE SobjectType = 'Case'
                AND Name NOT IN ('Pickup Case', 'Status Case', 'New Service Case')
                AND IsActive = true
                ORDER BY Name
            ];

            for (RecordType rt : recordTypes) {
                options.add(new RecordTypeOption(rt.Id, rt.Name, rt.Description));
            }

            return options;

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.getAvailableRecordTypes',
                'Error getting record types: ' + e.getMessage(), e);
            throw new AuraHandledException('Failed to get record types: ' + e.getMessage());
        }
    }

    /**
     * Get current case configuration
     *
     * @param caseId The ID of the case
     * @return Current case configuration
     */
    @AuraEnabled(cacheable=true)
    public static CaseConfiguration getCurrentConfiguration(String caseId) {
        try {
            if (String.isBlank(caseId)) {
                throw new AuraHandledException('Case ID is required');
            }

            Case c = [
                SELECT Id, RecordTypeId, RecordType.Name, Case_Type__c, Case_Sub_Type__c,
                       Case_Reason__c, AssetId, Asset.Name, Asset.Product2.Family,
                       Asset.Duration__c, Asset.Occurrence_Type__c, Asset.Product2.Equipment_Type__c,
                       CPQ_New_Service__c, LOB__c
                FROM Case
                WHERE Id = :caseId
                LIMIT 1
            ];

            CaseConfiguration config = new CaseConfiguration();
            config.recordTypeId = c.RecordTypeId;
            config.recordTypeName = c.RecordType.Name;
            config.caseType = c.Case_Type__c;
            config.caseSubType = c.Case_Sub_Type__c;
            config.caseReason = c.Case_Reason__c;
            config.assetId = c.AssetId;
            config.assetName = c.Asset != null ? c.Asset.Name : '';
            config.assetFamily = c.Asset != null && c.Asset.Product2 != null ? c.Asset.Product2.Family : '';

            return config;

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.getCurrentConfiguration',
                'Error getting configuration: ' + e.getMessage(), e);
            throw new AuraHandledException('Failed to get configuration: ' + e.getMessage());
        }
    }

    // ========================================
    // Picklist Value Methods
    // ========================================

    /**
     * Get Case Type picklist values
     *
     * @param recordTypeId The record type ID (for filtering)
     * @return List of Case Type values
     */
    @AuraEnabled(cacheable=true)
    public static List<PicklistOption> getCaseTypeValues(String recordTypeId) {
        try {
            List<PicklistOption> options = new List<PicklistOption>();

            Schema.DescribeFieldResult fieldResult = Case.Case_Type__c.getDescribe();
            List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();

            for (Schema.PicklistEntry entry : entries) {
                if (entry.isActive()) {
                    options.add(new PicklistOption(entry.getLabel(), entry.getValue()));
                }
            }

            return options;

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.getCaseTypeValues',
                'Error getting case type values: ' + e.getMessage(), e);
            return new List<PicklistOption>();
        }
    }

    /**
     * Get Case Sub-Type picklist values based on Case Type
     *
     * @param caseType The selected case type
     * @param recordTypeId The record type ID
     * @return List of Case Sub-Type values
     */
    @AuraEnabled(cacheable=true)
    public static List<PicklistOption> getCaseSubTypeValues(String caseType, String recordTypeId) {
        try {
            List<PicklistOption> options = new List<PicklistOption>();

            Schema.DescribeFieldResult fieldResult = Case.Case_Sub_Type__c.getDescribe();
            List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();

            // Get controlling values for filtering
            Map<String, List<String>> dependentPicklistMap = getDependentPicklistValues(
                Case.Case_Type__c,
                Case.Case_Sub_Type__c
            );

            // If case type is selected, filter by dependent values
            if (String.isNotBlank(caseType) && dependentPicklistMap.containsKey(caseType)) {
                List<String> validValues = dependentPicklistMap.get(caseType);
                for (Schema.PicklistEntry entry : entries) {
                    if (entry.isActive() && validValues.contains(entry.getValue())) {
                        options.add(new PicklistOption(entry.getLabel(), entry.getValue()));
                    }
                }
            } else {
                // Return all active values
                for (Schema.PicklistEntry entry : entries) {
                    if (entry.isActive()) {
                        options.add(new PicklistOption(entry.getLabel(), entry.getValue()));
                    }
                }
            }

            return options;

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.getCaseSubTypeValues',
                'Error getting case sub-type values: ' + e.getMessage(), e);
            return new List<PicklistOption>();
        }
    }

    /**
     * Get Case Reason picklist values based on Case Sub-Type
     *
     * @param caseSubType The selected case sub-type
     * @param recordTypeId The record type ID
     * @return List of Case Reason values
     */
    @AuraEnabled(cacheable=true)
    public static List<PicklistOption> getCaseReasonValues(String caseSubType, String recordTypeId) {
        try {
            List<PicklistOption> options = new List<PicklistOption>();

            Schema.DescribeFieldResult fieldResult = Case.Case_Reason__c.getDescribe();
            List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();

            // Get controlling values for filtering
            Map<String, List<String>> dependentPicklistMap = getDependentPicklistValues(
                Case.Case_Sub_Type__c,
                Case.Case_Reason__c
            );

            // If case sub-type is selected, filter by dependent values
            if (String.isNotBlank(caseSubType) && dependentPicklistMap.containsKey(caseSubType)) {
                List<String> validValues = dependentPicklistMap.get(caseSubType);
                for (Schema.PicklistEntry entry : entries) {
                    if (entry.isActive() && validValues.contains(entry.getValue())) {
                        options.add(new PicklistOption(entry.getLabel(), entry.getValue()));
                    }
                }
            } else {
                // Return all active values
                for (Schema.PicklistEntry entry : entries) {
                    if (entry.isActive()) {
                        options.add(new PicklistOption(entry.getLabel(), entry.getValue()));
                    }
                }
            }

            return options;

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.getCaseReasonValues',
                'Error getting case reason values: ' + e.getMessage(), e);
            return new List<PicklistOption>();
        }
    }

    // ========================================
    // Case Update Methods
    // ========================================

    /**
     * Update case with new configuration
     *
     * @param caseId The ID of the case
     * @param configJson JSON string of configuration
     */
    @AuraEnabled
    public static void updateCaseConfiguration(String caseId, String configJson) {
        try {
            if (String.isBlank(caseId)) {
                throw new AuraHandledException('Case ID is required');
            }

            ConfigurationUpdate config = (ConfigurationUpdate) JSON.deserialize(
                configJson,
                ConfigurationUpdate.class
            );

            Case c = [
                SELECT Id, RecordTypeId, Case_Type__c, Case_Sub_Type__c, Case_Reason__c,
                       CPQ_New_Service__c, LOB__c, AssetId, Asset.Product2.Family
                FROM Case
                WHERE Id = :caseId
                LIMIT 1
            ];

            // Update record type if provided
            if (String.isNotBlank(config.recordTypeId)) {
                c.RecordTypeId = config.recordTypeId;

                // Handle New Service case special logic
                Id newServiceRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName()
                    .get(Constant_Util.New_Service_Case).getRecordTypeId();

                if (config.recordTypeId == newServiceRecordType) {
                    c.CPQ_New_Service__c = hasCPQLicense();
                    if (String.isBlank(c.LOB__c)) {
                        c.LOB__c = c.Asset != null && c.Asset.Product2 != null
                            ? c.Asset.Product2.Family
                            : Constant_Util.COMMERCIAL;
                    }
                } else {
                    c.CPQ_New_Service__c = false;
                }
            }

            // Update case type fields
            c.Case_Type__c = config.caseType;
            c.Case_Sub_Type__c = config.caseSubType;
            c.Case_Reason__c = config.caseReason;

            update c;

            UTIL_LoggingService.logDebug('CaseTypeConfiguratorController.updateCaseConfiguration',
                'Updated case ' + caseId + ' with configuration');

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.updateCaseConfiguration',
                'Error updating configuration: ' + e.getMessage(), e);
            throw new AuraHandledException('Failed to update configuration: ' + e.getMessage());
        }
    }

    /**
     * Quick update case type for predefined scenarios (Pickup, SNP, ETA)
     *
     * @param caseId The ID of the case
     * @param quickType The quick type: 'Pickup', 'SNP', 'ETA', 'New Service', 'Update Asset'
     */
    @AuraEnabled
    public static void updateQuickCaseType(String caseId, String quickType) {
        try {
            if (String.isBlank(caseId)) {
                throw new AuraHandledException('Case ID is required');
            }

            Case c = [
                SELECT Id, RecordTypeId, Case_Type__c, Case_Sub_Type__c, Case_Reason__c,
                       AssetId, Asset.Name, Asset.Product2.Family, Asset.Duration__c,
                       Asset.Occurrence_Type__c, Asset.Product2.Equipment_Type__c,
                       CPQ_New_Service__c, LOB__c
                FROM Case
                WHERE Id = :caseId
                LIMIT 1
            ];

            // Reset CPQ flag
            c.CPQ_New_Service__c = false;

            if (quickType == 'Pickup') {
                handlePickupCase(c);
            } else if (quickType == 'SNP') {
                handleSNPCase(c);
            } else if (quickType == 'ETA') {
                handleETACase(c);
            } else if (quickType == 'New Service') {
                handleNewServiceCase(c);
            } else if (quickType == 'Update Asset') {
                handleUpdateAssetCase(c);
            }

            update c;

            UTIL_LoggingService.logDebug('CaseTypeConfiguratorController.updateQuickCaseType',
                'Updated case ' + caseId + ' with quick type: ' + quickType);

        } catch (Exception e) {
            UTIL_LoggingService.logError('CaseTypeConfiguratorController.updateQuickCaseType',
                'Error updating quick type: ' + e.getMessage(), e);
            throw new AuraHandledException('Failed to update case type: ' + e.getMessage());
        }
    }

    // ========================================
    // Validation Methods
    // ========================================

    /**
     * Validate case configuration
     *
     * @param configJson JSON string of configuration
     * @return Validation result
     */
    @AuraEnabled
    public static Map<String, Object> validateConfiguration(String configJson) {
        Map<String, Object> result = new Map<String, Object>();
        result.put('isValid', true);
        result.put('message', '');

        try {
            ConfigurationUpdate config = (ConfigurationUpdate) JSON.deserialize(
                configJson,
                ConfigurationUpdate.class
            );

            // Validate required fields
            if (String.isBlank(config.caseType)) {
                result.put('isValid', false);
                result.put('message', 'Case Type is required');
                return result;
            }

            return result;

        } catch (Exception e) {
            result.put('isValid', false);
            result.put('message', 'Configuration validation failed: ' + e.getMessage());
            return result;
        }
    }

    // ========================================
    // Private Helper Methods
    // ========================================

    /**
     * Handle Pickup case type setup
     */
    private static void handlePickupCase(Case c) {
        c.Case_Type__c = 'Pickup';
        c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
            .get('Pickup Case').getRecordTypeId();
        c.Case_Reason__c = '';

        // Determine sub-type based on asset characteristics
        if (c.Asset == null || c.Asset.Product2 == null) {
            c.Case_Sub_Type__c = '';
            return;
        }

        String family = c.Asset.Product2.Family;
        String equipmentType = c.Asset.Product2.Equipment_Type__c;
        String occurrenceType = c.Asset.Occurrence_Type__c;
        String duration = c.Asset.Duration__c;

        if (family == Constant_Util.COMMERCIAL && occurrenceType == Constant_Util.ON_CALL) {
            c.Case_Sub_Type__c = Constant_Util.ON_CALL_PICK;
        } else if (family == Constant_Util.COMMERCIAL
                  && Constant_Util.HAND_PICKUP.equals(equipmentType)
                  && Constant_Util.PERMANENT.equals(duration)) {
            c.Case_Sub_Type__c = '';
        } else if (family == Constant_Util.COMMERCIAL
                  && (occurrenceType == Constant_Util.SCHEDULED || occurrenceType == Constant_Util.SCHEDULED_ON_CALL)) {
            c.Case_Sub_Type__c = Constant_Util.EXTRA_PICKUP;
        } else if (family == Constant_Util.ROLLOFF
                  && duration == Constant_Util.PERMANENT
                  && equipmentType != Constant_Util.Baler) {
            c.Case_Sub_Type__c = Constant_Util.EMPTY_AND_RETURN;
        } else if (Constant_Util.Baler.equals(equipmentType)) {
            c.Case_Sub_Type__c = Constant_Util.Bales;
        } else if (family == Constant_Util.SERVICES && c.Asset.Name.equals(Constant_Util.Bulk_Service_Type)) {
            c.Case_Sub_Type__c = Constant_Util.Bulk_Service_Type;
        } else if (family == Constant_Util.SERVICES && c.Asset.Name.equals(Constant_Util.Got_Junk_Pickup)) {
            c.Case_Sub_Type__c = Constant_Util.Haul_Away_No_Equipment;
        } else {
            c.Case_Sub_Type__c = '';
        }
    }

    /**
     * Handle SNP (Service Not Performed) case type setup
     */
    private static void handleSNPCase(Case c) {
        c.Case_Type__c = 'Status';
        c.Case_Sub_Type__c = 'Service not performed';
        c.Case_Reason__c = 'Customer Reported';
        c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
            .get('Status Case').getRecordTypeId();
    }

    /**
     * Handle ETA case type setup
     */
    private static void handleETACase(Case c) {
        c.Case_Type__c = 'Status';
        c.Case_Sub_Type__c = 'ETA';
        c.Case_Reason__c = '';
        c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
            .get('Status Case').getRecordTypeId();
    }

    /**
     * Handle New Service case type setup
     */
    private static void handleNewServiceCase(Case c) {
        Id newServiceRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName()
            .get(Constant_Util.New_Service_Case).getRecordTypeId();

        c.Case_Type__c = 'New Service';
        c.Case_Sub_Type__c = '';
        c.Case_Reason__c = '';
        c.CPQ_New_Service__c = hasCPQLicense();
        c.RecordTypeId = newServiceRecordType;

        if (String.isBlank(c.LOB__c)) {
            c.LOB__c = (c.Asset != null && c.Asset.Product2 != null && String.isNotBlank(c.Asset.Product2.Family))
                ? c.Asset.Product2.Family
                : Constant_Util.COMMERCIAL;
        }
    }

    /**
     * Handle Update Asset case type setup
     */
    private static void handleUpdateAssetCase(Case c) {
        Id updateAssetRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName()
            .get('Update Asset Case').getRecordTypeId();

        c.Case_Type__c = '';
        c.Case_Sub_Type__c = '';
        c.Case_Reason__c = '';
        c.RecordTypeId = updateAssetRecordType;
    }

    /**
     * Check if current user has CPQ license
     */
    private static Boolean hasCPQLicense() {
        List<PermissionSetLicenseAssign> pslList = [
            SELECT Id, AssigneeId, PermissionSetLicenseId, PermissionSetLicense.MasterLabel
            FROM PermissionSetLicenseAssign
            WHERE PermissionSetLicense.MasterLabel = 'Salesforce CPQ License'
            AND AssigneeId = :UserInfo.getUserId()
        ];

        return !pslList.isEmpty();
    }

    /**
     * Get dependent picklist values
     */
    private static Map<String, List<String>> getDependentPicklistValues(
        Schema.SObjectField controllingField,
        Schema.SObjectField dependentField
    ) {
        Map<String, List<String>> dependentPicklistMap = new Map<String, List<String>>();

        Schema.DescribeFieldResult controllingFieldInfo = controllingField.getDescribe();
        Schema.DescribeFieldResult dependentFieldInfo = dependentField.getDescribe();

        List<Schema.PicklistEntry> controllingValues = controllingFieldInfo.getPicklistValues();
        List<Schema.PicklistEntry> dependentValues = dependentFieldInfo.getPicklistValues();

        for (Schema.PicklistEntry dependentValue : dependentValues) {
            if (dependentValue.isActive()) {
                List<String> controllers = new List<String>();

                // Simplified approach - add all controlling values
                for (Schema.PicklistEntry controllingValue : controllingValues) {
                    if (controllingValue.isActive()) {
                        controllers.add(controllingValue.getValue());
                    }
                }

                // Store in reverse map (we'll return controlling -> dependent)
                for (String controller : controllers) {
                    if (!dependentPicklistMap.containsKey(controller)) {
                        dependentPicklistMap.put(controller, new List<String>());
                    }
                    dependentPicklistMap.get(controller).add(dependentValue.getValue());
                }
            }
        }

        return dependentPicklistMap;
    }

    // ========================================
    // Wrapper Classes
    // ========================================

    /**
     * Record Type Option Wrapper
     */
    public class RecordTypeOption {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String description { get; set; }

        public RecordTypeOption(String id, String name, String description) {
            this.id = id;
            this.name = name;
            this.description = description;
        }
    }

    /**
     * Case Configuration Wrapper
     */
    public class CaseConfiguration {
        @AuraEnabled public String recordTypeId { get; set; }
        @AuraEnabled public String recordTypeName { get; set; }
        @AuraEnabled public String caseType { get; set; }
        @AuraEnabled public String caseSubType { get; set; }
        @AuraEnabled public String caseReason { get; set; }
        @AuraEnabled public String assetId { get; set; }
        @AuraEnabled public String assetName { get; set; }
        @AuraEnabled public String assetFamily { get; set; }
    }

    /**
     * Configuration Update Input Wrapper
     */
    public class ConfigurationUpdate {
        @AuraEnabled public String recordTypeId { get; set; }
        @AuraEnabled public String caseType { get; set; }
        @AuraEnabled public String caseSubType { get; set; }
        @AuraEnabled public String caseReason { get; set; }
    }

    /**
     * Picklist Option Wrapper
     */
    public class PicklistOption {
        @AuraEnabled public String label { get; set; }
        @AuraEnabled public String value { get; set; }

        public PicklistOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
}