objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <description>Case Reason on the Case</description>
        <label>Case Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Sub_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>It will have all case sub type values which will depend on Case type selection.</description>
        <label>Case Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Case_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>the sub type of the case</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsOpportunity_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Opportunity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quote Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>This field contains the parent case number</description>
        <label>Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Acorn Issue Tracking Number, AKA T-Number</description>
        <label>Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Modify_Existing_Service_Case</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>For customers or vendor requests regarding modification to existing services, such as a change in frequency, cancellation or addition of fees.</description>
        <label>Modify Existing Service Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>New_Service_Case</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>For customer requests regarding the addition of temporary or permanent service at their location, such as delivery or installation of a compactor.</description>
        <label>New Service Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Update_Asset_Case</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>This record type is created for add change story SDT-19922</description>
        <label>Update Asset Case</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_record_Type__c</fullName>
        <formula>Case__r.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__QuotePricebookId__c</fullName>
        <description>Custom pricebook ID field that updates the standard Pricebook2Id field. Use to automatically drive pricebook selection from workflow rules.</description>
        <label>Quote Pricebook Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason__c</fullName>
    <formula>Text(SBQQ__Opportunity2__r.Case__r.Case_Reason__c)</formula>
    <label>Case Reason</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case_record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_record_Type__c</fullName>
    <formula>SBQQ__Opportunity2__r.Case_record_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Type__c</fullName>
    <formula>Text(SBQQ__Opportunity2__r.Case__r.Case_Sub_Type__c)</formula>
    <label>Case Sub-Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <formula>Text(SBQQ__Opportunity2__r.Case__r.Case_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Only__c.field-meta.xml
<CustomField>
    <fullName>Quote_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Product Configured</fullName>
                <label>Procure Service</label>
            </value>
            <value>
                <fullName>Cost Configured</fullName>
                <label>Configure Price</label>
            </value>
            <value>
                <fullName>Price Configured</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Case_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>All Other Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary/Regulatory</fullName>
    </customValue>
    <customValue>
        <fullName>Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Baler Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Mailback Box</fullName>
    </customValue>
    <customValue>
        <fullName>Onsite Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Discrepancies</fullName>
    </customValue>
    <customValue>
        <fullName>Bill Not Received</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Service</fullName>
    </customValue>
    <customValue>
        <fullName>Clean Up External</fullName>
    </customValue>
    <customValue>
        <fullName>Clean Up Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Closed/Closing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Communication Channel Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor/Baler/Vertical CMP</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Construction and Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Contaminated</fullName>
    </customValue>
    <customValue>
        <fullName>Cost/Price</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Reported</fullName>
    </customValue>
    <customValue>
        <fullName>Days of Service</fullName>
    </customValue>
    <customValue>
        <fullName>Dig-Out</fullName>
    </customValue>
    <customValue>
        <fullName>Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster/Toter/Port-o-let</fullName>
    </customValue>
    <customValue>
        <fullName>Electronic Recycling Collection</fullName>
    </customValue>
    <masterLabel>Case Reason</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Keys</fullName>
    </customValue>
    <customValue>
        <fullName>Award Services</fullName>
    </customValue>
    <customValue>
        <fullName>Baler</fullName>
    </customValue>
    <customValue>
        <fullName>Bale Wire</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel</fullName>
    </customValue>
    <customValue>
        <fullName>Cancel Location</fullName>
    </customValue>
    <customValue>
        <fullName>Change/Correction</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor</fullName>
    </customValue>
    <customValue>
        <fullName>Compactor Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Question</fullName>
    </customValue>
    <customValue>
        <fullName>Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Dumpster Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>eBusiness Portal Question</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Return</fullName>
    </customValue>
    <customValue>
        <fullName>Empty and Do NOT Return</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment/Property</fullName>
    </customValue>
    <customValue>
        <fullName>ETA</fullName>
    </customValue>
    <customValue>
        <fullName>Event Box(es)</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Location</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Service</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Fee(s)</fullName>
    </customValue>
    <customValue>
        <fullName>General Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Service Level</fullName>
    </customValue>
    <customValue>
        <fullName>Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Increase/Decrease</fullName>
    </customValue>
    <customValue>
        <fullName>Lamptracker/Batterytracker/MedWaste</fullName>
    </customValue>
    <customValue>
        <fullName>Lids</fullName>
    </customValue>
    <description>Case Sub Type</description>
    <masterLabel>Case Sub Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Modify</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Change Service</fullName>
    </customValue>
    <customValue>
        <fullName>Discrepencies</fullName>
    </customValue>
    <customValue>
        <fullName>FAST Issue</fullName>
    </customValue>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Hauler Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Inoperable</fullName>
    </customValue>
    <customValue>
        <fullName>Interruption</fullName>
    </customValue>
    <customValue>
        <fullName>New Service</fullName>
    </customValue>
    <customValue>
        <fullName>Operable</fullName>
    </customValue>
    <customValue>
        <fullName>Payment Inquiries</fullName>
    </customValue>
    <customValue>
        <fullName>Pickup</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Declines</fullName>
    </customValue>
    <customValue>
        <fullName>Procurement</fullName>
    </customValue>
    <customValue>
        <fullName>Replace</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Special Request</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Change Vendor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellations</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Reconciliation (Step 2)</fullName>
        <isActive>false</isActive>
        <label>Billing Reconciliation (Step 2)</label>
    </customValue>
    <masterLabel>Case Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CaseCPQService.cls
/**
 * @description CaseCPQService - Service Layer for CPQ/Quote Operations
 *
 * This service class handles all CPQ (Configure, Price, Quote) integrations for Cases.
 * It provides a centralized location for quote creation, opportunity management,
 * and CPQ product configuration logic.
 *
 * Key Responsibilities:
 * - Create Opportunities and Quotes from Cases
 * - Manage CPQ quote line items
 * - Handle quote type determination logic
 * - Coordinate between Case and CPQ objects
 *
 * Design Principles:
 * - Single Responsibility: Only handles CPQ/Quote operations
 * - Service Layer: No direct UI dependencies
 * - Testability: All methods are mockable and bulkified where possible
 *
 * @author Waste Management
 * @date 2025
 * @group Service Layer
 */
public class CaseCPQService {

    // ========================================================================
    // QUOTE CREATION METHODS
    // ========================================================================

    /**
     * @description Creates Opportunity and Quote from Case (Lightning-enabled wrapper)
     * This method wraps the legacy createOppQuote logic from GetCaseInformation
     * for backward compatibility while providing the proper service layer structure.
     *
     * @param caseId The Case Id to create quote from
     * @return Quote Id of the created quote
     */
    @AuraEnabled
    public static String createQuoteFromCase(String caseId) {
        // Delegate to GetCaseInformation for now (maintains backward compatibility)
        // TODO: Refactor to move all CPQ logic into this service class
        return GetCaseInformation.createOppQuote(caseId);
    }

    /**
     * @description Creates Opportunity and Quote from multiple Cases (bulkified)
     * @param caseIds Set of Case Ids to create quotes from
     * @return Map of Case Id to Quote Id
     */
    public static Map<Id, Id> createQuotesFromCases(Set<Id> caseIds) {
        Map<Id, Id> caseToQuoteMap = new Map<Id, Id>();

        // TODO: Implement bulkified quote creation logic
        // For now, iterate (not optimal but maintains functionality)
        for (Id caseId : caseIds) {
            try {
                String quoteId = createQuoteFromCase(caseId);
                if (String.isNotBlank(quoteId)) {
                    caseToQuoteMap.put(caseId, quoteId);
                }
            } catch (Exception ex) {
                UTIL_LoggingService.logHandledException(
                    ex,
                    UserInfo.getOrganizationId(),
                    'CaseCPQService.createQuotesFromCases',
                    LoggingLevel.ERROR
                );
            }
        }

        return caseToQuoteMap;
    }

    /**
     * @description Determines the appropriate Quote Type based on Case attributes
     * Extracted from GetCaseInformation createOppQuote method for reusability
     *
     * @param caseRecord The Case record
     * @return Quote Type constant (Quote, Amendment, Correction, etc.)
     */
    public static String determineQuoteType(Case caseRecord) {
        String quoteType = '';
        Boolean isInternalCorrectionsTeamUser = UserServices.isInternalCorrectionTeamUser(UserInfo.getUserId());
        Boolean isHaulAway = HaulAwayService.getIsHaulAwayService(caseRecord);

        if ((caseRecord.Case_Record_Type__c == Constant_Util.New_Service_Case) || isHaulAway) {
            quoteType = Constant_Util.QUOTE;
        } else if (caseRecord.Case_Record_Type__c == Constant_Util.MODIFY_EXISTING_SERVICE_CASE &&
                   caseRecord.Case_Type__c == Constant_Util.Change_Service &&
                   caseRecord.Case_Sub_Type__c == Constant_Util.Change_Correction &&
                   caseRecord.Case_Reason__c == Constant_Util.CASE_REASON_DAYSOFSERVICE &&
                   !isInternalCorrectionsTeamUser) {
            quoteType = Constant_Util.QUOTE_TYPE_AMEND;
        } else if (caseRecord.Case_Record_Type__c == Constant_Util.UPDATE_ASSET_CASE) {
            quoteType = Constant_Util.QUOTE_TYPE_AMEND;
        } else if (caseRecord.Case_Record_Type__c == Constant_Util.MODIFY_EXISTING_SERVICE_CASE &&
                   caseRecord.Case_Type__c == Constant_Util.Change_Service &&
                   caseRecord.Case_Sub_Type__c == Constant_Util.Change_Correction) {
            quoteType = Constant_Util.QUOTE_TYPE_CORRECTION;
        } else if (caseRecord.Case_Record_Type__c == Constant_Util.MODIFY_EXISTING_SERVICE_CASE &&
                   caseRecord.Case_Type__c == Constant_Util.Change_Service &&
                   (caseRecord.Case_Sub_Type__c == Constant_Util.WASTE_STREAM ||
                    caseRecord.Case_Sub_Type__c == Constant_Util.Decrease ||
                    caseRecord.Case_Sub_Type__c == Constant_Util.Increase ||
                    caseRecord.Case_Sub_Type__c == Constant_Util.Rightsizing_Load_Max ||
                    caseRecord.Case_Sub_Type__c == Constant_Util.VENDOR)) {
            quoteType = Constant_Util.QUOTE_TYPE_AMEND;
        } else {
            quoteType = Constant_Util.KEYWORD_EXCEPTION;
        }

        return quoteType;
    }

    /**
     * @description Checks if a Case is eligible for CPQ quote creation
     * @param caseRecord The Case record to evaluate
     * @return True if eligible, false otherwise
     */
    public static Boolean isCaseEligibleForQuote(Case caseRecord) {
        // Business rules for quote eligibility
        if (caseRecord == null) {
            return false;
        }

        // Add eligibility checks based on Case Type, Status, etc.
        if (caseRecord.IsOpportunity_Created__c == true) {
            return false; // Already has a quote
        }

        // Check for New Service or Modify Service cases
        if (caseRecord.Case_Record_Type__c == Constant_Util.New_Service_Case ||
            caseRecord.Case_Record_Type__c == Constant_Util.MODIFY_EXISTING_SERVICE_CASE ||
            caseRecord.Case_Record_Type__c == Constant_Util.UPDATE_ASSET_CASE) {
            return true;
        }

        // Check for Haul Away Service
        if (HaulAwayService.getIsHaulAwayService(caseRecord)) {
            return true;
        }

        return false;
    }

    /**
     * @description Retrieves all Quotes associated with a Case
     * @param caseId The Case Id
     * @return List of Quotes related to the Case
     */
    public static List<SBQQ__Quote__c> getQuotesByCase(Id caseId) {
        List<SBQQ__Quote__c> quotes = [
            SELECT Id, Name, SBQQ__Status__c, SBQQ__Type__c,
                   SBQQ__Opportunity2__c, SBQQ__Primary__c,
                   SBQQ__StartDate__c, Duration__c, Quote_Only__c,
                   CreatedDate, LastModifiedDate
            FROM SBQQ__Quote__c
            WHERE SBQQ__Opportunity2__r.Case__c = :caseId
            ORDER BY CreatedDate DESC
        ];

        return quotes;
    }

    /**
     * @description Retrieves the primary Quote for a Case
     * @param caseId The Case Id
     * @return Primary Quote or null if not found
     */
    public static SBQQ__Quote__c getPrimaryQuoteByCase(Id caseId) {
        List<SBQQ__Quote__c> quotes = [
            SELECT Id, Name, SBQQ__Status__c, SBQQ__Type__c,
                   SBQQ__Opportunity2__c, SBQQ__Primary__c,
                   SBQQ__StartDate__c, Duration__c, Quote_Only__c,
                   CreatedDate, LastModifiedDate
            FROM SBQQ__Quote__c
            WHERE SBQQ__Opportunity2__r.Case__c = :caseId
            AND SBQQ__Primary__c = true
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        return quotes.isEmpty() ? null : quotes[0];
    }

    /**
     * @description Retrieves Opportunities associated with a Case
     * @param caseId The Case Id
     * @return List of Opportunities related to the Case
     */
    public static List<Opportunity> getOpportunitiesByCase(Id caseId) {
        List<Opportunity> opportunities = [
            SELECT Id, Name, StageName, CloseDate, Duration__c,
                   AccountId, Case__c, SBQQ__QuotePricebookId__c,
                   CreatedDate, LastModifiedDate
            FROM Opportunity
            WHERE Case__c = :caseId
            ORDER BY CreatedDate DESC
        ];

        return opportunities;
    }

    // ========================================================================
    // HELPER METHODS
    // ========================================================================

    /**
     * @description Builds case comments string for Quote
     * @param caseRecord The Case record
     * @param quoteName The Quote name
     * @return Formatted comments string
     */
    private static String buildQuoteComments(Case caseRecord, String quoteName) {
        String comments = 'SFDC Quote: ' + quoteName + '\n';

        if (caseRecord.Tracking_Number__c != null) {
            comments += 'SFDC Case: ' + caseRecord.CaseNumber + ' - Tracking Number: ' + caseRecord.Tracking_Number__c + '\n';
        } else {
            comments += 'SFDC Case: ' + caseRecord.CaseNumber + '\n';
        }

        comments += 'SFDC Reference #: ' + caseRecord.Reference_Number__c + '\n';

        return comments;
    }

    /**
     * @description Result wrapper for quote creation operations
     */
    public class QuoteCreationResult {
        @AuraEnabled public Boolean success { get; set; }
        @AuraEnabled public String quoteId { get; set; }
        @AuraEnabled public String opportunityId { get; set; }
        @AuraEnabled public String errorMessage { get; set; }

        public QuoteCreationResult(Boolean success, String quoteId, String oppId, String error) {
            this.success = success;
            this.quoteId = quoteId;
            this.opportunityId = oppId;
            this.errorMessage = error;
        }
    }
}