objects/Case.object
<CustomObject>
    <fields>
        <fullName>CompanyCategoryCode__c</fullName>
        <label>CompanyCategoryCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Override_Reason__c</fullName>
        <description>The field provide SLA Override reason in the case when the Service Date is not equal to the SLA Date.</description>
        <label>SLA Override Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Repairs</fullName>
                </value>
                <value>
                    <fullName>Corporate Visit/Walkthrough</fullName>
                </value>
                <value>
                    <fullName>Power Outage</fullName>
                </value>
                <value>
                    <fullName>Potential Violation</fullName>
                </value>
                <value>
                    <fullName>Weather/Natural Disaster</fullName>
                </value>
                <value>
                    <fullName>Internal Error</fullName>
                </value>
                <value>
                    <fullName>Vendor Error</fullName>
                </value>
                <value>
                    <fullName>Vendor not able to meet SLA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>NAM/PM</fullName>
                    <isActive>false</isActive>
                    <label>NAM/PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Description_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Waste__c</fullName>
    <label>Description of Waste</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>For SDT-21237 - To navigate from a Quote to the case from which it is originated</description>
    <formula>HYPERLINK(
&quot;/&quot; &amp; SBQQ__Opportunity2__r.Case__c,SBQQ__Opportunity2__r.Case__r.CaseNumber, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Product Configured</fullName>
                <label>Procure Service</label>
            </value>
            <value>
                <fullName>Cost Configured</fullName>
                <label>Configure Price</label>
            </value>
            <value>
                <fullName>Price Configured</fullName>
                <label>Submit for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
            <value>
                <fullName>Correction</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CompanyCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCategoryCode__c</fullName>
    <label>CompanyCategoryCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CompanyCategoryName__c.field-meta.xml
<CustomField>
    <fullName>CompanyCategoryName__c</fullName>
    <description>Store the Company Category Name</description>
    <label>Company Category</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Description_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Waste__c</fullName>
    <label>Description of Waste</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/MaterialGrade__c.field-meta.xml
<CustomField>
    <fullName>MaterialGrade__c</fullName>
    <label>MaterialGrade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Grade</fullName>
            </value>
            <value>
                <fullName>International Trash</fullName>
            </value>
            <value>
                <fullName>WTEND</fullName>
                <label>WTE Non-Diverted</label>
            </value>
            <value>
            <fullName>Waxed OCC</fullName>
            </value>
            <value>
            <fullName>Cardboard 36&quot; Bales</fullName>
            </value>
            <value>
            <fullName>Cardboard 42&quot; Bales</fullName>
            </value>
            <value>
            <fullName>Cardboard 48&quot; Bales</fullName>
            </value>
            <value>
            <fullName>Cardboard 60&quot; Bales</fullName>
            </value>
            <value>
            <fullName>Cardboard 64&quot; Bales</fullName>
            </value>
            <value>
            <fullName>Cardboard 72&quot; Bales</fullName>
            </value>
            <value>
            <fullName>Cardboard Compacted</fullName>
            </value>
            <value>
            <fullName>Cardboard Flattened Loose</fullName>
            </value>
            <value>
            <fullName>Cardboard Reusable Boxes</fullName>
            </value>
            <value>
            <fullName>Cardboard Reusable Boxes - Large</fullName>
            </value>
            <value>
            <fullName>Cardboard Reusable Boxes - Medium</fullName>
            </value>
            <value>
            <fullName>Cardboard Reusable Boxes - Small</fullName>
            </value>
            <value>
            <fullName>Cardboard Strapped to Pallet</fullName>
            </value>
            <value>
            <fullName>Cardboard Whole Loose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ProductOption__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProductOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product option that generated this line (if any).</description>
    <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
    <label>Product Option</label>
    <referenceTo>SBQQ__ProductOption__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.
If you want to change the Start Date, please update the Vendor Commit Date on the Bundle.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

classes/QuoteProcurementQuoteLineServiceTest.cls
/**
 * @description Test class for QuoteProcurementQuoteLineService
 *
 * Tests quote line update operations including:
 * - Updating quote line bundles from header wrapper
 * - Equipment size picklist conversions
 * - Quantity updates for lock products
 * - SLA date updates
 *
 * Utilizes TestDataFactoryRefactored for consistent test data creation.
 *
 * @author Waste Management
 * @date 2025
 * @group Test Classes
 */
@isTest
private class QuoteProcurementQuoteLineServiceTest {

    /**
     * @description Set up test data for all test methods
     */
    @testSetup
    static void setupTestData() {
        // Create test account
        Account testAccount = TestDataFactoryRefactored.createAccount();
        insert testAccount;

        // Create test contact
        Contact testContact = TestDataFactoryRefactored.createContact(testAccount.Id);
        insert testContact;

        // Create test case
        Case testCase = TestDataFactoryRefactored.createCase(testAccount.Id, testContact.Id);
        insert testCase;

        // Create opportunity linked to case
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Case__c = testCase.Id
        );
        insert testOpp;

        // Create quote
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Opportunity2__c = testOpp.Id,
            SBQQ__Status__c = 'Draft',
            SBQQ__PrimaryContact__c = testContact.Id
        );
        insert testQuote;

        // Create test products
        Product2 containerProduct = TestDataFactoryRefactored.createProduct('Test Container', 'Container');
        Product2 wasteCategoryProduct = TestDataFactoryRefactored.createProduct('Test Waste Category', 'Waste Category');
        Product2 accessoryProduct = TestDataFactoryRefactored.createProduct('Test Accessory', 'Accessories');
        insert new List<Product2>{containerProduct, wasteCategoryProduct, accessoryProduct};

        // Create product option for accessories
        SBQQ__ProductOption__c productOption = new SBQQ__ProductOption__c(
            SBQQ__ConfiguredSKU__c = containerProduct.Id,
            SBQQ__OptionalSKU__c = accessoryProduct.Id,
            SBQQ__Type__c = 'Accessory'
        );
        insert productOption;

        // Create parent quote line (container)
        SBQQ__QuoteLine__c parentQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = containerProduct.Id,
            SBQQ__Number__c = 1,
            SBQQ__Quantity__c = 1,
            Equipment_Size__c = '10 Yard',
            SBQQ__StartDate__c = Date.today(),
            SBQQ__EndDate__c = Date.today().addDays(365),
            Description_of_Waste__c = 'Original Waste',
            MaterialGrade__c = 'Grade A',
            CompanyCategoryCode__c = 'CC01',
            CompanyCategoryName__c = 'Category 1'
        );
        insert parentQL;

        // Create child quote line (waste category)
        SBQQ__QuoteLine__c wasteCategoryQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = wasteCategoryProduct.Id,
            SBQQ__RequiredBy__c = parentQL.Id,
            SBQQ__Number__c = 2,
            SBQQ__Quantity__c = 1,
            SBQQ__OptionLevel__c = 1
        );

        // Create accessory quote line
        SBQQ__QuoteLine__c accessoryQL = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = accessoryProduct.Id,
            SBQQ__RequiredBy__c = parentQL.Id,
            SBQQ__Number__c = 3,
            SBQQ__Quantity__c = 2,
            SBQQ__OptionLevel__c = 1,
            SBQQ__ProductOption__c = productOption.Id
        );

        insert new List<SBQQ__QuoteLine__c>{wasteCategoryQL, accessoryQL};
    }

    /**
     * @description Test updateQuoteOverview - success scenario
     */
    @isTest
    static void testUpdateQuoteOverview_Success() {
        SBQQ__QuoteLine__c parentQL = [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__RequiredBy__c = null LIMIT 1];

        // Create header wrapper with update data
        QuoteProcurementController.HeaderWrapper wrapper = new QuoteProcurementController.HeaderWrapper();
        wrapper.parentId = parentQL.Id;
        wrapper.quantity = 3;
        wrapper.equipmentSize = '20 Yard';
        wrapper.wasteDescription = 'Updated Waste Description';
        wrapper.selectedMaterialGrade = 'Grade B';
        wrapper.companyCategory = 'CC02';
        wrapper.companyCategoryName = 'Category 2';
        wrapper.slaOverrideReason = 'Test Reason';
        wrapper.slaOverrideComment = 'Test Comment';

        Test.startTest();
        Boolean result = QuoteProcurementQuoteLineService.updateQuoteOverview(wrapper);
        Test.stopTest();

        System.assertEquals(true, result, 'Update should succeed');

        // Verify parent quote line was updated
        SBQQ__QuoteLine__c updatedParent = [
            SELECT Id, SBQQ__Quantity__c, Equipment_Size__c, Description_of_Waste__c,
                MaterialGrade__c, CompanyCategoryCode__c, CompanyCategoryName__c,
                SLA_Override_Reason__c, SLA_Override_Comment__c
            FROM SBQQ__QuoteLine__c
            WHERE Id = :parentQL.Id
        ];

        System.assertEquals(3, updatedParent.SBQQ__Quantity__c, 'Quantity should be updated');
        System.assertEquals('20 Yard', updatedParent.Equipment_Size__c, 'Equipment size should be updated');
        System.assertEquals('Updated Waste Description', updatedParent.Description_of_Waste__c, 'Waste description should be updated');
        System.assertEquals('Grade B', updatedParent.MaterialGrade__c, 'Material grade should be updated');
        System.assertEquals('CC02', updatedParent.CompanyCategoryCode__c, 'Company category code should be updated');
        System.assertEquals('Category 2', updatedParent.CompanyCategoryName__c, 'Company category name should be updated');
        System.assertEquals('Test Reason', updatedParent.SLA_Override_Reason__c, 'SLA override reason should be updated');
        System.assertEquals('Test Comment', updatedParent.SLA_Override_Comment__c, 'SLA override comment should be updated');
    }

    /**
     * @description Test updateQuoteOverview - verify child lines updated
     */
    @isTest
    static void testUpdateQuoteOverview_VerifyChildLinesUpdated() {
        SBQQ__QuoteLine__c parentQL = [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__RequiredBy__c = null LIMIT 1];

        QuoteProcurementController.HeaderWrapper wrapper = new QuoteProcurementController.HeaderWrapper();
        wrapper.parentId = parentQL.Id;
        wrapper.quantity = 5;
        wrapper.wasteDescription = 'New Waste';
        wrapper.equipmentSize = '30 Yard';

        Test.startTest();
        Boolean result = QuoteProcurementQuoteLineService.updateQuoteOverview(wrapper);
        Test.stopTest();

        System.assertEquals(true, result, 'Update should succeed');

        // Verify child quote lines were updated (except accessories)
        List<SBQQ__QuoteLine__c> childLines = [
            SELECT Id, SBQQ__Quantity__c, Description_of_Waste__c, Equipment_Size__c,
                SBQQ__ProductOption__r.SBQQ__Type__c
            FROM SBQQ__QuoteLine__c
            WHERE SBQQ__RequiredBy__c = :parentQL.Id
        ];

        for (SBQQ__QuoteLine__c child : childLines) {
            System.assertEquals('New Waste', child.Description_of_Waste__c, 'Waste description should be updated on child');
            System.assertEquals('30 Yard', child.Equipment_Size__c, 'Equipment size should be updated on child');

            // Accessories should NOT have quantity updated
            if (child.SBQQ__ProductOption__r.SBQQ__Type__c == 'Accessory') {
                System.assertEquals(2, child.SBQQ__Quantity__c, 'Accessory quantity should NOT be updated');
            } else {
                System.assertEquals(5, child.SBQQ__Quantity__c, 'Non-accessory quantity should be updated');
            }
        }
    }

    /**
     * @description Test updateQuoteOverview - verify null material grade handling
     */
    @isTest
    static void testUpdateQuoteOverview_NullMaterialGrade() {
        SBQQ__QuoteLine__c parentQL = [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__RequiredBy__c = null LIMIT 1];

        QuoteProcurementController.HeaderWrapper wrapper = new QuoteProcurementController.HeaderWrapper();
        wrapper.parentId = parentQL.Id;
        wrapper.quantity = 2;
        wrapper.equipmentSize = '10 Yard';
        wrapper.selectedMaterialGrade = null; // Null material grade

        Test.startTest();
        Boolean result = QuoteProcurementQuoteLineService.updateQuoteOverview(wrapper);
        Test.stopTest();

        System.assertEquals(true, result, 'Update should succeed with null material grade');

        // Verify material grade was not changed
        SBQQ__QuoteLine__c updatedParent = [
            SELECT MaterialGrade__c
            FROM SBQQ__QuoteLine__c
            WHERE Id = :parentQL.Id
        ];

        System.assertEquals('Grade A', updatedParent.MaterialGrade__c, 'Material grade should remain unchanged');
    }

    /**
     * @description Test updateQuoteOverview - verify empty company category handling
     */
    @isTest
    static void testUpdateQuoteOverview_EmptyCompanyCategory() {
        SBQQ__QuoteLine__c parentQL = [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__RequiredBy__c = null LIMIT 1];

        QuoteProcurementController.HeaderWrapper wrapper = new QuoteProcurementController.HeaderWrapper();
        wrapper.parentId = parentQL.Id;
        wrapper.quantity = 2;
        wrapper.equipmentSize = '10 Yard';
        wrapper.companyCategory = '';
        wrapper.companyCategoryName = '';

        Test.startTest();
        Boolean result = QuoteProcurementQuoteLineService.updateQuoteOverview(wrapper);
        Test.stopTest();

        System.assertEquals(true, result, 'Update should succeed with empty company category');

        // Verify company category was not changed
        SBQQ__QuoteLine__c updatedParent = [
            SELECT CompanyCategoryCode__c, CompanyCategoryName__c
            FROM SBQQ__QuoteLine__c
            WHERE Id = :parentQL.Id
        ];

        System.assertEquals('CC01', updatedParent.CompanyCategoryCode__c, 'Company category code should remain unchanged');
        System.assertEquals('Category 1', updatedParent.CompanyCategoryName__c, 'Company category name should remain unchanged');
    }

    /**
     * @description Test updateQuoteOverview - verify SLA date update for parent only
     */
    @isTest
    static void testUpdateQuoteOverview_SLADateUpdate() {
        SBQQ__QuoteLine__c parentQL = [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__RequiredBy__c = null LIMIT 1];

        QuoteProcurementController.HeaderWrapper wrapper = new QuoteProcurementController.HeaderWrapper();
        wrapper.parentId = parentQL.Id;
        wrapper.quantity = 2;
        wrapper.equipmentSize = '10 Yard';

        Test.startTest();
        Boolean result = QuoteProcurementQuoteLineService.updateQuoteOverview(wrapper);
        Test.stopTest();

        System.assertEquals(true, result, 'Update should succeed');

        // Verify SLA date was set on parent (if callDetermineSLA returns a value)
        SBQQ__QuoteLine__c updatedParent = [
            SELECT Quote_SLA_Date__c
            FROM SBQQ__QuoteLine__c
            WHERE Id = :parentQL.Id
        ];

        // SLA date may be null or set depending on callDetermineSLA implementation
        // This test verifies the method was called without error
        System.assertNotEquals(null, updatedParent, 'Parent should exist');
    }

    /**
     * @description Test updateQuoteOverview - error handling (invalid parent ID)
     */
    @isTest
    static void testUpdateQuoteOverview_InvalidParentId() {
        QuoteProcurementController.HeaderWrapper wrapper = new QuoteProcurementController.HeaderWrapper();
        wrapper.parentId = null; // Invalid parent ID
        wrapper.quantity = 2;
        wrapper.equipmentSize = '10 Yard';

        Test.startTest();
        Boolean result = QuoteProcurementQuoteLineService.updateQuoteOverview(wrapper);
        Test.stopTest();

        // Should return false on error
        System.assertEquals(false, result, 'Should return false on error');
    }
}