objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Cost_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Cost_Unit_of_Measure__c</fullName>
    <label>Cost Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_of_Measurements</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/CostModelType__c.field-meta.xml
<CustomField>
    <fullName>CostModelType__c</fullName>
    <label>CostModelType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Price_Model_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Frequency_Interval__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Interval__c</fullName>
    <label>Frequency Interval</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Occurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Type__c</fullName>
    <label>Occurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Occurrence_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/PriceUOM__c.field-meta.xml
<CustomField>
    <fullName>PriceUOM__c</fullName>
    <label>PriceUOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_of_Measurements</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Frequency__c</fullName>
    <label>Schedule Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Cost_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Cost_Unit_of_Measure__c</fullName>
    <label>Cost Unit of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Occurrence_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BNDL</fullName>
                <label>Bundle</label>
            </value>
            <value>
                <fullName>DYS</fullName>
                <label>Days</label>
            </value>
            <value>
                <fullName>ECH</fullName>
                <label>Each</label>
            </value>
            <value>
                <fullName>EV</fullName>
                <label>Event</label>
            </value>
            <value>
                <fullName>FT</fullName>
                <label>Feet</label>
            </value>
            <value>
                <fullName>GL</fullName>
                <label>Gallons</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Hourly</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Inches</label>
            </value>
            <value>
                <fullName>KT</fullName>
                <label>Key Turn</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Metric Tonnes</label>
            </value>
            <value>
                <fullName>MTH</fullName>
                <label>Months</label>
            </value>
            <value>
                <fullName>LB</fullName>
                <label>Pounds</label>
            </value>
            <value>
                <fullName>QTR</fullName>
                <label>Quarters</label>
            </value>
            <value>
                <fullName>TN</fullName>
                <label>Tons</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Weeks</label>
            </value>
            <value>
                <fullName>YD</fullName>
                <label>Yard</label>
            </value>
            <value>
                <fullName>YRS</fullName>
                <label>Years</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/CostModelType__c.field-meta.xml
<CustomField>
    <fullName>CostModelType__c</fullName>
    <label>Cost Model Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PER</fullName>
                <label>Per-Unit</label>
            </value>
            <value>
                <fullName>STP</fullName>
                <label>Stepped</label>
            </value>
            <value>
                <fullName>REB</fullName>
                <label>Rebate</label>
            </value>
            <value>
                <fullName>MRG</fullName>
                <label>Margin</label>
            </value>
            <value>
                <fullName>MRS</fullName>
                <label>Margin Stepped</label>
            </value>
            <value>
                <fullName>ZCH</fullName>
                <label>Zero Charge</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Occurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Type__c</fullName>
    <label>Occurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OC</fullName>
                <label>On-Call</label>
            </value>
            <value>
                <fullName>SOC</fullName>
                <label>Scheduled On-Call</label>
            </value>
            <value>
                <fullName>SCH</fullName>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>OnCall`</fullName>
                <isActive>false</isActive>
                <label>OnCall`</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PriceUOM__c.field-meta.xml
<CustomField>
    <fullName>PriceUOM__c</fullName>
    <label>Price Unit of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Occurrence_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BNDL</fullName>
                <label>Bundle</label>
            </value>
            <value>
                <fullName>DYS</fullName>
                <label>Days</label>
            </value>
            <value>
                <fullName>ECH</fullName>
                <label>Each</label>
            </value>
            <value>
                <fullName>EV</fullName>
                <label>Event</label>
            </value>
            <value>
                <fullName>FT</fullName>
                <label>Feet</label>
            </value>
            <value>
                <fullName>GL</fullName>
                <label>Gallons</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Hourly</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Inches</label>
            </value>
            <value>
                <fullName>KT</fullName>
                <label>Key Turn</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Metric Tonnes</label>
            </value>
            <value>
                <fullName>MTH</fullName>
                <label>Months</label>
            </value>
            <value>
                <fullName>LB</fullName>
                <label>Pounds</label>
            </value>
            <value>
                <fullName>QTR</fullName>
                <label>Quarters</label>
            </value>
            <value>
                <fullName>TN</fullName>
                <label>Tons</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Weeks</label>
            </value>
            <value>
                <fullName>YD</fullName>
                <label>Yards</label>
            </value>
            <value>
                <fullName>YRS</fullName>
                <label>Years</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ProductOption__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProductOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product option that generated this line (if any).</description>
    <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
    <label>Product Option</label>
    <referenceTo>SBQQ__ProductOption__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.
If you want to change the Start Date, please update the Vendor Commit Date on the Bundle.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Frequency__c</fullName>
    <label>Schedule Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Schedule_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SID__c.field-meta.xml
<CustomField>
    <fullName>SID__c</fullName>
    <label>SID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Cost_Price_Model_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PER</fullName>
        <default>true</default>
        <label>Per-Unit</label>
    </customValue>
    <customValue>
        <fullName>Stepped</fullName>
    </customValue>
    <customValue>
        <fullName>Rebate</fullName>
    </customValue>
    <customValue>
        <fullName>Margin</fullName>
    </customValue>
    <customValue>
        <fullName>Margin Stepped</fullName>
    </customValue>
    <customValue>
        <fullName>Zero Charge</fullName>
    </customValue>
    <description>The cost and price model types to be used by Salesforce CPQ</description>
    <masterLabel>Cost/Price Model Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Occurrence_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OC</fullName>
        <label>On-Call</label>
    </customValue>
    <customValue>
        <fullName>SOC</fullName>
        <label>Scheduled On-Call</label>
    </customValue>
    <customValue>
        <fullName>SCH</fullName>
        <label>Scheduled</label>
    </customValue>
    <description>The schedule type/occurrence type of a product to be used by the CPQ Configurator</description>
    <masterLabel>Occurrence Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Schedule_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>D</fullName>
        <label>Daily</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>Weekly</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>Monthly</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yearly</label>
    </customValue>
    <masterLabel>Schedule Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit_of_Measurements.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BNDL</fullName>
        <label>Bundle</label>
    </customValue>
    <customValue>
        <fullName>DYS</fullName>
        <label>Days</label>
    </customValue>
    <customValue>
        <fullName>ECH</fullName>
        <label>Each</label>
    </customValue>
    <customValue>
        <fullName>EV</fullName>
        <label>Event</label>
    </customValue>
    <customValue>
        <fullName>FT</fullName>
        <label>Feet</label>
    </customValue>
    <customValue>
        <fullName>GL</fullName>
        <label>Gallons</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Hourly</label>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
        <label>Inches</label>
    </customValue>
    <customValue>
        <fullName>KT</fullName>
        <label>Key Turn</label>
    </customValue>
    <customValue>
        <fullName>LB</fullName>
        <label>Pounds</label>
    </customValue>
    <customValue>
        <fullName>MTH</fullName>
        <label>Months</label>
    </customValue>
    <customValue>
        <fullName>QTR</fullName>
        <label>Quarters</label>
    </customValue>
    <customValue>
        <fullName>TN</fullName>
        <label>Tons</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>Weeks</label>
    </customValue>
    <customValue>
        <fullName>YD</fullName>
        <label>Yards</label>
    </customValue>
    <customValue>
        <fullName>YRS</fullName>
        <label>Years</label>
    </customValue>
    <masterLabel>Unit of Measurements</masterLabel>
</GlobalValueSet>

classes/QuoteProcurementProductOptionService.cls
/**
 * @description QuoteProcurementProductOptionService - Handles product option operations
 *
 * This service manages operations related to product options on quote lines, including:
 * - Adding product options to quote lines
 * - Removing product options from quote lines
 * - Updating key quantities for accessory options
 *
 * Key Responsibilities:
 * - Create quote lines for product options with proper field mappings
 * - Handle special logic for Keys products (end date = start date)
 * - Remove accessory and key quote lines
 * - Bulk update key quantities
 *
 * Architecture:
 * - Follows service layer patterns from QuoteProcurementFavoritesService
 * - Uses standard error handling with AuraHandledException
 * - Integrates with UTIL_LoggingService for error tracking
 * - Returns operation results as strings ('SUCCESS' or error message)
 *
 * @author Waste Management
 * @date 2025
 * @group Service Layer - Product Options Management
 */
public with sharing class QuoteProcurementProductOptionService {

    // ========================================================================
    // PUBLIC API - PRODUCT OPTION MANAGEMENT
    // ========================================================================

    /**
     * @description Add a product option to a quote line
     * Refactored from: addProductOption() in QuoteProcurementController
     *
     * Creates a new child quote line for the specified product option.
     * Special handling for Keys products: sets end date equal to start date.
     *
     * @param quoteLineId The parent quote line ID
     * @param productOptionId The product option ID to add
     * @return String The created quote line ID on success, or error message on failure
     */
    @AuraEnabled
    public static String addProductOption(Id quoteLineId, Id productOptionId) {
        System.debug('QuoteProcurementProductOptionService.addProductOption - Start');
        System.debug('quoteLineId: ' + quoteLineId + ', productOptionId: ' + productOptionId);

        try {
            // Query parent quote line and its children
            List<SBQQ__QuoteLine__c> quoteLines = [
                SELECT Id, SBQQ__Number__c, SBQQ__StartDate__c, Equipment_Size__c,
                       SBQQ__Quote__c, SID__c
                FROM SBQQ__QuoteLine__c
                WHERE Id = :quoteLineId OR SBQQ__RequiredBy__c = :quoteLineId
                ORDER BY SBQQ__Number__c DESC
            ];

            if (quoteLines.isEmpty()) {
                throw new AuraHandledException('Quote line not found with ID: ' + quoteLineId);
            }

            // Query product option details
            SBQQ__ProductOption__c prodOption = [
                SELECT Id, SBQQ__OptionalSKU__c, SBQQ__OptionalSKU__r.Name,
                       SBQQ__OptionalSKU__r.ProductCode, SBQQ__Quantity__c, Occurrence_Type__c,
                       CostModelType__c, Cost_Unit_of_Measure__c, PriceUOM__c,
                       Schedule_Frequency__c, Frequency_Interval__c
                FROM SBQQ__ProductOption__c
                WHERE Id = :productOptionId
            ];

            // Build new quote line for the option
            SBQQ__QuoteLine__c qLine = new SBQQ__QuoteLine__c(
                SBQQ__Quote__c = quoteLines[0].SBQQ__Quote__c,
                SBQQ__Product__c = prodOption.SBQQ__OptionalSKU__c,
                Equipment_Size__c = quoteLines[0].Equipment_Size__c,
                SBQQ__RequiredBy__c = quoteLineId,
                SBQQ__ProductOption__c = prodOption.Id,
                SBQQ__OptionLevel__c = 1,
                SBQQ__Number__c = quoteLines[0].SBQQ__Number__c + 1,
                SBQQ__CostEditable__c = true,
                SBQQ__PriceEditable__c = true,
                SBQQ__Quantity__c = prodOption.SBQQ__Quantity__c,
                Occurrence_Type__c = prodOption.Occurrence_Type__c,
                CostModelType__c = prodOption.CostModelType__c,
                Cost_Unit_of_Measure__c = prodOption.Cost_Unit_of_Measure__c,
                PriceUOM__c = prodOption.PriceUOM__c,
                Schedule_Frequency__c = prodOption.Schedule_Frequency__c,
                Frequency_Interval__c = prodOption.Frequency_Interval__c,
                SBQQ__StartDate__c = quoteLines[0].SBQQ__StartDate__c,
                SID__c = quoteLines[0].SID__c
            );

            System.debug('Created quote line: ' + qLine);

            // Special handling for Keys products - set end date = start date
            if (prodOption.SBQQ__OptionalSKU__r.Name == Constant_Util.KEYS) {
                qLine.SBQQ__EndDate__c = qLine.SBQQ__StartDate__c;
                System.debug('Keys product detected - setting end date = start date');
            }

            // Insert the quote line
            insert qLine;
            System.debug('Quote line inserted successfully: ' + qLine.Id);

            return String.valueOf(qLine.Id);

        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'Error in addProductOption: ' + ex.getMessage());
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.ERROR_APPLICATION,
                LoggingLevel.ERROR
            );
            return ex.getMessage();
        }
    }

    /**
     * @description Remove a product option from a quote line
     * Refactored from: removeProductOption(Id, Id) in QuoteProcurementController
     *
     * Deletes the child quote line associated with the specified product option.
     *
     * @param quoteLineId The parent quote line ID
     * @param productOptionId The optional SKU ID of the product option to remove
     * @return String 'SUCCESS' on success, or error message on failure
     */
    @AuraEnabled
    public static String removeProductOption(Id quoteLineId, Id productOptionId) {
        System.debug('QuoteProcurementProductOptionService.removeProductOption - Start');
        System.debug('quoteLineId: ' + quoteLineId + ', productOptionId: ' + productOptionId);

        try {
            // Find the child quote line to remove
            SBQQ__QuoteLine__c quoteLine = [
                SELECT Id
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__RequiredBy__c = :quoteLineId
                AND SBQQ__ProductOption__r.SBQQ__OptionalSKU__c = :productOptionId
                LIMIT 1
            ];

            delete quoteLine;
            System.debug('Quote line deleted successfully');

            return 'SUCCESS';

        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'Error in removeProductOption: ' + ex.getMessage());
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.ERROR_APPLICATION,
                LoggingLevel.ERROR
            );
            return ex.getMessage();
        }
    }

    /**
     * @description Remove a product option and its associated keys from a quote line
     * Refactored from: removeProductOption(Id, Id, Id) in QuoteProcurementController
     *
     * Deletes both the accessory quote line and any associated key quote lines.
     * This is used when an accessory that has keys is unchecked.
     *
     * @param quoteLineId The parent quote line ID
     * @param productOptionId The optional SKU ID of the accessory to remove
     * @param keyOptionId The product option ID of the associated key
     * @return String 'SUCCESS' on success, or error message on failure
     */
    @AuraEnabled
    public static String removeProductOptionWithKeys(Id quoteLineId, Id productOptionId, Id keyOptionId) {
        System.debug('QuoteProcurementProductOptionService.removeProductOptionWithKeys - Start');
        System.debug('quoteLineId: ' + quoteLineId + ', productOptionId: ' + productOptionId +
                    ', keyOptionId: ' + keyOptionId);

        try {
            // Find both the accessory and key quote lines to remove
            List<SBQQ__QuoteLine__c> quoteLine = [
                SELECT Id
                FROM SBQQ__QuoteLine__c
                WHERE (SBQQ__RequiredBy__c = :quoteLineId
                       AND SBQQ__ProductOption__r.SBQQ__OptionalSKU__c = :productOptionId)
                OR (SBQQ__RequiredBy__r.SBQQ__RequiredBy__c = :quoteLineId
                    AND SBQQ__ProductOption__c = :keyOptionId)
                LIMIT 2
            ];

            delete quoteLine;
            System.debug('Quote lines deleted successfully: ' + quoteLine.size() + ' records');

            return 'SUCCESS';

        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'Error in removeProductOptionWithKeys: ' + ex.getMessage());
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.ERROR_APPLICATION,
                LoggingLevel.ERROR
            );
            return ex.getMessage();
        }
    }

    /**
     * @description Update quantities on key quote lines
     * Refactored from: updateKeysQuantity() in QuoteProcurementController
     *
     * Updates the quantities for padlock key quote lines based on the provided map.
     * Used when user adjusts key quantities for accessories.
     *
     * @param parentId The parent quote line ID
     * @param keyObj List of KeyMapWrapper objects containing key IDs and quantities
     * @return String 'SUCCESS' on success, or error message on failure
     */
    @AuraEnabled
    public static String updateKeysQuantity(Id parentId, List<QuoteProcurementController.KeyMapWrapper> keyObj) {
        System.debug('QuoteProcurementProductOptionService.updateKeysQuantity - Start');
        System.debug('parentId: ' + parentId + ', keyObj size: ' + keyObj.size());

        try {
            // Build sets and maps from the key objects
            Set<String> idSet = new Set<String>();
            Map<String, String> keyMap = new Map<String, String>();

            for (QuoteProcurementController.KeyMapWrapper obj : keyObj) {
                System.debug('Processing key: ' + obj.id + ' = ' + obj.value);
                idSet.add((String)obj.id);
                keyMap.put((String)obj.id, (String)obj.value);
            }

            // Query the key quote lines
            List<SBQQ__QuoteLine__c> quoteLines = [
                SELECT Id, SBQQ__Quantity__c, SBQQ__ProductOption__c
                FROM SBQQ__QuoteLine__c
                WHERE SBQQ__RequiredBy__r.SBQQ__RequiredBy__c = :parentId
                AND SBQQ__ProductOption__c IN :idSet
            ];

            System.debug('Found ' + quoteLines.size() + ' key quote lines to update');

            // Update quantities
            List<SBQQ__QuoteLine__c> updatedQuoteLinesList = new List<SBQQ__QuoteLine__c>();

            for (SBQQ__QuoteLine__c ql : quoteLines) {
                if (keyMap.containsKey(ql.SBQQ__ProductOption__c)) {
                    String quantityValue = keyMap.get(ql.SBQQ__ProductOption__c);
                    ql.SBQQ__Quantity__c = (quantityValue == null || quantityValue == '')
                        ? 0
                        : Decimal.valueOf(quantityValue);
                    updatedQuoteLinesList.add(ql);
                }
            }

            // Perform update if there are changes
            if (!updatedQuoteLinesList.isEmpty()) {
                update updatedQuoteLinesList;
                System.debug('Updated ' + updatedQuoteLinesList.size() + ' quote lines');
            }

            return 'SUCCESS';

        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'Error in updateKeysQuantity: ' + ex.getMessage());
            UTIL_LoggingService.logHandledException(
                ex,
                UserInfo.getOrganizationId(),
                UTIL_ErrorConstants.ERROR_APPLICATION,
                LoggingLevel.ERROR
            );
            return ex.getMessage();
        }
    }
}