objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuantityEditable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag that determines whether the quantity is editable.</description>
        <inlineHelpText>Allow or prevent changing the quantity for this product.</inlineHelpText>
        <label>Quantity Editable</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ConfigurationAttribute__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description>Picklist values field, used to temporarily store values programmatically and retrieve in custom components</description>
    <label>Picklist Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__ConfigurationAttribute__c/fields/SBQQ__TargetField__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TargetField__c</fullName>
    <description>Field on the Product Option that sources remaining metadata and holds the value.</description>
    <inlineHelpText>Specify field on Product Option that will hold this attribute&apos;s value.</inlineHelpText>
    <label>Target Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unit Price</fullName>
            </value>
            <value>
                <fullName>Discount (Amt)</fullName>
            </value>
            <value>
                <fullName>Discount (%)</fullName>
            </value>
            <value>
                <fullName>Ownership__c</fullName>
            </value>
            <value>
                <fullName>Duration__c</fullName>
            </value>
            <value>
                <fullName>Description_of_Waste__c</fullName>
            </value>
            <value>
                <fullName>Certificate_of_Disposal__c</fullName>
            </value>
            <value>
                <fullName>Equipment_Style__c</fullName>
            </value>
            <value>
                <fullName>Service_Style__c</fullName>
            </value>
            <value>
                <fullName>Vendor__c</fullName>
            </value>
            <value>
                <fullName>Compactor_Type__c</fullName>
            </value>
            <value>
                <fullName>Certificate_of_Destruction__c</fullName>
            </value>
            <value>
                <fullName>Equipment_Schedule_Type__c</fullName>
            </value>
            <value>
                <fullName>Equipment_Size__c</fullName>
            </value>
            <value>
                <fullName>Compactor_Size__c</fullName>
            </value>
            <value>
                <fullName>Profile_Number__c</fullName>
            </value>
            <value>
                <fullName>Equipment_Side_Doors__c</fullName>
            </value>
            <value>
                <fullName>Understructure__c</fullName>
            </value>
            <value>
                <fullName>Occurrence_Type__c</fullName>
            </value>
            <value>
                <fullName>Schedule_Frequency__c</fullName>
            </value>
            <value>
                <fullName>Type_of_Lid__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Certificate_of_Destruction__c.field-meta.xml
<CustomField>
    <fullName>Certificate_of_Destruction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certificate of Destruction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Certificate_of_Disposal__c.field-meta.xml
<CustomField>
    <fullName>Certificate_of_Disposal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certificate of Disposal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Description_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Waste__c</fullName>
    <label>Description of Waste</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Equipment_Style__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Style__c</fullName>
    <label>Equipment Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Style</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Occurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Type__c</fullName>
    <label>Occurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Occurrence_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <label>Ownership</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ownership</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Profile_Number__c.field-meta.xml
<CustomField>
    <fullName>Profile_Number__c</fullName>
    <label>Profile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The vendor who will be providing the service to the container</description>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Options</relationshipLabel>
    <relationshipName>Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Certificate_of_Destruction__c.field-meta.xml
<CustomField>
    <fullName>Certificate_of_Destruction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certificate of Destruction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Certificate_of_Disposal__c.field-meta.xml
<CustomField>
    <fullName>Certificate_of_Disposal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certificate of Disposal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Description_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Waste__c</fullName>
    <label>Description of Waste</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Equipment_Size__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Size__c</fullName>
    <label>Equipment Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quote_Equipment_Sizes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Equipment_Style__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Style__c</fullName>
    <label>Equipment Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equipment_Style</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Occurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Type__c</fullName>
    <label>Occurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OC</fullName>
                <label>On-Call</label>
            </value>
            <value>
                <fullName>SOC</fullName>
                <label>Scheduled On-Call</label>
            </value>
            <value>
                <fullName>SCH</fullName>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>OnCall`</fullName>
                <isActive>false</isActive>
                <label>OnCall`</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <label>Ownership</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ownership</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Profile_Number__c.field-meta.xml
<CustomField>
    <fullName>Profile_Number__c</fullName>
    <label>Profile Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ProductOption__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProductOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product option that generated this line (if any).</description>
    <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
    <label>Product Option</label>
    <referenceTo>SBQQ__ProductOption__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The payable entity related to this quote line</description>
    <inlineHelpText>The payable vendor related to this quote line.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Equipment_Style.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Slant Top</fullName>
    </customValue>
    <customValue>
        <fullName>Tall</fullName>
    </customValue>
    <customValue>
        <fullName>Split Container</fullName>
    </customValue>
    <customValue>
        <fullName>Cathedral</fullName>
    </customValue>
    <customValue>
        <fullName>Loading Dock</fullName>
    </customValue>
    <customValue>
        <fullName>Apartment Style</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Crusher</fullName>
    </customValue>
    <customValue>
        <fullName>Horizontal</fullName>
    </customValue>
    <customValue>
        <fullName>Vertical</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Top</fullName>
    </customValue>
    <customValue>
        <fullName>Slant-Top</fullName>
        <isActive>false</isActive>
        <label>Slant-Top</label>
    </customValue>
    <masterLabel>Equipment Style</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Occurrence_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OC</fullName>
        <label>On-Call</label>
    </customValue>
    <customValue>
        <fullName>SOC</fullName>
        <label>Scheduled On-Call</label>
    </customValue>
    <customValue>
        <fullName>SCH</fullName>
        <label>Scheduled</label>
    </customValue>
    <description>The schedule type/occurrence type of a product to be used by the CPQ Configurator</description>
    <masterLabel>Occurrence Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Ownership.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLT</fullName>
        <label>Customer Owned</label>
    </customValue>
    <customValue>
        <fullName>VDR</fullName>
        <label>Vendor Owned</label>
    </customValue>
    <customValue>
        <fullName>GRL</fullName>
        <label>Greenleaf Owned</label>
    </customValue>
    <customValue>
        <fullName>MLS</fullName>
        <label>Mall/Landlord Owned</label>
    </customValue>
    <customValue>
        <fullName>UKW</fullName>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>LRC</fullName>
        <label>Lease/Rental Company</label>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <masterLabel>Ownership</masterLabel>
</GlobalValueSet>

classes/QuoteProcurementProductService.cls
/**
 * @description QuoteProcurementProductService - Product configuration and option management layer
 *
 * This service handles product options, accessories, configuration attributes,
 * and product rules for QuoteLines.
 *
 * Key Responsibilities:
 * - Product option management (add/remove)
 * - Accessory management
 * - Configuration attribute handling
 * - Product rule evaluation
 * - Keys and quantity management
 *
 * @author Waste Management
 * @date 2025
 * @group Service Layer - Product Configuration
 */
public with sharing class QuoteProcurementProductService {

    // ========================================================================
    // PUBLIC API - ACCESSORY MANAGEMENT
    // ========================================================================

    /**
     * @description Get accessories with selection for a product
     * Refactored from: getAccessoriesWithSelection() in QuoteProcurementController
     * @param productId The Product2 ID
     * @param quoteId The Quote ID
     * @return Map<String,List<Object>> Map of accessories and selections
     */
    @AuraEnabled
    public static Map<String, List<Object>> getAccessoriesWithSelection(Id productId, Id quoteId) {
        List<Id> selectedAccessoryList = new List<Id>();
        List<Id> disabledAccessoryList = new List<Id>();
        Map<Id, Id> mapOptionIdAndOptionSKUId = new Map<Id, Id>();

        QuoteLineSelector.getProductOptionForQuote(
            quoteId,
            selectedAccessoryList,
            mapOptionIdAndOptionSKUId,
            disabledAccessoryList
        );

        Map<String, List<Object>> mapSelectedAndAvailableAssesory = new Map<String, List<Object>>();
        mapSelectedAndAvailableAssesory.put('AllAccessory', ProductServices.filterProductOptions(productId, quoteId));
        mapSelectedAndAvailableAssesory.put('SelectedAccessory', selectedAccessoryList);
        mapSelectedAndAvailableAssesory.put('mapOptionIdAndOptionSKUId', new List<Object>{mapOptionIdAndOptionSKUId});
        mapSelectedAndAvailableAssesory.put('disabledAccessoryList', disabledAccessoryList);

        return mapSelectedAndAvailableAssesory;
    }

    /**
     * @description Get accessories for a product
     * Refactored from: getAccessories() in QuoteProcurementController
     * @param productId The Product2 ID
     * @return List<SBQQ__ProductOption__c> List of accessories
     */
    @AuraEnabled
    public static List<SBQQ__ProductOption__c> getAccessories(Id productId) {
        return [
            SELECT Id, SBQQ__ConfiguredSKU__r.Name, SBQQ__OptionalSKU__c,
                   SBQQ__OptionalSKU__r.Name, SBQQ__QuantityEditable__c, SBQQ__Quantity__c
            FROM SBQQ__ProductOption__c
            WHERE SBQQ__ConfiguredSKU__c = :productId
                  AND SBQQ__Feature__r.Name IN ('Additional Services', 'General Accessories')
            ORDER BY SBQQ__Number__c DESC
        ];
    }

    /**
     * @description Get padlock keys for products
     * Refactored from: getPadlockKeys() in QuoteProcurementController
     * @param padLockIdList List of padlock Product IDs
     * @return List<SBQQ__ProductOption__c> List of key options
     */
    @AuraEnabled
    public static List<SBQQ__ProductOption__c> getPadlockKeys(List<Id> padLockIdList) {
        List<SBQQ__ProductOption__c> accessoryList = [
            SELECT Id, SBQQ__ConfiguredSKU__r.Name, SBQQ__ConfiguredSKU__c,
                   SBQQ__OptionalSKU__c, SBQQ__OptionalSKU__r.Name,
                   SBQQ__QuantityEditable__c, SBQQ__Quantity__c
            FROM SBQQ__ProductOption__c
            WHERE SBQQ__ConfiguredSKU__c IN :padLockIdList
        ];

        return accessoryList.isEmpty() ? null : accessoryList;
    }

    // ========================================================================
    // PUBLIC API - CONFIGURATION ATTRIBUTES
    // ========================================================================

    /**
     * @description Get configuration attributes for a product
     * Returns attributes with picklist values
     * @param productId The Product2 ID
     * @param quoteLineId The QuoteLine ID
     * @return List<SBQQ__ConfigurationAttribute__c> Configuration attributes
     */
    @AuraEnabled
    public static List<SBQQ__ConfigurationAttribute__c> getConfigAttributes(Id productId,
                                                                            String quoteLineId) {
        // Product-specific equipment style exclusions
        Map<String, Set<String>> equipmentStyleValuesWithProduct = new Map<String, Set<String>>();
        equipmentStyleValuesWithProduct.put('Dumpster',
            new Set<String>{'Apartment Style', 'Pre-Crusher', 'Horizontal', 'Vertical'});
        equipmentStyleValuesWithProduct.put('Compactor',
            new Set<String>{'Slant Top', 'Tall', 'Split Container', 'Cathedral', 'Loading Dock', 'Slant-Top'});

        String currentProductName;
        if (String.isNotBlank(productId)) {
            Product2 productObj = [SELECT Id, Name FROM Product2 WHERE Id = :productId LIMIT 1];
            if (productObj != null) {
                currentProductName = productObj.Name;
            }
        }

        List<SBQQ__ConfigurationAttribute__c> attributeList = [
            SELECT Id, SBQQ__TargetField__c, SBQQ__ApplyToProductOptions__c, SBQQ__Product__r.Name,
                   SBQQ__ColumnOrder__c, SBQQ__DisplayOrder__c, SBQQ__Feature__r.Name,
                   Picklist_Values__c, Name
            FROM SBQQ__ConfigurationAttribute__c
            WHERE SBQQ__Product__c = :productId
                  AND SBQQ__TargetField__c NOT IN (
                      'Equipment_Size__c', 'Duration', 'Occurrence_Type__c',
                      'Certificate_of_Destruction__c', 'Certificate_of_Disposal__c',
                      'Description_of_Waste__c', 'Profile_Number__c', 'Vendor__c'
                  )
            ORDER BY SBQQ__Feature__r.Name ASC, SBQQ__DisplayOrder__c ASC, SBQQ__ColumnOrder__c ASC
        ];

        // Build field list for dynamic query
        String configList = '';
        for (SBQQ__ConfigurationAttribute__c conf : attributeList) {
            if (String.isBlank(configList)) {
                configList = conf.SBQQ__TargetField__c;
            } else {
                configList += ', ' + conf.SBQQ__TargetField__c;
            }
        }

        // Query QuoteLine for current values
        String queryString = 'SELECT Id, ' + configList +
                           ' FROM SBQQ__QuoteLine__c WHERE Id = :quoteLineId LIMIT 1';
        SBQQ__QuoteLine__c targetQL = Database.query(queryString);

        // Build picklist options with selected values
        for (SBQQ__ConfigurationAttribute__c conf : attributeList) {
            List<PicklistSelect> picklistOptions = new List<PicklistSelect>();
            Schema.DescribeFieldResult dfr = SBQQ__QuoteLine__c.SObjectType.getDescribe()
                .fields.getMap()
                .get(conf.SBQQ__TargetField__c)
                .getDescribe();

            List<Schema.PicklistEntry> ple = dfr.getPicklistValues();
            for (Schema.PicklistEntry p : ple) {
                PicklistSelect ps = new PicklistSelect();
                ps.value = p.getValue();
                ps.label = p.getLabel();
                ps.selected = (p.getValue() == targetQL.get(conf.SBQQ__TargetField__c));

                // Filter equipment style options based on product
                if (conf.SBQQ__TargetField__c.equalsIgnoreCase('Equipment_Style__c')) {
                    Boolean isOptionValid = isEquipmentStyleOptionValid(
                        equipmentStyleValuesWithProduct,
                        currentProductName,
                        conf.SBQQ__TargetField__c,
                        ps.value
                    );
                    if (isOptionValid) {
                        picklistOptions.add(ps);
                    }
                } else {
                    picklistOptions.add(ps);
                }
            }

            conf.Picklist_Values__c = JSON.serialize(picklistOptions);
        }

        return attributeList;
    }

    /**
     * @description Update configuration attribute on QuoteLines
     * @param quoteLineId The QuoteLine ID
     * @param fieldName The field API name
     * @param fieldValue The new value
     * @param quoteId The Quote ID
     * @return String 'SUCCESS' or error message
     */
    @AuraEnabled
    public static String updateConfigAttribute(Id quoteLineId, String fieldName,
                                               String fieldValue, Id quoteId) {
        String queryString = 'SELECT Id, SBQQ__Quote__c, ' +
                           String.escapeSingleQuotes(fieldName) +
                           ' FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :quoteId';

        List<SBQQ__QuoteLine__c> quoteLines = Database.query(queryString);

        for (SBQQ__QuoteLine__c ql : quoteLines) {
            if (fieldName == 'Ownership__c') {
                ql.Ownership__c = fieldValue;
            } else if (ql.Id == quoteLineId) {
                ql.put(fieldName, fieldValue);
            }
        }

        try {
            update quoteLines;
            return 'SUCCESS';
        } catch (Exception e) {
            return e.getMessage();
        }
    }

    // ========================================================================
    // PUBLIC API - PRODUCT RULES
    // ========================================================================

    /**
     * @description Get product rules for configuration
     * @param productId The Product2 ID
     * @return List<SBQQ__ErrorCondition__c> Product rules
     */
    @AuraEnabled
    public static List<SBQQ__ErrorCondition__c> getProductRules(Id productId) {
        List<SBQQ__ErrorCondition__c> errorConditions = new List<SBQQ__ErrorCondition__c>();
        Set<Id> ruleIds = new Set<Id>();

        List<SBQQ__ConfigurationRule__c> configRules = [
            SELECT Id, SBQQ__Product__c, SBQQ__ProductRule__c
            FROM SBQQ__ConfigurationRule__c
            WHERE SBQQ__Product__c = :productId AND SBQQ__Active__c = true
        ];

        if (configRules.isEmpty()) {
            return errorConditions;
        }

        for (SBQQ__ConfigurationRule__c c : configRules) {
            ruleIds.add(c.SBQQ__ProductRule__c);
        }

        errorConditions = [
            SELECT Id, SBQQ__Rule__c, SBQQ__TestedField__c, SBQQ__Operator__c,
                   SBQQ__FilterType__c, SBQQ__FilterValue__c
            FROM SBQQ__ErrorCondition__c
            WHERE SBQQ__Rule__c IN :ruleIds AND SBQQ__Operator__c = 'equals'
        ];

        return errorConditions;
    }

    // ========================================================================
    // PRIVATE HELPER METHODS
    // ========================================================================

    /**
     * @description Validate equipment style option by product name
     * @param equipmentStyleMap Map of product to excluded styles
     * @param productName Current product name
     * @param targetField Target field name
     * @param equipmentStyleOption Option value to check
     * @return Boolean True if valid
     */
    private static Boolean isEquipmentStyleOptionValid(
        Map<String, Set<String>> equipmentStyleMap,
        String productName,
        String targetField,
        String equipmentStyleOption
    ) {
        if (equipmentStyleMap.containsKey(productName) &&
            targetField.equalsIgnoreCase('Equipment_Style__c') &&
            !equipmentStyleMap.get(productName).contains(equipmentStyleOption)) {
            return true;
        }
        return false;
    }

    // ========================================================================
    // INNER CLASSES
    // ========================================================================

    /**
     * @description Wrapper for picklist selection
     */
    public class PicklistSelect {
        @AuraEnabled public String value {get; set;}
        @AuraEnabled public String label {get; set;}
        @AuraEnabled public Boolean selected {get; set;}
    }
}